// @vegastack icon-components@0.24.3 sha256-7yEg5fIYkyH1cpD5bNKn6SGOvMh+VUqHWLYF6eSSjEM=

import {
  BriefcaseBusiness,
  ChartNoAxesCombined,
  Target,
  Handshake,
  Presentation,
  Megaphone,
  BadgeCheck,
  Award,
  Trophy,
  Medal,
  Milestone,
  Rocket,
  TrendingUp,
  Calculator,
  Receipt,
  Banknote,
  Wallet,
  CreditCard,
  Scale,
  Factory,
  UsersRound,
  UserRound,
  Contact,
  IdCard,
  Accessibility,
  Baby,
  PersonStanding,
  HeartHandshake,
  HandHelping,
  GraduationCap,
  Stethoscope,
  HardHat,
  ShieldCheck,
  FingerprintPattern,
  KeyRound,
  FaceSlightlySmiling,
  Brain,
  Eye,
  Ear,
  Hand,
  MessageCircle,
  MessagesSquare,
  Mail,
  Phone,
  Video,
  Mic,
  Radio,
  Satellite,
  Send,
  Inbox,
  AtSign,
  Bell,
  Rss,
  MicSignal,
  Speech,
  Headphones,
  Volume2,
  Languages,
  Webcam,
  Antenna,
  FileText,
  Files,
  FolderOpen,
  BookOpen,
  NotebookPen,
  StickyNote,
  Newspaper,
  ClipboardList,
  ScrollText,
  LibraryBig,
  Bookmark,
  Paperclip,
  Archive,
  Package,
  Image,
  Film,
  Music,
  Map,
  Ticket,
  ScanLine,
  CodeXml,
  Terminal,
  Bug,
  Cpu,
  CircuitBoard,
  Database,
  Server,
  Cloud,
  Network,
  Wifi,
  EthernetPort,
  Bluetooth,
  Usb,
  PlugZap,
  BatteryCharging,
  Monitor,
  Smartphone,
  Tablet,
  Keyboard,
  Mouse,
  Layers,
  ListTodo,
  CalendarDays,
  Clock,
  Timer,
  AlarmClock,
  Check,
  SquareCheckBig,
  Flag,
  Tag,
  Kanban,
  Search,
  Funnel,
  Settings2,
  Wrench,
  Workflow,
  GitBranch,
  Puzzle,
  Link,
  Split,
  House,
  BuildingComplex,
  Store,
  Warehouse,
  Hospital,
  School,
  University,
  Church,
  Landmark,
  Tent,
  Mountain,
  Trees,
  Globe,
  Compass,
  Navigation,
  MapPin,
  Route,
  Plane,
  TrainFront,
  Ship,
  Lightbulb,
  Sparkles,
  Star,
  Heart,
  Flame,
  Zap,
  Sun,
  Moon,
  Umbrella,
  Coffee,
  Apple,
  Leaf,
  Flower2,
  PawPrint,
  Gem,
  Gift,
  ShoppingCart,
  ShoppingBag,
  Camera,
  Palette,
} from "lucide-react";
import type { IconName } from "@/lib/icon-data";
/** Explicit canonical exports keep renderer code independent of picker state and emoji data. */
export const ICON_COMPONENTS = {
  "briefcase-business": BriefcaseBusiness,
  "chart-no-axes-combined": ChartNoAxesCombined,
  target: Target,
  handshake: Handshake,
  presentation: Presentation,
  megaphone: Megaphone,
  "badge-check": BadgeCheck,
  award: Award,
  trophy: Trophy,
  medal: Medal,
  milestone: Milestone,
  rocket: Rocket,
  "trending-up": TrendingUp,
  calculator: Calculator,
  receipt: Receipt,
  banknote: Banknote,
  wallet: Wallet,
  "credit-card": CreditCard,
  scale: Scale,
  factory: Factory,
  "users-round": UsersRound,
  "user-round": UserRound,
  contact: Contact,
  "id-card": IdCard,
  accessibility: Accessibility,
  baby: Baby,
  "person-standing": PersonStanding,
  "heart-handshake": HeartHandshake,
  "hand-helping": HandHelping,
  "graduation-cap": GraduationCap,
  stethoscope: Stethoscope,
  "hard-hat": HardHat,
  "shield-check": ShieldCheck,
  "fingerprint-pattern": FingerprintPattern,
  "key-round": KeyRound,
  "face-slightly-smiling": FaceSlightlySmiling,
  brain: Brain,
  eye: Eye,
  ear: Ear,
  hand: Hand,
  "message-circle": MessageCircle,
  "messages-square": MessagesSquare,
  mail: Mail,
  phone: Phone,
  video: Video,
  mic: Mic,
  radio: Radio,
  satellite: Satellite,
  send: Send,
  inbox: Inbox,
  "at-sign": AtSign,
  bell: Bell,
  rss: Rss,
  "mic-signal": MicSignal,
  speech: Speech,
  headphones: Headphones,
  "volume-2": Volume2,
  languages: Languages,
  webcam: Webcam,
  antenna: Antenna,
  "file-text": FileText,
  files: Files,
  "folder-open": FolderOpen,
  "book-open": BookOpen,
  "notebook-pen": NotebookPen,
  "sticky-note": StickyNote,
  newspaper: Newspaper,
  "clipboard-list": ClipboardList,
  "scroll-text": ScrollText,
  "library-big": LibraryBig,
  bookmark: Bookmark,
  paperclip: Paperclip,
  archive: Archive,
  package: Package,
  image: Image,
  film: Film,
  music: Music,
  map: Map,
  ticket: Ticket,
  "scan-line": ScanLine,
  "code-xml": CodeXml,
  terminal: Terminal,
  bug: Bug,
  cpu: Cpu,
  "circuit-board": CircuitBoard,
  database: Database,
  server: Server,
  cloud: Cloud,
  network: Network,
  wifi: Wifi,
  "ethernet-port": EthernetPort,
  bluetooth: Bluetooth,
  usb: Usb,
  "plug-zap": PlugZap,
  "battery-charging": BatteryCharging,
  monitor: Monitor,
  smartphone: Smartphone,
  tablet: Tablet,
  keyboard: Keyboard,
  mouse: Mouse,
  layers: Layers,
  "list-todo": ListTodo,
  "calendar-days": CalendarDays,
  clock: Clock,
  timer: Timer,
  "alarm-clock": AlarmClock,
  check: Check,
  "square-check-big": SquareCheckBig,
  flag: Flag,
  tag: Tag,
  kanban: Kanban,
  search: Search,
  funnel: Funnel,
  "settings-2": Settings2,
  wrench: Wrench,
  workflow: Workflow,
  "git-branch": GitBranch,
  puzzle: Puzzle,
  link: Link,
  split: Split,
  house: House,
  "building-complex": BuildingComplex,
  store: Store,
  warehouse: Warehouse,
  hospital: Hospital,
  school: School,
  university: University,
  church: Church,
  landmark: Landmark,
  tent: Tent,
  mountain: Mountain,
  trees: Trees,
  globe: Globe,
  compass: Compass,
  navigation: Navigation,
  "map-pin": MapPin,
  route: Route,
  plane: Plane,
  "train-front": TrainFront,
  ship: Ship,
  lightbulb: Lightbulb,
  sparkles: Sparkles,
  star: Star,
  heart: Heart,
  flame: Flame,
  zap: Zap,
  sun: Sun,
  moon: Moon,
  umbrella: Umbrella,
  coffee: Coffee,
  apple: Apple,
  leaf: Leaf,
  "flower-2": Flower2,
  "paw-print": PawPrint,
  gem: Gem,
  gift: Gift,
  "shopping-cart": ShoppingCart,
  "shopping-bag": ShoppingBag,
  camera: Camera,
  palette: Palette,
} satisfies Record<
  IconName,
  React.ComponentType<import("lucide-react").LucideProps>
>;
