// @vegastack icon-alarm-clock@0.7.1 sha256-jwzn/cH+WU7LqrGPEvKROvknLKwUcigHs0APdKVLyKQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/alarm-clock.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { y: 0, x: 0, transition: { duration: 0.2, type: "spring", stiffness: 200, damping: 25 } },
  animate: { y: -1.5, x: [-1, 1, -1, 1, -1, 0], transition: { y: { duration: 0.2, type: "spring", stiffness: 200, damping: 25 }, x: { duration: 0.3, repeat: 1, ease: "linear" } } },
};

const SECONDARY_PATH_VARIANTS: Variants = {
  normal: { y: 0, x: 0, transition: { duration: 0.2, type: "spring", stiffness: 200, damping: 25 } },
  animate: { y: -2.5, x: [-2, 2, -2, 2, -2, 0], transition: { y: { duration: 0.2, type: "spring", stiffness: 200, damping: 25 }, x: { duration: 0.3, repeat: 1, ease: "linear" } } },
};

export type AlarmClockIconHandle = AnimatedIconHandle;

export const AlarmClockIcon = createAnimatedIcon({
  name: "AlarmClockIcon",
  svg: { style: { overflow: "visible" } },
  elements: [
    { tag: "motion.path", d: "M18 20.5L19.5 22", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M6 20.5L4.5 22", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M21 13C21 17.968 16.968 22 12 22C7.032 22 3 17.968 3 13C3 8.032 7.032 4 12 4C16.968 4 21 8.032 21 13Z", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M15.339 15.862L12.549 14.197C12.063 13.909 11.667 13.216 11.667 12.649V8.95898", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M18 2L21.747 5.31064", variants: SECONDARY_PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M6 2L2.25304 5.31064", variants: SECONDARY_PATH_VARIANTS, initial: "normal" },
  ],
});
