// @vegastack icon-align-center@0.17.1 sha256-548e24W8r6fRk3MwBhTi09Z+jLyFH0/IYF3xmJfpbFU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/align-center.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type AlignCenterIconHandle = AnimatedIconHandle;

export const AlignCenterIcon = createAnimatedIcon({
  name: "AlignCenterIcon",
  elements: [
    { tag: "motion.path", d: "M17 12H7", variants: { normal: { translateX: 0 }, animate: { translateX: [0, 3, -3, 2, -2, 0], transition: { ease: "linear", translateX: { duration: 1 } } } } },
    "M19 18H5",
    "M21 6H3",
  ],
});
