// @vegastack icon-align-right@0.7.5 sha256-68PePMjxVUvAlIFCckL7wDOtrprpm5O9wJFMYemKvMM=

// Mirrored from lucide-animated (https://lucide-animated.com/r/align-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 150, damping: 15, mass: 0.3 };

export type AlignRightIconHandle = AnimatedIconHandle;

export const AlignRightIcon = createAnimatedIcon({
  name: "AlignRightIcon",
  elements: [
    { tag: "motion.line", x1: "3", x2: "21", y1: "6", y2: "6", variants: { normal: { x1: 3 }, animate: { x1: 3 } }, transition: DEFAULT_TRANSITION },
    { tag: "motion.line", x1: "9", x2: "21", y1: "12", y2: "12", variants: { normal: { x1: 9 }, animate: { x1: 5 } }, transition: DEFAULT_TRANSITION },
    { tag: "motion.line", x1: "7", x2: "21", y1: "18", y2: "18", variants: { normal: { x1: 7 }, animate: { x1: 12 } }, transition: DEFAULT_TRANSITION },
  ],
});
