// @vegastack icon-align-left@0.8.0 sha256-aglLsFvEYFkAQmYf080x/2hMeXm4MCSivgx4tniwKLE=

// Mirrored from lucide-animated (https://lucide-animated.com/r/align-left.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 150, damping: 15, mass: 0.3 };

export type AlignLeftIconHandle = AnimatedIconHandle;

export const AlignLeftIcon = createAnimatedIcon({
  name: "AlignLeftIcon",
  elements: [
    { tag: "motion.line", x1: "3", x2: "21", y1: "6", y2: "6", variants: { normal: { x2: 21 }, animate: { x2: 21 } }, transition: DEFAULT_TRANSITION },
    { tag: "motion.line", x1: "3", x2: "15", y1: "12", y2: "12", variants: { normal: { x2: 15 }, animate: { x2: 19 } }, transition: DEFAULT_TRANSITION },
    { tag: "motion.line", x1: "3", x2: "17", y1: "18", y2: "18", variants: { normal: { x2: 17 }, animate: { x2: 12 } }, transition: DEFAULT_TRANSITION },
  ],
});
