// @vegastack icon-arrow-big-up-dash@0.23.33 sha256-ggRDwC9tuFK8ShJaN9v/1ur3KDmBZJFU1vbY/rnLke8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/arrow-big-up-dash.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DASH_VARIANTS: Variants = { normal: { translateY: 0 }, animate: { translateY: [0, -1, 0], transition: { duration: 0.4 } } };

const ARROW_VARIANTS: Variants = { normal: { translateY: 0 }, animate: { translateY: [0, -3, 0], transition: { duration: 0.4 } } };

export type ArrowBigUpDashIconHandle = AnimatedIconHandle;

export const ArrowBigUpDashIcon = createAnimatedIcon({
  name: "ArrowBigUpDashIcon",
  elements: [
    { tag: "motion.path", d: "M9 19h6", variants: DASH_VARIANTS },
    { tag: "motion.path", d: "M9 15v-3H5l7-7 7 7h-4v3H9z", variants: ARROW_VARIANTS },
  ],
});
