// @vegastack icon-arrow-big-left-dash@0.8.0 sha256-sbw8pYrAUBJVX7n0Y9UDEIzfxALqtjF9+ilLgFevyY0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/arrow-big-left-dash.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DASH_VARIANTS: Variants = { normal: { translateX: 0 }, animate: { translateX: [0, -1, 0], transition: { duration: 0.4 } } };

const ARROW_VARIANTS: Variants = { normal: { translateX: 0 }, animate: { translateX: [0, -3, 0], transition: { duration: 0.4 } } };

export type ArrowBigLeftDashIconHandle = AnimatedIconHandle;

export const ArrowBigLeftDashIcon = createAnimatedIcon({
  name: "ArrowBigLeftDashIcon",
  elements: [
    { tag: "motion.path", d: "M19 15V9", variants: DASH_VARIANTS },
    { tag: "motion.path", d: "M15 15h-3v4l-7-7 7-7v4h3v6z", variants: ARROW_VARIANTS },
  ],
});
