// @vegastack icon-arrow-big-up@0.23.16 sha256-v3L6Fz/9S+6qk7gWfVJp9ogVjAH4FG6z0AK7oH9h0Sc=

// Mirrored from lucide-animated (https://lucide-animated.com/r/arrow-big-up.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { d: "M9 18v-6H5l7-7 7 7h-4v6H9z", translateY: 0 }, animate: { d: "M9 18v-6H5l7-7 7 7h-4v6H9z", translateY: [0, -3, 0], transition: { duration: 0.4 } } };

export type ArrowBigUpIconHandle = AnimatedIconHandle;

export const ArrowBigUpIcon = createAnimatedIcon({ name: "ArrowBigUpIcon", elements: [{ tag: "motion.path", d: "M9 18v-6H5l7-7 7 7h-4v6H9z", variants: PATH_VARIANTS }] });
