// @vegastack icon-arrow-big-right@0.7.4 sha256-LZvHIY/AfIO2y9oxh+yYzO92vgztbT3x1N0LwTHTKzg=

// Mirrored from lucide-animated (https://lucide-animated.com/r/arrow-big-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { d: "M6 9h6V5l7 7-7 7v-4H6V9z", translateX: 0 }, animate: { d: "M6 9h6V5l7 7-7 7v-4H6V9z", translateX: [0, 3, 0], transition: { duration: 0.4 } } };

export type ArrowBigRightIconHandle = AnimatedIconHandle;

export const ArrowBigRightIcon = createAnimatedIcon({ name: "ArrowBigRightIcon", elements: [{ tag: "motion.path", d: "M6 9h6V5l7 7-7 7v-4H6V9z", variants: PATH_VARIANTS }] });
