// @vegastack icon-attach-file@0.7.1 sha256-tmBNUqLqoQS7RcElleUtDIV39b7KyMvkHzsZKid0/zU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/attach-file.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1, pathOffset: 0 },
  animate: { opacity: [0, 1], pathLength: [0, 1], transition: { delay: 0.1, duration: 0.4, opacity: { duration: 0.1, delay: 0.1 } } },
};

export type AttachFileIconHandle = AnimatedIconHandle;

export const AttachFileIcon = createAnimatedIcon({
  name: "AttachFileIcon",
  elements: [
    {
      tag: "motion.path",
      d: "M6 7.90909V16C6 19.3137 8.68629 22 12 22V22C15.3137 22 18 19.3137 18 16V6C18 3.79086 16.2091 2 14 2V2C11.7909 2 10 3.79086 10 6V15.1818C10 16.2864 10.8954 17.1818 12 17.1818V17.1818C13.1046 17.1818 14 16.2864 14 15.1818V8",
      variants: PATH_VARIANTS,
      initial: "normal",
    },
  ],
});
