// @vegastack icon-axe@0.7.3 sha256-yY8b9F//WwsEMvFa0DyypwKxGwCWnrzq+lrxz8PyKs0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/axe.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const AXE_VARIANTS: Variants = {
  normal: { rotate: 0, transition: { duration: 0.3, ease: "easeOut" } },
  animate: { rotate: [0, -20, 25, 0], transition: { duration: 0.8, times: [0, 0.6, 0.8, 1], ease: ["easeInOut", "easeOut", "easeOut"] } },
};

export type AxeIconHandle = AnimatedIconHandle;

export const AxeIcon = createAnimatedIcon({
  name: "AxeIcon",
  svg: { tag: "motion.svg", variants: AXE_VARIANTS, initial: "normal", style: { transformOrigin: "0% 100%", transformBox: "fill-box" } },
  elements: [
    "m14 12-8.381 8.38a1 1 0 0 1-3.001-3L11 9",
    "M15 15.5a.5.5 0 0 0 .5.5A6.5 6.5 0 0 0 22 9.5a.5.5 0 0 0-.5-.5h-1.672a2 2 0 0 1-1.414-.586l-5.062-5.062a1.205 1.205 0 0 0-1.704 0L9.352 5.648a1.205 1.205 0 0 0 0 1.704l5.062 5.062A2 2 0 0 1 15 13.828z",
  ],
});
