// @vegastack icon-badge-percent@0.8.2 sha256-19gRUiW4Pfv+Lrjz9kx0mVKMawRyBh29VHTXGKBMq4U=

// Mirrored from lucide-animated (https://lucide-animated.com/r/badge-percent.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { rotate: 0, transition: { type: "spring", stiffness: 60, damping: 10, duration: 0.5 } },
  animate: { rotate: 180, transition: { delay: 0.1, type: "spring", stiffness: 80, damping: 13 } },
};

export type BadgePercentIconHandle = AnimatedIconHandle;

export const BadgePercentIcon = createAnimatedIcon({
  name: "BadgePercentIcon",
  elements: [
    {
      tag: "motion.path",
      d: "M3.85 8.62a4 4 0 0 1 4.78-4.77 4 4 0 0 1 6.74 0 4 4 0 0 1 4.78 4.78 4 4 0 0 1 0 6.74 4 4 0 0 1-4.77 4.78 4 4 0 0 1-6.75 0 4 4 0 0 1-4.78-4.77 4 4 0 0 1 0-6.76Z",
      variants: PATH_VARIANTS,
    },
    "m15 9-6 6",
    "M9 9h.01",
    "M15 15h.01",
  ],
});
