// @vegastack icon-bluetooth-searching@0.7.0 sha256-tFYh092SKFuPLonizF+tdtkjJ1jmU19YX5BycOOXnHA=

// Mirrored from lucide-animated (https://lucide-animated.com/r/bluetooth-searching.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { scale: 1, transition: { repeat: 0 } }, animate: { scale: [0, 1, 0.8] } };

const SECOND_VARIANTS: Variants = { normal: { opacity: 1 }, animate: { opacity: [1, 0.8, 1], transition: { repeat: 1 } } };

export type BluetoothSearchingIconHandle = AnimatedIconHandle;

export const BluetoothSearchingIcon = createAnimatedIcon({
  name: "BluetoothSearchingIcon",
  elements: [
    { tag: "motion.path", d: "m7 7 10 10-5 5V2l5 5L7 17", variants: SECOND_VARIANTS },
    { tag: "motion.path", d: "M20.83 14.83a4 4 0 0 0 0-5.66", variants: PATH_VARIANTS, transition: { duration: 0.6, delay: 0.2, repeat: 1 } },
    { tag: "motion.path", d: "M18 12h.01", variants: PATH_VARIANTS, transition: { duration: 0.6, repeat: 1 } },
  ],
});
