// @vegastack icon-bold@0.12.1 sha256-eAu/Ofj9YYrXV2PP6ezsuVvs25gW0o3Y4xcCH2vIokI=

// Mirrored from lucide-animated (https://lucide-animated.com/r/bold.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { strokeWidth: 2 }, animate: { strokeWidth: 3.5 } };

export type BoldIconHandle = AnimatedIconHandle;

export const BoldIcon = createAnimatedIcon({
  name: "BoldIcon",
  elements: [{ tag: "motion.path", d: "M6 12h9a4 4 0 0 1 0 8H7a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h7a4 4 0 0 1 0 8", variants: PATH_VARIANTS, transition: { duration: 0.6 } }],
});
