// @vegastack icon-bone@0.8.1 sha256-ONp1Uyd4inBWQExJDzdTqpy8K4GbuY07aDpCdno2ap0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/bone.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: [0, -8, 8, -6, 0], transition: { ease: "circIn", rotate: { duration: 0.5 } } } };

export type BoneIconHandle = AnimatedIconHandle;

export const BoneIcon = createAnimatedIcon({
  name: "BoneIcon",
  elements: [
    {
      tag: "motion.path",
      d: "M17 10c.7-.7 1.69 0 2.5 0a2.5 2.5 0 1 0 0-5 .5.5 0 0 1-.5-.5 2.5 2.5 0 1 0-5 0c0 .81.7 1.8 0 2.5l-7 7c-.7.7-1.69 0-2.5 0a2.5 2.5 0 0 0 0 5c.28 0 .5.22.5.5a2.5 2.5 0 1 0 5 0c0-.81-.7-1.8 0-2.5Z",
      variants: VARIANTS,
    },
  ],
});
