// @vegastack icon-bookmark-check@0.6.0 sha256-83LJ9jfQmKtp3R6TPLIUJuhjZNRC6Eh18cILfswKE3Y=

// Mirrored from lucide-animated (https://lucide-animated.com/r/bookmark-check.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const BOOKMARK_VARIANTS: Variants = { normal: { scaleY: 1, scaleX: 1 }, animate: { scaleY: [1, 1.3, 0.9, 1.05, 1], scaleX: [1, 0.9, 1.1, 0.95, 1], transition: { duration: 0.6, ease: "easeOut" } } };

const CHECK_VARIANTS: Variants = { normal: { opacity: 1, strokeDashoffset: 0 }, animate: { strokeDashoffset: [1, 0], opacity: [0, 1], transition: { duration: 0.3, ease: "easeOut" } } };

export type BookmarkCheckIconHandle = AnimatedIconHandle;

export const BookmarkCheckIcon = createAnimatedIcon({
  name: "BookmarkCheckIcon",
  elements: [
    { tag: "motion.path", d: "m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2Z", variants: BOOKMARK_VARIANTS, style: { originX: 0.5, originY: 0.5 } },
    { tag: "motion.path", d: "m9 10 2 2 4-4", pathLength: "1", strokeDasharray: "1 1", variants: CHECK_VARIANTS, initial: "normal" },
  ],
});
