// @vegastack icon-box@0.8.0 sha256-E+P/M+xDkq0sT9e9J+9VpK5EmxPvHfk8JIEFmQobesQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/box.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, transition: { duration: 0.3, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], transition: { duration: 0.4, opacity: { duration: 0.1 } } },
};

export type BoxIconHandle = AnimatedIconHandle;

export const BoxIcon = createAnimatedIcon({
  name: "BoxIcon",
  elements: [
    { tag: "motion.path", d: "M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "m3.3 7 8.7 5 8.7-5", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M12 22V12", variants: PATH_VARIANTS, initial: "normal" },
  ],
});
