// @vegastack icon-calendar-check-2@0.8.1 sha256-xy9xo3RCN694XwQFKz5hc694zpQgtrwHDHfgSe3UtWc=

// Mirrored from lucide-animated (https://lucide-animated.com/r/calendar-check-2.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CHECK_VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1, transition: { duration: 0.3 } },
  animate: { pathLength: [0, 1], opacity: [0, 1], transition: { pathLength: { duration: 0.4, ease: "easeInOut" }, opacity: { duration: 0.4, ease: "easeInOut" } } },
};

export type CalendarCheck2IconHandle = AnimatedIconHandle;

export const CalendarCheck2Icon = createAnimatedIcon({
  name: "CalendarCheck2Icon",
  elements: [
    "M8 2v4",
    "M16 2v4",
    "M21 14V6a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h8",
    "M3 10h18",
    { tag: "motion.path", d: "m16 20 2 2 4-4", variants: CHECK_VARIANTS, initial: "normal", style: { transformOrigin: "center" } },
  ],
});
