// @vegastack icon-chart-scatter@0.6.0 sha256-Ch5Ub2cUfIXOe4KBEyr11NbX8+xhsgX0VcJfu02FGSk=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chart-scatter.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DOT_VARIANTS: Variants = {
  visible: (i: number) => ({ opacity: 1, transition: { delay: i * 0.15, duration: 0.3 } }),
  hidden: { opacity: 0, transition: { duration: 0.2 } },
  default: { opacity: 1 },
};

export type ChartScatterIconHandle = AnimatedIconHandle;

export const ChartScatterIcon = createAnimatedIcon({
  name: "ChartScatterIcon",
  svg: { tag: "motion.svg", initial: "default" },
  elements: [
    { tag: "motion.circle", cx: "7.5", cy: "7.5", fill: "currentColor", r: ".5", variants: DOT_VARIANTS, custom: 0, inherit: true },
    { tag: "motion.circle", cx: "18.5", cy: "5.5", fill: "currentColor", r: ".5", variants: DOT_VARIANTS, custom: 1, inherit: true },
    { tag: "motion.circle", cx: "11.5", cy: "11.5", fill: "currentColor", r: ".5", variants: DOT_VARIANTS, custom: 2, inherit: true },
    { tag: "motion.circle", cx: "7.5", cy: "16.5", fill: "currentColor", r: ".5", variants: DOT_VARIANTS, custom: 3, inherit: true },
    { tag: "motion.circle", cx: "17.5", cy: "14.5", fill: "currentColor", r: ".5", variants: DOT_VARIANTS, custom: 4, inherit: true },
    { tag: "path", d: "M3 3v16a2 2 0 0 0 2 2h16", strokeWidth: "2" },
  ],
  start: async ({ control, run }) => {
    await run(control(), "hidden");
    await run(control(), "visible");
  },
  stop: ({ control, reset }) => {
    reset(control(), "default");
  },
});
