// @vegastack icon-chess-knight@0.8.1 sha256-4Jk9WJ1mYWKm0HagO29adq1pEBDptAfA6AUf9of6pwU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chess-knight.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const KNIGHT_VARIANTS: Variants = {
  normal: { rotate: 0, y: 0, transition: { type: "spring", stiffness: 220, damping: 12 } },
  animate: { rotate: [0, 12, 38, 42, 38, 10, -5, 0], y: [0, -2, -9, -12, -9, -2, 1, 0], transition: { duration: 0.9, times: [0, 0.1, 0.3, 0.45, 0.6, 0.78, 0.9, 1], ease: "easeInOut" } },
};

export type ChessKnightIconHandle = AnimatedIconHandle;

export const ChessKnightIcon = createAnimatedIcon({
  name: "ChessKnightIcon",
  svg: { style: { overflow: "visible" } },
  elements: [
    {
      tag: "motion.g",
      variants: KNIGHT_VARIANTS,
      initial: "normal",
      style: { transformBox: "view-box", transformOrigin: "12px 22px" },
      children: [
        "M5 20a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v1a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1z",
        "M16.5 18c1-2 2.5-5 2.5-9a7 7 0 0 0-7-7H6.635a1 1 0 0 0-.768 1.64L7 5l-2.32 5.802a2 2 0 0 0 .95 2.526l2.87 1.456",
        "m15 5 1.425-1.425",
        "m17 8 1.53-1.53",
        "M9.713 12.185 7 18",
      ],
    },
  ],
});
