// @vegastack icon-chevrons-left-right@0.23.9 sha256-qr0JP8ffAeO8y5h6lCS+bFJnch91K7lY4AH1cNA3sYo=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chevrons-left-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 250, damping: 25 };

export type ChevronsLeftRightIconHandle = AnimatedIconHandle;

export const ChevronsLeftRightIcon = createAnimatedIcon({
  name: "ChevronsLeftRightIcon",
  elements: [
    { tag: "motion.path", d: "m9 7-5 5 5 5", variants: { normal: { translateX: "0%" }, animate: { translateX: "-2px" } }, initial: "normal", transition: DEFAULT_TRANSITION },
    { tag: "motion.path", d: "m15 7 5 5-5 5", variants: { normal: { translateX: "0%" }, animate: { translateX: "2px" } }, initial: "normal", transition: DEFAULT_TRANSITION },
  ],
});
