// @vegastack icon-chevron-right@0.23.57 sha256-h2TRGQ4ix5/4iOP0IjuECVz+lOEr/HkyiGQ5K3Gsx4w=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chevron-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type ChevronRightIconHandle = AnimatedIconHandle;

export const ChevronRightIcon = createAnimatedIcon({
  name: "ChevronRightIcon",
  elements: [{ tag: "motion.path", d: "m9 18 6-6-6-6", variants: { normal: { x: 0 }, animate: { x: [0, 2, 0] } }, transition: DEFAULT_TRANSITION }],
});
