// @vegastack icon-chevron-up@0.11.0 sha256-O6ulgj1Nq4k4DV5ffANppV/f1iCvSNomQTPApSFb5M4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chevron-up.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type ChevronUpIconHandle = AnimatedIconHandle;

export const ChevronUpIcon = createAnimatedIcon({
  name: "ChevronUpIcon",
  elements: [{ tag: "motion.path", d: "m18 15-6-6-6 6", variants: { normal: { y: 0 }, animate: { y: [0, -2, 0] } }, transition: DEFAULT_TRANSITION }],
});
