// @vegastack icon-circle-chevron-right@0.7.1 sha256-SzI1oO7q/Y2u5nACgz64BdWQU0yzDQwHE9K6Xgf0svo=

// Mirrored from lucide-animated (https://lucide-animated.com/r/circle-chevron-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type CircleChevronRightIconHandle = AnimatedIconHandle;

export const CircleChevronRightIcon = createAnimatedIcon({
  name: "CircleChevronRightIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    { tag: "motion.path", d: "m10 8 4 4-4 4", variants: { normal: { x: 0 }, animate: { x: [0, 2, 0] } }, transition: DEFAULT_TRANSITION },
  ],
});
