// @vegastack icon-circle-check@0.7.5 sha256-9cJiXVreVNIcz9UT152GiIb90bdCu4Zm3TopTGiBkmU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/circle-check.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, transition: { duration: 0.3, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], transition: { duration: 0.4, opacity: { duration: 0.1 } } },
};

export type CircleCheckIconHandle = AnimatedIconHandle;

export const CircleCheckIcon = createAnimatedIcon({
  name: "CircleCheckIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    { tag: "motion.path", d: "m9 12 2 2 4-4", variants: PATH_VARIANTS, initial: "normal" },
  ],
});
