// @vegastack icon-circle-chevron-left@0.6.0 sha256-R5DQbGhvMvKHTn8owYBrSXNI7EnvQpvobjzmhlWxkp0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/circle-chevron-left.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type CircleChevronLeftIconHandle = AnimatedIconHandle;

export const CircleChevronLeftIcon = createAnimatedIcon({
  name: "CircleChevronLeftIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    { tag: "motion.path", d: "m14 16-4-4 4-4", variants: { normal: { x: 0 }, animate: { x: [0, -2, 0] } }, transition: DEFAULT_TRANSITION },
  ],
});
