// @vegastack icon-cloud-sun@0.6.0 sha256-C3WPGiY7mnhKaOKVrW4U5rZFwuGMtrTh1ngtQj3MV0U=

// Mirrored from lucide-animated (https://lucide-animated.com/r/cloud-sun.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CLOUD_VARIANTS: Variants = { normal: { x: 0, y: 0 }, animate: { x: [-1, 1, -1, 1, 0], y: [-1, 1, -1, 1, 0], transition: { duration: 1, ease: "easeInOut" } } };

const SUN_VARIANTS: Variants = { normal: { opacity: 1 }, animate: (i: number) => ({ opacity: [0, 1], transition: { delay: i * 0.1, duration: 0.3 } }) };

export type CloudSunIconHandle = AnimatedIconHandle;

export const CloudSunIcon = createAnimatedIcon({
  name: "CloudSunIcon",
  svg: { style: { overflow: "visible" } },
  elements: [
    { tag: "motion.g", variants: CLOUD_VARIANTS, initial: "normal", group: "cloud", children: ["M13 22H7a5 5 0 1 1 4.9-6H13a3 3 0 0 1 0 6Z"] },
    { tag: "motion.path", d: "M12 2v2", variants: SUN_VARIANTS, initial: "normal", custom: 1, group: "sun" },
    { tag: "motion.path", d: "m4.93 4.93 1.41 1.41", variants: SUN_VARIANTS, initial: "normal", custom: 2, group: "sun" },
    { tag: "motion.path", d: "M20 12h2", variants: SUN_VARIANTS, initial: "normal", custom: 3, group: "sun" },
    { tag: "motion.path", d: "m19.07 4.93-1.41 1.41", variants: SUN_VARIANTS, initial: "normal", custom: 4, group: "sun" },
    { tag: "motion.path", d: "M15.947 12.65a4 4 0 0 0-5.925-4.128", variants: SUN_VARIANTS, initial: "normal", custom: 5, group: "sun" },
  ],
  groups: ["cloud", "sun"],
  start: ({ controls, run }) => {
    run(controls.cloud, "animate");
    run(controls.sun, "animate");
  },
  stop: ({ controls, reset }) => {
    reset(controls.cloud, "normal");
    reset(controls.sun, "normal");
  },
});
