// @vegastack icon-compass@0.23.39 sha256-q3yAednaLdN7Zg2q+czzdhQ5Hh7ZpFH7uBURNtuyvQ8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/compass.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type CompassIconHandle = AnimatedIconHandle;

export const CompassIcon = createAnimatedIcon({
  name: "CompassIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    {
      tag: "motion.polygon",
      points: "16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76",
      variants: { normal: { rotate: 0 }, animate: { rotate: 360 } },
      transition: { type: "spring", stiffness: 120, damping: 15 },
    },
  ],
});
