// @vegastack icon-corner-left-up@0.11.3 sha256-2HH+A91LYJwiK61wy3SG59wDAXP7eqCoZ/+pPlGO3V8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/corner-left-up.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const STRETCH_VARIANTS: Variants = { normal: { scaleY: 1, y: 0, opacity: 1 }, animate: { scaleY: [1, 1.15, 1], y: [0, -2, 0], transition: { duration: 0.45, ease: "easeInOut" } } };

export type CornerLeftUpIconHandle = AnimatedIconHandle;

export const CornerLeftUpIcon = createAnimatedIcon({
  name: "CornerLeftUpIcon",
  svg: { tag: "motion.svg", variants: STRETCH_VARIANTS, initial: "normal" },
  elements: ["M14 9 9 4 4 9", "M20 20h-7a4 4 0 0 1-4-4V4"],
});
