// @vegastack icon-corner-up-left@0.7.5 sha256-sWECIC4reTmF7SGg048oFtpV6/uw4LbWIj41BPoOuS0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/corner-up-left.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const STRETCH_VARIANTS: Variants = { normal: { scaleX: 1, x: 0, opacity: 1 }, animate: { scaleX: [1, 1.15, 1], x: [0, -2, 0], transition: { duration: 0.45, ease: "easeInOut" } } };

export type CornerUpLeftIconHandle = AnimatedIconHandle;

export const CornerUpLeftIcon = createAnimatedIcon({
  name: "CornerUpLeftIcon",
  svg: { tag: "motion.svg", variants: STRETCH_VARIANTS, initial: "normal" },
  elements: ["M20 20v-7a4 4 0 0 0-4-4H4", "M9 14 4 9l5-5"],
});
