// @vegastack icon-dribbble@0.6.0 sha256-XDs2Qqq5Ox3jS0f+XmIRlt5XNIh2jQ5yFWqLDqsZXIk=

// Mirrored from lucide-animated (https://lucide-animated.com/r/dribbble.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CIRCLE_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, pathOffset: 0, transition: { duration: 0.4, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], pathOffset: [1, 0], transition: { duration: 0.6, ease: "linear", opacity: { duration: 0.1 } } },
};

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, pathOffset: 0, transition: { duration: 0.4, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], pathOffset: [1, 0], transition: { duration: 0.6, ease: "linear", opacity: { duration: 0.1 } } },
};

export type DribbbleIconHandle = AnimatedIconHandle;

export const DribbbleIcon = createAnimatedIcon({
  name: "DribbbleIcon",
  elements: [
    { tag: "motion.circle", cx: "12", cy: "12", r: "10", variants: CIRCLE_VARIANTS, initial: "normal", group: "circle" },
    { tag: "motion.path", d: "M19.13 5.09C15.22 9.14 10 10.44 2.25 10.94", variants: PATH_VARIANTS, initial: "normal", group: "path1" },
    { tag: "motion.path", d: "M21.75 12.84c-6.62-1.41-12.14 1-16.38 6.32", variants: PATH_VARIANTS, initial: "normal", group: "path2" },
    { tag: "motion.path", d: "M8.56 2.75c4.37 6 6 9.42 8 17.72", variants: PATH_VARIANTS, initial: "normal", group: "path3" },
  ],
  groups: ["circle", "path1", "path2", "path3"],
  start: ({ controls, run }) => {
    run(controls.circle, "animate");
    run(controls.path1, "animate");
    run(controls.path2, "animate");
    run(controls.path3, "animate");
  },
  stop: ({ controls, reset }) => {
    reset(controls.circle, "normal");
    reset(controls.path1, "normal");
    reset(controls.path2, "normal");
    reset(controls.path3, "normal");
  },
});
