// @vegastack icon-eye@0.7.0 sha256-Mn+Lkn1hY9g0RGywae0yULVF+CZWDuUn8ZO66RD9QoU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/eye.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type EyeIconHandle = AnimatedIconHandle;

export const EyeIcon = createAnimatedIcon({
  name: "EyeIcon",
  elements: [
    {
      tag: "motion.path",
      d: "M2.062 12.348a1 1 0 0 1 0-.696 10.75 10.75 0 0 1 19.876 0 1 1 0 0 1 0 .696 10.75 10.75 0 0 1-19.876 0",
      variants: { normal: { scaleY: 1, opacity: 1 }, animate: { scaleY: [1, 0.1, 1], opacity: [1, 0.3, 1] } },
      transition: { duration: 0.4, ease: "easeInOut" },
      style: { originY: "50%" },
    },
    {
      tag: "motion.circle",
      cx: "12",
      cy: "12",
      r: "3",
      variants: { normal: { scale: 1, opacity: 1 }, animate: { scale: [1, 0.3, 1], opacity: [1, 0.3, 1] } },
      transition: { duration: 0.4, ease: "easeInOut" },
    },
  ],
});
