// @vegastack icon-feather@0.12.1 sha256-u6TNB1i9xnitTEz72g8OZzBpbW896NTdEL3lWT8Q3Mc=

// Mirrored from lucide-animated (https://lucide-animated.com/r/feather.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const FEATHER_VARIANTS: Variants = {
  normal: { rotate: 0, y: 0, x: 0 },
  animate: { rotate: [0, -8, 4, -3, 0], y: [0, -4, -2, -1, 0], x: [0, 2, -2, 1, 0], transition: { duration: 1.6, ease: "easeInOut" } },
};

export type FeatherIconHandle = AnimatedIconHandle;

export const FeatherIcon = createAnimatedIcon({
  name: "FeatherIcon",
  svg: { tag: "motion.svg", variants: FEATHER_VARIANTS },
  elements: ["M12.67 19a2 2 0 0 0 1.416-.588l6.154-6.172a6 6 0 0 0-8.49-8.49L5.586 9.914A2 2 0 0 0 5 11.328V18a1 1 0 0 0 1 1z", "M16 8 2 22", "M17.5 15H9"],
});
