// @vegastack icon-file-text@0.6.0 sha256-TrVBBLSz1wKwIatn3rIGDhbbu5wL1RKDqIm0NZhfNTI=

// Mirrored from lucide-animated (https://lucide-animated.com/r/file-text.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type FileTextIconHandle = AnimatedIconHandle;

export const FileTextIcon = createAnimatedIcon({
  name: "FileTextIcon",
  svg: { tag: "motion.svg", variants: { normal: { scale: 1 }, animate: { scale: 1.05, transition: { duration: 0.3, ease: "easeOut" } } }, initial: "normal" },
  elements: [
    "M15 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V7Z",
    "M14 2v4a2 2 0 0 0 2 2h4",
    {
      tag: "motion.path",
      d: "M10 9H8",
      stroke: "currentColor",
      strokeWidth: "2",
      variants: { normal: { pathLength: 1, x1: 8, x2: 10 }, animate: { pathLength: [1, 0, 1], x1: [8, 10, 8], x2: [10, 10, 10], transition: { duration: 0.7, delay: 0.3 } } },
      inherit: true,
    },
    {
      tag: "motion.path",
      d: "M16 13H8",
      stroke: "currentColor",
      strokeWidth: "2",
      variants: { normal: { pathLength: 1, x1: 8, x2: 16 }, animate: { pathLength: [1, 0, 1], x1: [8, 16, 8], x2: [16, 16, 16], transition: { duration: 0.7, delay: 0.5 } } },
      inherit: true,
    },
    {
      tag: "motion.path",
      d: "M16 17H8",
      stroke: "currentColor",
      strokeWidth: "2",
      variants: { normal: { pathLength: 1, x1: 8, x2: 16 }, animate: { pathLength: [1, 0, 1], x1: [8, 16, 8], x2: [16, 16, 16], transition: { duration: 0.7, delay: 0.7 } } },
      inherit: true,
    },
  ],
});
