// @vegastack icon-heart-pulse@0.3.0 sha256-WeNsgTUtf/KszqXMjd/Br3n0f8an2Jk6biI0TIRPxo4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/heart-pulse.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface HeartPulseIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface HeartPulseIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<HeartPulseIconHandle>;
}

const HEART_DRAW_VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1 },
  hidden: { pathLength: 0, opacity: 0 },
  draw: { pathLength: [0, 1], opacity: [0, 1] },
};

const HEART_PULSE_VARIANTS: Variants = {
  normal: { scale: 1 },
  pulse: { scale: [1, 1.08, 1] },
};

const LINE_VARIANTS: Variants = {
  normal: { pathLength: 1, pathOffset: 0, opacity: 1 },
  animate: { pathLength: [0, 1], pathOffset: [1, 0], opacity: [0, 1] },
};

const HeartPulseIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: HeartPulseIconProps) => {
  const heartDrawControls = useAnimation();
  const heartPulseControls = useAnimation();
  const lineControls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof heartDrawControls,
      definition: Parameters<typeof heartDrawControls.start>[0],
      transitionOverride?: Parameters<typeof heartDrawControls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof heartDrawControls,
      definition: Parameters<typeof heartDrawControls.start>[0],
      transitionOverride?: Parameters<typeof heartDrawControls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = useCallback(async () => {
    runAnimation(heartDrawControls, "hidden", { duration: 0 });
    await runAnimation(lineControls, "animate", {
      duration: 0.6,
      ease: "linear",
      opacity: { duration: 0.1 },
    });
    await runAnimation(heartDrawControls, "draw", {
      duration: 0.5,
      ease: "easeOut",
      opacity: { duration: 0.1 },
    });
    runAnimation(heartPulseControls, "pulse", {
      duration: 0.9,
      repeat: 1,
      ease: "easeInOut",
    });
  }, [heartDrawControls, heartPulseControls, lineControls]);

  const stopAnimation = useCallback(() => {
    resetAnimation(heartDrawControls, "normal", { duration: 0.3 });
    resetAnimation(heartPulseControls, "normal", { duration: 0.3 });
    resetAnimation(lineControls, "normal", { duration: 0.3 });
  }, [heartDrawControls, heartPulseControls, lineControls]);

  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <svg
        fill="none"
        height={size}
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <motion.g
          animate={heartPulseControls}
          style={{ originX: "12px", originY: "12px" }}
          variants={HEART_PULSE_VARIANTS}
        >
          <motion.path
            animate={heartDrawControls}
            d="M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5"
            variants={HEART_DRAW_VARIANTS}
          />
        </motion.g>
        <motion.path
          animate={lineControls}
          d="M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27"
          variants={LINE_VARIANTS}
        />
      </svg>
    </div>
  );
};

HeartPulseIcon.displayName = "HeartPulseIcon";

export { HeartPulseIcon };
