// @vegastack icon-heart@0.8.0 sha256-eeDSJ+AtPm1EEEnmIlh9cTLegCvu0tGEd8ePn2OFrAo=

// Mirrored from lucide-animated (https://lucide-animated.com/r/heart.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type HeartIconHandle = AnimatedIconHandle;

export const HeartIcon = createAnimatedIcon({
  name: "HeartIcon",
  svg: { tag: "motion.svg", variants: { normal: { scale: 1 }, animate: { scale: [1, 1.08, 1] } }, transition: { duration: 0.45, repeat: 2 } },
  elements: ["M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z"],
});
