// @vegastack icon-key@0.7.3 sha256-d7vHdsSIQ3nsaTzNOLYzd2b7tTWqn/hooVF+bMXWvtg=

// Mirrored from lucide-animated (https://lucide-animated.com/r/key.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type KeyIconHandle = AnimatedIconHandle;

export const KeyIcon = createAnimatedIcon({
  name: "KeyIcon",
  svg: {
    tag: "motion.svg",
    variants: {
      normal: { rotate: 0, transition: { type: "spring", stiffness: 120, damping: 14, duration: 0.8 } },
      animate: { rotate: [-3, -33, -25, -28], transition: { duration: 0.6, times: [0, 0.6, 0.8, 1], ease: "easeInOut" } },
    },
    initial: "normal",
    style: { originX: 0.3, originY: 0.7 },
  },
  elements: ["m15.5 7.5 2.3 2.3a1 1 0 0 0 1.4 0l2.1-2.1a1 1 0 0 0 0-1.4L19 4", "m21 2-9.6 9.6", { tag: "circle", cx: "7.5", cy: "15.5", r: "5.5" }],
});
