// @vegastack icon-login@0.6.0 sha256-Df3G7u0jgxRfcmo1hUMhZFa1EnMJaSgbcVtsmFSPWr8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/login.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { animate: { x: -2, translateX: [0, 3, 0], transition: { duration: 0.4 } } };

export type LogInIconHandle = AnimatedIconHandle;

export const LogInIcon = createAnimatedIcon({
  name: "LogInIcon",
  elements: [
    "M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4",
    { tag: "motion.polyline", points: "10 17 15 12 10 7", variants: PATH_VARIANTS },
    { tag: "motion.line", x1: "3", x2: "15", y1: "12", y2: "12", variants: PATH_VARIANTS },
  ],
});
