// @vegastack icon-logout@0.8.1 sha256-2KJ+4biCd7jWJE4CiAknEyyxLLSQsYJeY3WEdXZLtD4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/logout.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { animate: { x: 2, translateX: [0, -3, 0], transition: { duration: 0.4 } } };

export type LogoutIconHandle = AnimatedIconHandle;

export const LogoutIcon = createAnimatedIcon({
  name: "LogoutIcon",
  elements: [
    "M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4",
    { tag: "motion.polyline", points: "16 17 21 12 16 7", variants: PATH_VARIANTS },
    { tag: "motion.line", x1: "21", x2: "9", y1: "12", y2: "12", variants: PATH_VARIANTS },
  ],
});
