// @vegastack icon-map-pin-check@0.7.0 sha256-/dqnuEhojhiIk+XhA4263rWm7NOxjoA2HL4CtIpsydE=

// Mirrored from lucide-animated (https://lucide-animated.com/r/map-pin-check.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SVG_VARIANTS: Variants = { normal: { y: 0 }, animate: { y: [0, -5, -3], transition: { duration: 0.5, times: [0, 0.6, 1] } } };

const CHECK_VARIANTS: Variants = { normal: { opacity: 1 }, animate: { opacity: [0, 1], pathLength: [0, 1], transition: { delay: 0.3, duration: 0.3, opacity: { duration: 0.1, delay: 0.3 } } } };

export type MapPinCheckIconHandle = AnimatedIconHandle;

export const MapPinCheckIcon = createAnimatedIcon({
  name: "MapPinCheckIcon",
  svg: { tag: "motion.svg", variants: SVG_VARIANTS, initial: "normal" },
  elements: [
    "M19.43 12.935c.357-.967.57-1.955.57-2.935a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 32.197 32.197 0 0 0 .813-.728",
    { tag: "circle", cx: "12", cy: "10", r: "3" },
    { tag: "motion.path", d: "m16 18 2 2 4-4", variants: CHECK_VARIANTS, initial: "normal" },
  ],
});
