// @vegastack icon-map-pin-check-inside@0.7.0 sha256-LF5/pgQkgLdn5iaLCbcX2trWVm0lztR7Si8xXKi39qI=

// Mirrored from lucide-animated (https://lucide-animated.com/r/map-pin-check-inside.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SVG_VARIANTS: Variants = { normal: { y: 0 }, animate: { y: [0, -5, -3], transition: { duration: 0.5, times: [0, 0.6, 1] } } };

const CHECK_VARIANTS: Variants = { normal: { opacity: 1 }, animate: { opacity: [0, 1], pathLength: [0, 1], transition: { delay: 0.3, duration: 0.3, opacity: { duration: 0.1, delay: 0.3 } } } };

export type MapPinCheckInsideIconHandle = AnimatedIconHandle;

export const MapPinCheckInsideIcon = createAnimatedIcon({
  name: "MapPinCheckInsideIcon",
  svg: { tag: "motion.svg", variants: SVG_VARIANTS, initial: "normal" },
  elements: [
    "M20 10c0 4.993-5.539 10.193-7.399 11.799a1 1 0 0 1-1.202 0C9.539 20.193 4 14.993 4 10a8 8 0 0 1 16 0",
    { tag: "motion.path", d: "m9 10 2 2 4-4", variants: CHECK_VARIANTS, initial: "normal" },
  ],
});
