// @vegastack icon-map-pin-minus@0.7.2 sha256-kwd4tXzlWmOPAyO7jy3NC+m/uzWW4/Xj487vkcvB1hU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/map-pin-minus.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SVG_VARIANTS: Variants = { normal: { y: 0 }, animate: { y: [0, -5, -3], transition: { duration: 0.5, times: [0, 0.6, 1] } } };

const MINUS_VARIANTS: Variants = { normal: { opacity: 1 }, animate: { opacity: [0, 1], pathLength: [0, 1], transition: { delay: 0.3, duration: 0.3, opacity: { duration: 0.1, delay: 0.3 } } } };

export type MapPinMinusIconHandle = AnimatedIconHandle;

export const MapPinMinusIcon = createAnimatedIcon({
  name: "MapPinMinusIcon",
  svg: { tag: "motion.svg", variants: SVG_VARIANTS, initial: "normal" },
  elements: [
    "M18.977 14C19.6 12.701 20 11.343 20 10a8 8 0 0 0-16 0c0 4.993 5.539 10.193 7.399 11.799a1 1 0 0 0 1.202 0 32 32 0 0 0 .824-.738",
    { tag: "circle", cx: "12", cy: "10", r: "3" },
    { tag: "motion.path", d: "M16 18h6", variants: MINUS_VARIANTS, initial: "normal" },
  ],
});
