// @vegastack icon-message-circle-x@0.6.0 sha256-hZ1WGnO+XVMH4XfOSur9dFabLY4Nsbk3Ou540O3hSH0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/message-circle-x.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const FIRST_LINE_VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1, transition: { duration: 0.3 } },
  animate: { pathLength: [0, 1], opacity: [0, 1], transition: { pathLength: { duration: 0.4, ease: "easeInOut" }, opacity: { duration: 0.4, ease: "easeInOut" } } },
};

const SECOND_LINE_VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1, transition: { duration: 0.3 } },
  animate: { pathLength: [0, 1], opacity: [0, 1], transition: { pathLength: { duration: 0.4, ease: "easeInOut", delay: 0.2 }, opacity: { duration: 0.4, ease: "easeInOut", delay: 0.2 } } },
};

export type MessageCircleXIconHandle = AnimatedIconHandle;

export const MessageCircleXIcon = createAnimatedIcon({
  name: "MessageCircleXIcon",
  elements: [
    "M2.992 16.342a2 2 0 0 1 .094 1.167l-1.065 3.29a1 1 0 0 0 1.236 1.168l3.413-.998a2 2 0 0 1 1.099.092 10 10 0 1 0-4.777-4.719",
    { tag: "motion.path", d: "m15 9-6 6", variants: FIRST_LINE_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "m9 9 6 6", variants: SECOND_LINE_VARIANTS, initial: "normal" },
  ],
});
