// @vegastack icon-mic@0.3.0 sha256-tz47AdjtrRYNmGk1ZAzf0K//C50+45UdIMSzaqVJOVE=

// Mirrored from lucide-animated (https://lucide-animated.com/r/mic.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface MicIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface MicIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<MicIconHandle>;
}

const CAPSULE_VARIANTS: Variants = {
  normal: { y: 0 },
  animate: {
    y: [0, -3, 0, -2, 0],
    transition: {
      duration: 0.6,
      ease: "easeInOut",
    },
  },
};

const MicIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: MicIconProps) => {
  const controls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = () => runAnimation(controls, "animate");
  const stopAnimation = () => resetAnimation(controls, "normal");
  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <svg
        fill="none"
        height={size}
        overflow="visible"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d="M12 19v3" />
        <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
        <motion.rect
          animate={controls}
          height="13"
          rx="3"
          variants={CAPSULE_VARIANTS}
          width="6"
          x="9"
          y="2"
        />
      </svg>
    </div>
  );
};

MicIcon.displayName = "MicIcon";

export { MicIcon };
