// @vegastack icon-monitor-cog@0.6.0 sha256-z6yddPFxm4KGiTuS8ErQ0DuQ+7QsjUVUPeyQG8gOoYk=

// Mirrored from lucide-animated (https://lucide-animated.com/r/monitor-cog.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const G_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: 180 } };

export type MonitorCogIconHandle = AnimatedIconHandle;

export const MonitorCogIcon = createAnimatedIcon({
  name: "MonitorCogIcon",
  svg: { style: { overflow: "visible" } },
  elements: [
    "M12 17v4",
    "M22 13v2a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h7",
    "M8 21h8",
    {
      tag: "motion.g",
      variants: G_VARIANTS,
      transition: { type: "spring", stiffness: 50, damping: 10 },
      children: [
        "m14.305 7.53.923-.382",
        "m15.228 4.852-.923-.383",
        "m16.852 3.228-.383-.924",
        "m16.852 8.772-.383.923",
        "m19.148 3.228.383-.924",
        "m19.53 9.696-.382-.924",
        "m20.772 4.852.924-.383",
        "m20.772 7.148.924.383",
        { tag: "circle", cx: "18", cy: "6", r: "3" },
      ],
    },
  ],
});
