// @vegastack icon-pen-tool@0.7.0 sha256-HJgvJVveFx648duXnuPu3MH/l5EiWiqAlZKgQa8lCCI=

// Mirrored from lucide-animated (https://lucide-animated.com/r/pen-tool.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SVG_VARIANTS: Variants = { normal: { rotate: 0, translateX: 0, translateY: 0 }, animate: { rotate: [0, 0, 8, -3, 8, 0], translateY: [0, 2, 0, -1, 0] } };

const PATH_VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1, pathOffset: 0 }, animate: { pathLength: [0, 0, 1], opacity: [0, 1], pathOffset: [0, 1, 0] } };

export type PenToolIconHandle = AnimatedIconHandle;

export const PenToolIcon = createAnimatedIcon({
  name: "PenToolIcon",
  svg: { tag: "motion.svg", variants: SVG_VARIANTS, transition: { duration: 1 } },
  elements: [
    "M15.707 21.293a1 1 0 0 1-1.414 0l-1.586-1.586a1 1 0 0 1 0-1.414l5.586-5.586a1 1 0 0 1 1.414 0l1.586 1.586a1 1 0 0 1 0 1.414z",
    "m18 13-1.375-6.874a1 1 0 0 0-.746-.776L3.235 2.028a1 1 0 0 0-1.207 1.207L5.35 15.879a1 1 0 0 0 .776.746L13 18",
    { tag: "motion.path", d: "m2.3 2.3 7.286 7.286", variants: PATH_VARIANTS, transition: { duration: 0.8 } },
    { tag: "circle", cx: "11", cy: "11", r: "2" },
  ],
});
