// @vegastack icon-pickaxe@0.3.0 sha256-fY0wEfzQdb/ahq14faccjc5wPN6Bl9gEnKPf5ivYpck=

// Mirrored from lucide-animated (https://lucide-animated.com/r/pickaxe.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface PickaxeIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface PickaxeIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<PickaxeIconHandle>;
}

const PICKAXE_VARIANTS: Variants = {
  normal: {
    rotate: 0,
    transition: {
      duration: 0.3,
      ease: "easeOut",
    },
  },
  animate: {
    rotate: [0, -20, 25, 0],
    transition: {
      duration: 0.8,
      times: [0, 0.6, 0.8, 1],
      ease: ["easeInOut", "easeOut", "easeOut"],
    },
  },
};

const PickaxeIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: PickaxeIconProps) => {
  const controls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = () => runAnimation(controls, "animate");
  const stopAnimation = () => resetAnimation(controls, "normal");
  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <motion.svg
        animate={controls}
        fill="none"
        height={size}
        initial="normal"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        style={{ transformOrigin: "0% 100%", transformBox: "fill-box" }}
        variants={PICKAXE_VARIANTS}
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d="m14 13-8.381 8.38a1 1 0 0 1-3.001-3L11 9.999" />
        <path d="M15.973 4.027A13 13 0 0 0 5.902 2.373c-1.398.342-1.092 2.158.277 2.601a19.9 19.9 0 0 1 5.822 3.024" />
        <path d="M16.001 11.999a19.9 19.9 0 0 1 3.024 5.824c.444 1.369 2.26 1.676 2.603.278A13 13 0 0 0 20 8.069" />
        <path d="M18.352 3.352a1.205 1.205 0 0 0-1.704 0l-5.296 5.296a1.205 1.205 0 0 0 0 1.704l2.296 2.296a1.205 1.205 0 0 0 1.704 0l5.296-5.296a1.205 1.205 0 0 0 0-1.704z" />
      </motion.svg>
    </div>
  );
};

PickaxeIcon.displayName = "PickaxeIcon";

export { PickaxeIcon };
