// @vegastack icon-plus@0.23.115 sha256-lPsUBcdD1XAlf6LWQKl39WZHlhXofFb40LxtDe/B/k8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/plus.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type PlusIconHandle = AnimatedIconHandle;

export const PlusIcon = createAnimatedIcon({
  name: "PlusIcon",
  svg: { tag: "motion.svg", variants: { normal: { rotate: 0 }, animate: { rotate: 180 } }, transition: { type: "spring", stiffness: 100, damping: 15 } },
  elements: ["M5 12h14", "M12 5v14"],
});
