// @vegastack icon-radio-tower@0.6.0 sha256-2oOquuHAXA5/kuOeLE5898emCs3EhbEIrmJOcxDKbZQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/radio-tower.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const VARIANTS: Variants = {
  normal: { opacity: 1, transition: { duration: 0.4 } },
  fadeOut: { opacity: 0, transition: { duration: 0.3 } },
  fadeIn: (i: number) => ({ opacity: 1, transition: { type: "spring", stiffness: 300, damping: 20, delay: i * 0.1 } }),
};

export type RadioTowerIconHandle = AnimatedIconHandle;

export const RadioTowerIcon = createAnimatedIcon({
  name: "RadioTowerIcon",
  elements: [
    { tag: "motion.path", d: "M4.9 16.1C1 12.2 1 5.8 4.9 1.9", variants: VARIANTS, initial: { opacity: 1 }, custom: 1 },
    { tag: "motion.path", d: "M7.8 4.7a6.14 6.14 0 0 0-.8 7.5", variants: VARIANTS, initial: { opacity: 1 }, custom: 0 },
    { tag: "circle", cx: "12", cy: "9", r: "2" },
    { tag: "motion.path", d: "M16.2 4.8c2 2 2.26 5.11.8 7.47", variants: VARIANTS, initial: { opacity: 1 }, custom: 0 },
    { tag: "motion.path", d: "M19.1 1.9a9.96 9.96 0 0 1 0 14.1", variants: VARIANTS, initial: { opacity: 1 }, custom: 1 },
    "M9.5 18h5",
    "m8 22 4-11 4 11",
  ],
  start: async ({ controls, run }) => {
    await run(controls.default, "fadeOut");
    run(controls.default, "fadeIn");
  },
  stop: ({ controls, reset }) => {
    reset(controls.default, "normal");
  },
});
