// @vegastack icon-refresh-ccw@0.25.0 sha256-9FhQxE/mcYpz9NDGnlQsN1xJLJwHR8IddoLOO94kwbo=

// Mirrored from lucide-animated (https://lucide-animated.com/r/refresh-ccw.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type RefreshCCWIconHandle = AnimatedIconHandle;

export const RefreshCCWIcon = createAnimatedIcon({
  name: "RefreshCCWIcon",
  elements: [
    {
      tag: "motion.g",
      variants: { normal: { rotate: "0deg" }, animate: { rotate: "-50deg" } },
      transition: { type: "spring", stiffness: 250, damping: 25 },
      children: ["M3 2v6h6", "M21 12A9 9 0 0 0 6 5.3L3 8", "M21 22v-6h-6", "M3 12a9 9 0 0 0 15 6.7l3-2.7"],
    },
  ],
});
