// @vegastack icon-square-arrow-down@0.7.4 sha256-fm7vO9mgP8+/vroj4Ie3m9v9YHoUDJ05WYIEwIKoYTg=

// Mirrored from lucide-animated (https://lucide-animated.com/r/square-arrow-down.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SQUARE_VARIANTS: Variants = { normal: { transition: { duration: 0.4 } }, animate: { transition: { duration: 0.6, ease: "easeInOut" } } };

const PATH_VARIANTS: Variants = { normal: { d: "m8 12 4 4 4-4", translateY: 0, opacity: 1 }, animate: { d: "m8 12 4 4 4-4", translateY: [0, -3, 0], transition: { duration: 0.4 } } };

const SECOND_PATH_VARIANTS: Variants = { normal: { d: "M12 8v8", opacity: 1 }, animate: { d: ["M12 8v8", "M12 8v5", "M12 8v8"], transition: { duration: 0.4 } } };

export type SquareArrowDownIconHandle = AnimatedIconHandle;

export const SquareArrowDownIcon = createAnimatedIcon({
  name: "SquareArrowDownIcon",
  elements: [
    { tag: "motion.rect", height: "18", rx: "2", width: "18", x: "3", y: "3", variants: SQUARE_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "m8 12 4 4 4-4", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M12 8v8", variants: SECOND_PATH_VARIANTS, initial: "normal" },
  ],
});
