// @vegastack icon-square-arrow-right@0.1.0 sha256-AlW7882Fr4AiAwmlLR4YilfAg3uCRlWza7xut6jA4fk=

// Mirrored from lucide-animated (https://lucide-animated.com/r/square-arrow-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation } from "motion/react";
import type { HTMLAttributes } from "react";
import { forwardRef, useCallback, useImperativeHandle, useRef } from "react";

import { cn } from "@vegastack/design";

export interface SquareArrowRightIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface SquareArrowRightIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number;
}

const SQUARE_VARIANTS: Variants = {
  normal: { transition: { duration: 0.4 } },
  animate: { transition: { duration: 0.6, ease: "easeInOut" } },
};

const PATH_VARIANTS: Variants = {
  normal: { d: "M8 12h8", opacity: 1 },
  animate: {
    d: ["M8 12h8", "M8 12h5", "M8 12h8"],
    transition: { duration: 0.4 },
  },
};

const SECOND_PATH_VARIANTS: Variants = {
  normal: { d: "m12 8 4 4-4 4", translateX: 0, opacity: 1 },
  animate: {
    d: "m12 8 4 4-4 4",
    translateX: [0, -3, 0],
    transition: { duration: 0.4 },
  },
};

const SquareArrowRightIcon = forwardRef<
  SquareArrowRightIconHandle,
  SquareArrowRightIconProps
>(({ onMouseEnter, onMouseLeave, className, size = 28, ...props }, ref) => {
  const controls = useAnimation();
  const isControlledRef = useRef(false);

  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return {
      startAnimation: () => controls.start("animate"),
      stopAnimation: () => controls.start("normal"),
    };
  });

  const handleMouseEnter = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (isControlledRef.current) onMouseEnter?.(e);
      else controls.start("animate");
    },
    [controls, onMouseEnter]
  );

  const handleMouseLeave = useCallback(
    (e: React.MouseEvent<HTMLDivElement>) => {
      if (isControlledRef.current) onMouseLeave?.(e);
      else controls.start("normal");
    },
    [controls, onMouseLeave]
  );

  return (
    <div
      className={cn(className)}
      onMouseEnter={handleMouseEnter}
      onMouseLeave={handleMouseLeave}
      {...props}
    >
      <svg
        fill="none"
        height={size}
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <motion.rect
          animate={controls}
          height="18"
          initial="normal"
          rx="2"
          variants={SQUARE_VARIANTS}
          width="18"
          x="3"
          y="3"
        />
        <motion.path
          animate={controls}
          d="M8 12h8"
          initial="normal"
          variants={PATH_VARIANTS}
        />
        <motion.path
          animate={controls}
          d="m12 8 4 4-4 4"
          initial="normal"
          variants={SECOND_PATH_VARIANTS}
        />
      </svg>
    </div>
  );
});

SquareArrowRightIcon.displayName = "SquareArrowRightIcon";

export { SquareArrowRightIcon };

