// @vegastack icon-sun-dim@0.7.2 sha256-nwreTxt8EJAlUKYMZW1PM0HApynTPNYXnNnOIEGkZO4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/sun-dim.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { opacity: 1 }, animate: (i: number) => ({ opacity: [0, 1], transition: { delay: i * 0.1, duration: 0.3 } }) };

export type SunDimIconHandle = AnimatedIconHandle;

export const SunDimIcon = createAnimatedIcon({
  name: "SunDimIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "4" },
    { tag: "motion.path", d: "M12 4h.01", variants: PATH_VARIANTS, custom: 1 },
    { tag: "motion.path", d: "M20 12h.01", variants: PATH_VARIANTS, custom: 2 },
    { tag: "motion.path", d: "M12 20h.01", variants: PATH_VARIANTS, custom: 3 },
    { tag: "motion.path", d: "M4 12h.01", variants: PATH_VARIANTS, custom: 4 },
    { tag: "motion.path", d: "M17.657 6.343h.01", variants: PATH_VARIANTS, custom: 5 },
    { tag: "motion.path", d: "M17.657 17.657h.01", variants: PATH_VARIANTS, custom: 6 },
    { tag: "motion.path", d: "M6.343 17.657h.01", variants: PATH_VARIANTS, custom: 7 },
    { tag: "motion.path", d: "M6.343 6.343h.01", variants: PATH_VARIANTS, custom: 8 },
  ],
});
