// @vegastack icon-thermometer@0.19.0 sha256-cgKibyQ8r8/s9b6L3I9P+9H7Uo5Ju6+DKbi+GivU/NA=

// Mirrored from lucide-animated (https://lucide-animated.com/r/thermometer.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: [0, -5, 5, -5, 5, 0], transition: { duration: 0.4, times: [0, 0.2, 0.4, 0.6, 0.8, 1] } } };

export type ThermometerIconHandle = AnimatedIconHandle;

export const ThermometerIcon = createAnimatedIcon({
  name: "ThermometerIcon",
  elements: [{ tag: "motion.path", d: "M14 4v10.54a4 4 0 1 1-4 0V4a2 2 0 0 1 4 0Z", variants: PATH_VARIANTS, style: { transformOrigin: "center" } }],
});
