// @vegastack icon-train-track@0.7.5 sha256-H/JUqtMAZ6g2nQV8DVuQEwJfUR+v2A4VTKXS8j/yzjQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/train-track.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const TRANSITION: Transition = { duration: 0.3, opacity: { delay: 0.15 } };

const VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1 }, animate: (custom: number) => ({ pathLength: [0, 1], opacity: [0, 1], transition: { ...TRANSITION, delay: 0.1 * custom } }) };

export type TrainTrackIconHandle = AnimatedIconHandle;

export const TrainTrackIcon = createAnimatedIcon({
  name: "TrainTrackIcon",
  elements: [
    "M2 17 17 2",
    { tag: "motion.path", d: "m2 14 8 8", variants: VARIANTS, custom: 4 },
    { tag: "motion.path", d: "m5 11 8 8", variants: VARIANTS, custom: 3 },
    { tag: "motion.path", d: "m8 8 8 8", variants: VARIANTS, custom: 2 },
    { tag: "motion.path", d: "m11 5 8 8", variants: VARIANTS, custom: 1 },
    { tag: "motion.path", d: "m14 2 8 8", variants: VARIANTS, custom: 0 },
    "M7 22 22 7",
  ],
});
