// @vegastack icon-trending-up-down@0.8.2 sha256-AmZA+Mc0BQBTAoeZvcK/FE+QW89G0Oylb+77r0cWz2U=

// Mirrored from lucide-animated (https://lucide-animated.com/r/trending-up-down.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SVG_VARIANTS: Variants = { animate: { x: 0, y: 0, translateX: [0, 2, 0], transition: { duration: 0.5 } } };

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, transition: { duration: 0.4, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], pathOffset: [1, 0], transition: { duration: 0.4, opacity: { duration: 0.1 } } },
};

const ARROW_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, transition: { delay: 0.3, duration: 0.3, opacity: { duration: 0.1, delay: 0.3 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], pathOffset: [0.5, 0], transition: { delay: 0.3, duration: 0.3, opacity: { duration: 0.1, delay: 0.3 } } },
};

export type TrendingUpDownIconHandle = AnimatedIconHandle;

export const TrendingUpDownIcon = createAnimatedIcon({
  name: "TrendingUpDownIcon",
  svg: { tag: "motion.svg", variants: SVG_VARIANTS, initial: "normal" },
  elements: [
    { tag: "motion.path", d: "M21 21 14.828 14.828", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M21 16v5h-5", variants: ARROW_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "m21 3-9 9-4-4-6 6", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M21 8V3h-5", variants: ARROW_VARIANTS, initial: "normal" },
  ],
});
