// GENERATED by tooling/sync-component-derived.mjs from packages/ui/component-contracts.json.
// Contract SHA-256: e9035bd97850b213755b93d6e42cd4bcb4f9cec45de9777f84b06bcfe881fe3b

export const HOME_TOTAL_REGISTRY_ITEM_COUNT = 554;
export const HOME_COMPONENT_COUNT = 108;
export const HOME_ANIMATED_ICON_COUNT = 439;
export const HOME_HOOK_COUNT = 6;
export const HOME_BLOCK_COUNT = 1;

export const HOME_COMPONENT_GROUPS = [
  {
    "number": "01",
    "title": "Core controls",
    "description": "Actions, selection, status, loading, identity, and compact utility controls.",
    "components": [
      {
        "name": "button",
        "title": "Button",
        "href": "/docs/components/button"
      },
      {
        "name": "icon-button",
        "title": "Icon Button",
        "href": "/docs/components/icon-button"
      },
      {
        "name": "copy-button",
        "title": "Copy Button",
        "href": "/docs/components/copy-button"
      },
      {
        "name": "notification-bell",
        "title": "Notification Bell",
        "href": "/docs/components/notification-bell"
      },
      {
        "name": "badge",
        "title": "Badge",
        "href": "/docs/components/badge"
      },
      {
        "name": "avatar",
        "title": "Avatar",
        "href": "/docs/components/avatar"
      },
      {
        "name": "label",
        "title": "Label",
        "href": "/docs/components/label"
      },
      {
        "name": "input",
        "title": "Input",
        "href": "/docs/components/input"
      },
      {
        "name": "textarea",
        "title": "Textarea",
        "href": "/docs/components/textarea"
      },
      {
        "name": "checkbox",
        "title": "Checkbox",
        "href": "/docs/components/checkbox"
      },
      {
        "name": "radio-group",
        "title": "Radio Group",
        "href": "/docs/components/radio-group"
      },
      {
        "name": "switch",
        "title": "Switch",
        "href": "/docs/components/switch"
      },
      {
        "name": "slider",
        "title": "Slider",
        "href": "/docs/components/slider"
      },
      {
        "name": "progress",
        "title": "Progress",
        "href": "/docs/components/progress"
      },
      {
        "name": "separator",
        "title": "Separator",
        "href": "/docs/components/separator"
      },
      {
        "name": "skeleton",
        "title": "Skeleton",
        "href": "/docs/components/skeleton"
      },
      {
        "name": "spinner",
        "title": "Spinner",
        "href": "/docs/components/spinner"
      },
      {
        "name": "status-icon",
        "title": "Status Icon",
        "href": "/docs/components/status-icon"
      },
      {
        "name": "kbd",
        "title": "Kbd",
        "href": "/docs/components/kbd"
      },
      {
        "name": "relative-time",
        "title": "Relative Time",
        "href": "/docs/components/relative-time"
      },
      {
        "name": "animated-number",
        "title": "Animated Number",
        "href": "/docs/components/animated-number"
      },
      {
        "name": "toggle",
        "title": "Toggle",
        "href": "/docs/components/toggle"
      },
      {
        "name": "toggle-group",
        "title": "Toggle Group",
        "href": "/docs/components/toggle-group"
      }
    ]
  },
  {
    "number": "02",
    "title": "Forms & editing",
    "description": "Structured fields, validation, rich editing, dates, countries, and autosave.",
    "components": [
      {
        "name": "field",
        "title": "Field",
        "href": "/docs/components/field"
      },
      {
        "name": "field-inline",
        "title": "Field Inline",
        "href": "/docs/components/field-inline"
      },
      {
        "name": "settings-row",
        "title": "Settings Row",
        "href": "/docs/components/settings-row"
      },
      {
        "name": "auto-save-input",
        "title": "Auto Save Input",
        "href": "/docs/components/auto-save-input"
      },
      {
        "name": "password-input",
        "title": "Password Input",
        "href": "/docs/components/password-input"
      },
      {
        "name": "otp-input",
        "title": "OTP Input",
        "href": "/docs/components/otp-input"
      },
      {
        "name": "color-picker",
        "title": "Color Picker",
        "href": "/docs/components/color-picker"
      },
      {
        "name": "select",
        "title": "Select",
        "href": "/docs/components/select"
      },
      {
        "name": "combobox",
        "title": "Combobox",
        "href": "/docs/components/combobox"
      },
      {
        "name": "country-select",
        "title": "Country Select",
        "href": "/docs/components/country-select"
      },
      {
        "name": "region-select",
        "title": "Region Select",
        "href": "/docs/components/region-select"
      },
      {
        "name": "date-picker",
        "title": "Date Picker",
        "href": "/docs/components/date-picker"
      },
      {
        "name": "filter-bar",
        "title": "Filter Bar",
        "href": "/docs/components/filter-bar"
      },
      {
        "name": "tag-group",
        "title": "Tag Group",
        "href": "/docs/components/tag-group"
      },
      {
        "name": "text-edit",
        "title": "Text Edit",
        "href": "/docs/components/text-edit"
      },
      {
        "name": "segmented",
        "title": "Segmented",
        "href": "/docs/components/segmented"
      },
      {
        "name": "editable-cell",
        "title": "Editable Cell",
        "href": "/docs/components/editable-cell"
      },
      {
        "name": "number-field",
        "title": "Number Field",
        "href": "/docs/components/number-field"
      },
      {
        "name": "chip-input",
        "title": "Chip Input",
        "href": "/docs/components/chip-input"
      },
      {
        "name": "filter-bar-managed",
        "title": "Filter Builder",
        "href": "/docs/components/filter-bar-managed"
      },
      {
        "name": "sortable-list",
        "title": "Sortable List",
        "href": "/docs/components/sortable-list"
      },
      {
        "name": "dropzone",
        "title": "Dropzone",
        "href": "/docs/components/dropzone"
      }
    ]
  },
  {
    "number": "03",
    "title": "Navigation & layout",
    "description": "Page structure, responsive shells, navigation, sidebars, and content framing.",
    "components": [
      {
        "name": "accordion",
        "title": "Accordion",
        "href": "/docs/components/accordion"
      },
      {
        "name": "breadcrumb",
        "title": "Breadcrumb",
        "href": "/docs/components/breadcrumb"
      },
      {
        "name": "collapsible",
        "title": "Collapsible",
        "href": "/docs/components/collapsible"
      },
      {
        "name": "command",
        "title": "Command Menu",
        "href": "/docs/components/command"
      },
      {
        "name": "pagination",
        "title": "Pagination",
        "href": "/docs/components/pagination"
      },
      {
        "name": "tabs",
        "title": "Tabs",
        "href": "/docs/components/tabs"
      },
      {
        "name": "sidebar",
        "title": "Sidebar",
        "href": "/docs/components/sidebar"
      },
      {
        "name": "navigation-menu",
        "title": "Navigation Menu",
        "href": "/docs/components/navigation-menu"
      },
      {
        "name": "app-shell",
        "title": "App Shell",
        "href": "/docs/components/app-shell"
      },
      {
        "name": "resizable",
        "title": "Resizable",
        "href": "/docs/components/resizable"
      },
      {
        "name": "scroll-area",
        "title": "Scroll Area",
        "href": "/docs/components/scroll-area"
      },
      {
        "name": "split-button",
        "title": "Split Button",
        "href": "/docs/components/split-button"
      },
      {
        "name": "stepper",
        "title": "Stepper",
        "href": "/docs/components/stepper"
      },
      {
        "name": "board",
        "title": "Board",
        "href": "/docs/components/board"
      }
    ]
  },
  {
    "number": "04",
    "title": "Overlays",
    "description": "Focused tasks, contextual actions, menus, commands, and progressive disclosure.",
    "components": [
      {
        "name": "alert-dialog",
        "title": "Alert Dialog",
        "href": "/docs/components/alert-dialog"
      },
      {
        "name": "dialog",
        "title": "Dialog",
        "href": "/docs/components/dialog"
      },
      {
        "name": "sheet",
        "title": "Sheet",
        "href": "/docs/components/sheet"
      },
      {
        "name": "popover",
        "title": "Popover",
        "href": "/docs/components/popover"
      },
      {
        "name": "hover-card",
        "title": "Hover Card",
        "href": "/docs/components/hover-card"
      },
      {
        "name": "tooltip",
        "title": "Tooltip",
        "href": "/docs/components/tooltip"
      },
      {
        "name": "dropdown-menu",
        "title": "Dropdown Menu",
        "href": "/docs/components/dropdown-menu"
      },
      {
        "name": "context-menu",
        "title": "Context Menu",
        "href": "/docs/components/context-menu"
      },
      {
        "name": "emoji-picker",
        "title": "Emoji Picker",
        "href": "/docs/components/emoji-picker"
      },
      {
        "name": "sonner",
        "title": "Toast",
        "href": "/docs/components/toast"
      },
      {
        "name": "provider",
        "title": "Provider",
        "href": "/docs/components/provider"
      },
      {
        "name": "action-bar",
        "title": "Action Bar",
        "href": "/docs/components/action-bar"
      },
      {
        "name": "shortcut-overlay",
        "title": "Shortcut Overlay",
        "href": "/docs/components/shortcut-overlay"
      }
    ]
  },
  {
    "number": "05",
    "title": "Data display",
    "description": "Structured records, filtering, charts, tables, properties, and responsive lists.",
    "components": [
      {
        "name": "card",
        "title": "Card",
        "href": "/docs/components/card"
      },
      {
        "name": "table",
        "title": "Table",
        "href": "/docs/components/table"
      },
      {
        "name": "data-list",
        "title": "Data List",
        "href": "/docs/components/data-list"
      },
      {
        "name": "data-grid",
        "title": "Data Grid",
        "href": "/docs/components/data-grid"
      },
      {
        "name": "chart",
        "title": "Chart",
        "href": "/docs/components/chart"
      },
      {
        "name": "comparison-matrix",
        "title": "Comparison Matrix",
        "href": "/docs/components/comparison-matrix"
      },
      {
        "name": "property-list",
        "title": "Property List",
        "href": "/docs/components/property-list"
      },
      {
        "name": "stat",
        "title": "Stat",
        "href": "/docs/components/stat"
      },
      {
        "name": "progress-indicator",
        "title": "Progress Indicator",
        "href": "/docs/components/progress-indicator"
      },
      {
        "name": "timeline",
        "title": "Timeline",
        "href": "/docs/components/timeline"
      }
    ]
  },
  {
    "number": "06",
    "title": "Content & marketing",
    "description": "Public-facing composition, type, code, pricing, announcements, and brand motion.",
    "components": [
      {
        "name": "alert",
        "title": "Alert",
        "href": "/docs/components/alert"
      },
      {
        "name": "empty",
        "title": "Empty",
        "href": "/docs/components/empty"
      },
      {
        "name": "truncated-text",
        "title": "Truncated Text",
        "href": "/docs/components/truncated-text"
      },
      {
        "name": "image",
        "title": "Image",
        "href": "/docs/components/image"
      },
      {
        "name": "onboarding-checklist",
        "title": "Onboarding Checklist",
        "href": "/docs/components/onboarding-checklist"
      },
      {
        "name": "markdown-view",
        "title": "Markdown View",
        "href": "/docs/components/markdown-view"
      },
      {
        "name": "code-block",
        "title": "Code Block",
        "href": "/docs/components/code-block"
      },
      {
        "name": "page-header",
        "title": "Page Header",
        "href": "/docs/components/page-header"
      },
      {
        "name": "item",
        "title": "Item",
        "href": "/docs/components/item"
      },
      {
        "name": "marketing-surface",
        "title": "Marketing Surface",
        "href": "/docs/components/marketing-surface"
      },
      {
        "name": "section-header",
        "title": "Section Header",
        "href": "/docs/components/section-header"
      },
      {
        "name": "figure-frame",
        "title": "Figure Frame",
        "href": "/docs/components/figure-frame"
      },
      {
        "name": "terminal",
        "title": "Terminal",
        "href": "/docs/components/terminal"
      },
      {
        "name": "logo-row",
        "title": "Logo Row",
        "href": "/docs/components/logo-row"
      },
      {
        "name": "testimonial",
        "title": "Testimonial",
        "href": "/docs/components/testimonial"
      },
      {
        "name": "announcement-banner",
        "title": "Announcement Banner",
        "href": "/docs/components/announcement-banner"
      },
      {
        "name": "ruled-band",
        "title": "Ruled Band",
        "href": "/docs/components/ruled-band"
      },
      {
        "name": "pricing-section",
        "title": "Pricing Section",
        "href": "/docs/components/pricing-section"
      },
      {
        "name": "staggered-text-reveal",
        "title": "Staggered Text Reveal",
        "href": "/docs/components/staggered-text-reveal"
      },
      {
        "name": "particle-field",
        "title": "Particle Field",
        "href": "/docs/components/particle-field"
      }
    ]
  },
  {
    "number": "07",
    "title": "AI & chat",
    "description": "Messages, bubbles, attachments, tool activity, and anchored conversation scrolling.",
    "components": [
      {
        "name": "marker",
        "title": "Marker",
        "href": "/docs/components/marker"
      },
      {
        "name": "message",
        "title": "Message",
        "href": "/docs/components/message"
      },
      {
        "name": "bubble",
        "title": "Bubble",
        "href": "/docs/components/bubble"
      },
      {
        "name": "message-scroller",
        "title": "Message Scroller",
        "href": "/docs/components/message-scroller"
      },
      {
        "name": "attachment",
        "title": "Attachment",
        "href": "/docs/components/attachment"
      },
      {
        "name": "tool-call-chip",
        "title": "Tool Call Chip",
        "href": "/docs/components/tool-call-chip"
      }
    ]
  }
] as const;
