// @vegastack icon-data@0.25.6 sha256-d5nPw0NeLO7i6NknHN1kB5huniXQS8UxlG5frXgExG0=

/** Curated catalogue metadata. Upstream tags pinned to Lucide revision 3b9ea6d08707edc439f25a4c354cb0d6b8bee973. */
export const ICON_CATEGORIES = [
  "Work",
  "People",
  "Communication",
  "Documents",
  "Technology",
  "Organisation",
  "Places",
  "Objects",
] as const;
/** A browsing category in the icon picker. */
export type IconCategory = (typeof ICON_CATEGORIES)[number];
/** The 160 reviewed outline icon entries; data only, safe for server validation. */
export const ICON_CATALOGUE = [
  {
    name: "briefcase-business",
    label: "Briefcase Business",
    category: "Work",
    tags: ["work", "bag", "baggage", "folder", "portfolio"],
    aliases: [
      "business",
      "sales",
      "client",
      "clients",
      "office",
      "folders",
      "briefcases",
      "businesses",
      "offices",
    ],
  },
  {
    name: "chart-no-axes-combined",
    label: "Chart No Axes Combined",
    category: "Work",
    tags: ["statistics", "analytics", "diagram", "graph", "trending up"],
    aliases: ["analytics", "reports", "report"],
  },
  {
    name: "target",
    label: "Target",
    category: "Work",
    tags: [
      "logo",
      "bullseye",
      "deadline",
      "projects",
      "overview",
      "work",
      "productivity",
    ],
    aliases: ["goal", "goals", "sales", "project"],
  },
  {
    name: "handshake",
    label: "Handshake",
    category: "Work",
    tags: [
      "agreement",
      "partnership",
      "deal",
      "business",
      "assistance",
      "cooperation",
      "friendship",
      "union",
      "terms",
    ],
    aliases: ["deal", "deals", "partner", "partners", "businesses"],
  },
  {
    name: "presentation",
    label: "Presentation",
    category: "Work",
    tags: [
      "screen",
      "whiteboard",
      "marker pens",
      "markers",
      "blackboard",
      "chalk",
      "easel",
      "school",
      "learning",
      "lesson",
      "office",
      "meeting",
      "project",
      "planning",
    ],
    aliases: ["meetings", "projects", "offices"],
  },
  {
    name: "megaphone",
    label: "Megaphone",
    category: "Work",
    tags: [
      "advertisement",
      "announcement",
      "attention",
      "alert",
      "loudspeaker",
      "megaphone",
      "notification",
    ],
    aliases: [],
  },
  {
    name: "badge-check",
    label: "Badge Check",
    category: "Work",
    tags: ["verified", "check"],
    aliases: [],
  },
  {
    name: "award",
    label: "Award",
    category: "Work",
    tags: ["achievement", "badge", "rosette", "prize", "winner"],
    aliases: [],
  },
  {
    name: "trophy",
    label: "Trophy",
    category: "Work",
    tags: [
      "prize",
      "sports",
      "winner",
      "achievement",
      "award",
      "champion",
      "celebration",
      "victory",
      "competition",
      "tournament",
      "leaderboard",
      "ranking",
      "success",
      "reward",
      "cup",
      "first",
      "gold",
    ],
    aliases: [],
  },
  {
    name: "medal",
    label: "Medal",
    category: "Work",
    tags: ["prize", "sports", "winner", "trophy", "award", "achievement"],
    aliases: [],
  },
  {
    name: "milestone",
    label: "Milestone",
    category: "Work",
    tags: [
      "signpost",
      "direction",
      "right",
      "east",
      "forward",
      "version control",
      "waypoint",
    ],
    aliases: [],
  },
  {
    name: "rocket",
    label: "Rocket",
    category: "Work",
    tags: ["release", "boost", "launch", "space", "version"],
    aliases: [],
  },
  {
    name: "trending-up",
    label: "Trending Up",
    category: "Work",
    tags: ["statistics"],
    aliases: [],
  },
  {
    name: "calculator",
    label: "Calculator",
    category: "Work",
    tags: ["count", "calculating machine"],
    aliases: [],
  },
  {
    name: "receipt",
    label: "Receipt",
    category: "Work",
    tags: [
      "bill",
      "voucher",
      "slip",
      "check",
      "counterfoil",
      "currency",
      "dollar",
      "usd",
      "$",
    ],
    aliases: ["receipts"],
  },
  {
    name: "banknote",
    label: "Banknote",
    category: "Work",
    tags: ["currency", "money", "payment"],
    aliases: [],
  },
  {
    name: "wallet",
    label: "Wallet",
    category: "Work",
    tags: ["money", "finance", "pocket"],
    aliases: [],
  },
  {
    name: "credit-card",
    label: "Credit Card",
    category: "Work",
    tags: ["bank", "purchase", "payment", "cc"],
    aliases: [],
  },
  {
    name: "scale",
    label: "Scale",
    category: "Work",
    tags: [
      "balance",
      "legal",
      "license",
      "right",
      "rule",
      "law",
      "justice",
      "weight",
      "measure",
      "compare",
      "judge",
      "fair",
      "ethics",
      "decision",
    ],
    aliases: [],
  },
  {
    name: "factory",
    label: "Factory",
    category: "Work",
    tags: [
      "building",
      "business",
      "energy",
      "industry",
      "manufacture",
      "sector",
    ],
    aliases: ["businesses"],
  },
  {
    name: "users-round",
    label: "Users Round",
    category: "People",
    tags: ["group", "people"],
    aliases: ["team", "teams", "people", "members", "member", "person", "user"],
  },
  {
    name: "user-round",
    label: "User Round",
    category: "People",
    tags: ["person", "account", "contact"],
    aliases: ["people", "users", "accounts", "contacts"],
  },
  {
    name: "contact",
    label: "Contact",
    category: "People",
    tags: [
      "user",
      "person",
      "family",
      "friend",
      "acquaintance",
      "listing",
      "networking",
    ],
    aliases: ["people", "users", "contacts"],
  },
  {
    name: "id-card",
    label: "Id Card",
    category: "People",
    tags: ["card", "badge", "identity", "authentication", "secure"],
    aliases: [],
  },
  {
    name: "accessibility",
    label: "Accessibility",
    category: "People",
    tags: ["disability", "disabled", "dda", "wheelchair"],
    aliases: [],
  },
  {
    name: "baby",
    label: "Baby",
    category: "People",
    tags: ["child", "childproof", "children"],
    aliases: [],
  },
  {
    name: "person-standing",
    label: "Person Standing",
    category: "People",
    tags: ["people", "human", "accessibility", "stick figure"],
    aliases: ["people"],
  },
  {
    name: "heart-handshake",
    label: "Heart Handshake",
    category: "People",
    tags: [
      "agreement",
      "charity",
      "help",
      "deal",
      "terms",
      "emotion",
      "together",
      "handshake",
    ],
    aliases: ["care", "support"],
  },
  {
    name: "hand-helping",
    label: "Helping Hand",
    category: "People",
    tags: ["agreement", "help", "proposal", "charity", "begging", "terms"],
    aliases: ["helping-hand"],
  },
  {
    name: "graduation-cap",
    label: "Graduation Cap",
    category: "People",
    tags: [
      "school",
      "university",
      "learn",
      "study",
      "mortarboard",
      "education",
      "ceremony",
      "academic",
      "hat",
      "diploma",
      "bachelor's",
      "master's",
      "doctorate",
    ],
    aliases: ["education", "training"],
  },
  {
    name: "stethoscope",
    label: "Stethoscope",
    category: "People",
    tags: ["phonendoscope", "medical", "heart", "lungs", "sound"],
    aliases: [],
  },
  {
    name: "hard-hat",
    label: "Hard Hat",
    category: "People",
    tags: ["helmet", "construction", "safety"],
    aliases: [],
  },
  {
    name: "shield-check",
    label: "Shield Check",
    category: "People",
    tags: [
      "cybersecurity",
      "secured",
      "safety",
      "protection",
      "protected",
      "guardian",
      "guarded",
      "armored",
      "armoured",
      "defense",
      "defence",
      "defended",
      "blocked",
      "threat",
      "prevention",
      "prevented",
      "antivirus",
      "vigilance",
      "vigilant",
      "active",
      "activated",
      "enabled",
      "detection",
      "scanned",
      "found",
      "strength",
      "strong",
      "tough",
      "invincible",
      "invincibility",
      "invulnerable",
      "undamaged",
      "audited",
      "admin",
      "verification",
      "verified",
      "certification",
      "certified",
      "tested",
      "passed",
      "qualified",
      "cleared",
      "cleaned",
      "disinfected",
      "uninfected",
      "task",
      "completed",
      "todo",
      "done",
      "ticked",
      "checked",
      "crest",
      "bravery",
    ],
    aliases: ["tasks"],
  },
  {
    name: "fingerprint-pattern",
    label: "Fingerprint",
    category: "People",
    tags: ["2fa", "authentication", "biometric", "identity", "security"],
    aliases: ["fingerprint"],
  },
  {
    name: "key-round",
    label: "Key Round",
    category: "People",
    tags: ["password", "login", "authentication", "secure", "unlock"],
    aliases: [],
  },
  {
    name: "face-slightly-smiling",
    label: "Smile",
    category: "People",
    tags: [
      "smile",
      "happy",
      "happiness",
      "good",
      "positive",
      "friendly",
      "patronizing",
      "passive aggressive",
      "ironic",
      "emoji",
      "emotion",
    ],
    aliases: ["smile"],
  },
  {
    name: "brain",
    label: "Brain",
    category: "People",
    tags: [
      "medical",
      "mind",
      "mental",
      "intellect",
      "cerebral",
      "consciousness",
      "genius",
      "artificial intelligence",
      "ai",
      "think",
      "thought",
      "insight",
      "intelligent",
      "smart",
    ],
    aliases: [],
  },
  {
    name: "eye",
    label: "Eye",
    category: "People",
    tags: [
      "view",
      "watch",
      "see",
      "show",
      "expose",
      "reveal",
      "display",
      "visible",
      "visibility",
      "vision",
      "preview",
      "read",
    ],
    aliases: [],
  },
  {
    name: "ear",
    label: "Ear",
    category: "People",
    tags: ["hearing", "noise", "audio", "accessibility"],
    aliases: [],
  },
  {
    name: "hand",
    label: "Hand",
    category: "People",
    tags: ["wave", "move", "mouse", "grab"],
    aliases: [],
  },
  {
    name: "message-circle",
    label: "Message Circle",
    category: "Communication",
    tags: [
      "comment",
      "chat",
      "conversation",
      "dialog",
      "feedback",
      "speech bubble",
    ],
    aliases: ["chat", "chats", "message", "messages"],
  },
  {
    name: "messages-square",
    label: "Messages Square",
    category: "Communication",
    tags: [
      "comment",
      "chat",
      "conversation",
      "dialog",
      "feedback",
      "speech bubbles",
      "copy",
      "multiple",
      "discussion",
      "interview",
      "debate",
    ],
    aliases: ["message"],
  },
  {
    name: "mail",
    label: "Mail",
    category: "Communication",
    tags: ["email", "message", "letter", "unread"],
    aliases: ["messages"],
  },
  {
    name: "phone",
    label: "Phone",
    category: "Communication",
    tags: ["call"],
    aliases: ["phones"],
  },
  {
    name: "video",
    label: "Video",
    category: "Communication",
    tags: [
      "camera",
      "movie",
      "film",
      "recording",
      "motion picture",
      "camcorder",
      "reel",
    ],
    aliases: [],
  },
  {
    name: "mic",
    label: "Mic",
    category: "Communication",
    tags: ["record", "sound", "listen", "radio", "podcast", "microphone"],
    aliases: [],
  },
  {
    name: "radio",
    label: "Radio",
    category: "Communication",
    tags: ["signal", "broadcast", "connectivity", "live", "frequency"],
    aliases: [],
  },
  {
    name: "satellite",
    label: "Satellite",
    category: "Communication",
    tags: ["space station", "orbit", "transmitter"],
    aliases: [],
  },
  {
    name: "send",
    label: "Send",
    category: "Communication",
    tags: [
      "email",
      "message",
      "mail",
      "paper airplane",
      "paper aeroplane",
      "submit",
    ],
    aliases: ["messages"],
  },
  {
    name: "inbox",
    label: "Inbox",
    category: "Communication",
    tags: ["email"],
    aliases: [],
  },
  {
    name: "at-sign",
    label: "At Sign",
    category: "Communication",
    tags: ["mention", "at", "email", "message", "@"],
    aliases: ["messages"],
  },
  {
    name: "bell",
    label: "Bell",
    category: "Communication",
    tags: ["alarm", "notification", "sound", "reminder"],
    aliases: [],
  },
  {
    name: "rss",
    label: "Rss",
    category: "Communication",
    tags: [
      "feed",
      "subscribe",
      "news",
      "updates",
      "notifications",
      "content",
      "blog",
      "articles",
      "broadcast",
      "syndication",
      "reader",
      "channels",
      "posts",
      "publishing",
      "digest",
      "alert",
      "following",
      "inbox",
      "newsletter",
      "weblog",
      "podcast",
    ],
    aliases: [],
  },
  {
    name: "mic-signal",
    label: "Podcast",
    category: "Communication",
    tags: [
      "podcast",
      "audio",
      "broadcast",
      "signal",
      "wireless",
      "radio",
      "airwaves",
      "microphone",
      "talk",
      "voice",
      "speech",
      "stream",
      "live",
      "voice chat",
      "push to talk",
      "transmission",
    ],
    aliases: ["podcast"],
  },
  {
    name: "speech",
    label: "Speech",
    category: "Communication",
    tags: [
      "disability",
      "disabled",
      "dda",
      "human",
      "accessibility",
      "people",
      "sound",
    ],
    aliases: ["person"],
  },
  {
    name: "headphones",
    label: "Headphones",
    category: "Communication",
    tags: ["music", "audio", "sound"],
    aliases: [],
  },
  {
    name: "volume-2",
    label: "Volume 2",
    category: "Communication",
    tags: ["music", "sound", "speaker"],
    aliases: ["volume-2"],
  },
  {
    name: "languages",
    label: "Languages",
    category: "Communication",
    tags: ["translate"],
    aliases: [],
  },
  {
    name: "webcam",
    label: "Webcam",
    category: "Communication",
    tags: ["camera", "security"],
    aliases: [],
  },
  {
    name: "antenna",
    label: "Antenna",
    category: "Communication",
    tags: [
      "signal",
      "connection",
      "connectivity",
      "tv",
      "television",
      "broadcast",
      "live",
      "frequency",
      "tune",
      "scan",
      "channels",
      "aerial",
      "receiver",
      "transmission",
      "transducer",
      "terrestrial",
      "satellite",
      "cable",
    ],
    aliases: [],
  },
  {
    name: "file-text",
    label: "File Text",
    category: "Documents",
    tags: ["data", "txt", "pdf", "document"],
    aliases: ["documents", "files"],
  },
  {
    name: "files",
    label: "Files",
    category: "Documents",
    tags: ["multiple", "copy", "documents"],
    aliases: ["document", "file"],
  },
  {
    name: "folder-open",
    label: "Folder Open",
    category: "Documents",
    tags: ["directory"],
    aliases: ["folders"],
  },
  {
    name: "book-open",
    label: "Book Open",
    category: "Documents",
    tags: [
      "reading",
      "pages",
      "booklet",
      "magazine",
      "leaflet",
      "pamphlet",
      "library",
      "writing",
      "written",
      "writer",
      "author",
      "story",
      "script",
      "screenplay",
      "fiction",
      "novel",
      "information",
      "knowledge",
      "education",
      "high school",
      "university",
      "college",
      "academy",
      "student",
      "study",
      "learning",
      "homework",
      "research",
      "documentation",
      "revealed",
      "blank",
      "plain",
    ],
    aliases: ["books"],
  },
  {
    name: "notebook-pen",
    label: "Notebook Pen",
    category: "Documents",
    tags: [
      "pencil",
      "notepad",
      "notes",
      "noted",
      "stationery",
      "sketchbook",
      "organizer",
      "organiser",
      "planner",
      "diary",
      "journal",
      "writing",
      "write",
      "written",
      "reading",
      "high school",
      "university",
      "college",
      "academy",
      "student",
      "study",
      "research",
      "homework",
      "eraser",
      "rubber",
    ],
    aliases: ["note"],
  },
  {
    name: "sticky-note",
    label: "Sticky Note",
    category: "Documents",
    tags: [
      "post-it",
      "comment",
      "annotation",
      "reaction",
      "memo",
      "reminder",
      "todo",
      "task",
      "idea",
      "brainstorm",
      "document",
      "page",
      "paper",
      "sheet",
      "stationary",
      "office",
    ],
    aliases: ["documents", "tasks", "offices", "notes"],
  },
  {
    name: "newspaper",
    label: "Newspaper",
    category: "Documents",
    tags: ["news", "feed", "home", "magazine", "article", "headline"],
    aliases: [],
  },
  {
    name: "clipboard-list",
    label: "Clipboard List",
    category: "Documents",
    tags: ["copy", "paste", "tasks"],
    aliases: ["task"],
  },
  {
    name: "scroll-text",
    label: "Scroll Text",
    category: "Documents",
    tags: [
      "paper",
      "log",
      "scripture",
      "document",
      "notes",
      "parchment",
      "list",
      "long",
      "script",
      "story",
      "code",
      "coding",
    ],
    aliases: ["documents", "note"],
  },
  {
    name: "library-big",
    label: "Library Big",
    category: "Documents",
    tags: [
      "books",
      "reading",
      "written",
      "authors",
      "stories",
      "fiction",
      "novels",
      "information",
      "knowledge",
      "education",
      "high school",
      "university",
      "college",
      "academy",
      "learning",
      "study",
      "research",
      "collection",
      "vinyl",
      "records",
      "albums",
      "music",
      "package",
    ],
    aliases: ["book"],
  },
  {
    name: "bookmark",
    label: "Bookmark",
    category: "Documents",
    tags: [
      "save",
      "favorite",
      "mark",
      "label",
      "attachment",
      "file",
      "stick",
      "pin",
      "read",
      "clip",
      "marker",
      "tag",
    ],
    aliases: ["files", "favourite", "labels", "tags"],
  },
  {
    name: "paperclip",
    label: "Paperclip",
    category: "Documents",
    tags: ["attachment", "file"],
    aliases: ["files"],
  },
  {
    name: "archive",
    label: "Archive",
    category: "Documents",
    tags: ["index", "backup", "box", "storage", "records"],
    aliases: [],
  },
  {
    name: "package",
    label: "Package",
    category: "Documents",
    tags: [
      "box",
      "container",
      "storage",
      "sealed",
      "delivery",
      "undelivered",
      "unopened",
      "packed",
      "archive",
      "zip",
      "module",
    ],
    aliases: [],
  },
  {
    name: "image",
    label: "Image",
    category: "Documents",
    tags: ["picture", "photo"],
    aliases: [],
  },
  {
    name: "film",
    label: "Film",
    category: "Documents",
    tags: ["movie", "video", "reel", "camera", "cinema", "entertainment"],
    aliases: [],
  },
  {
    name: "music",
    label: "Music",
    category: "Documents",
    tags: ["note", "quaver", "eighth note"],
    aliases: ["notes"],
  },
  {
    name: "map",
    label: "Map",
    category: "Documents",
    tags: ["location", "navigation", "travel"],
    aliases: [],
  },
  {
    name: "ticket",
    label: "Ticket",
    category: "Documents",
    tags: [
      "entry",
      "pass",
      "voucher",
      "event",
      "concert",
      "show",
      "perforated",
      "dashed",
    ],
    aliases: [],
  },
  {
    name: "scan-line",
    label: "Scan Line",
    category: "Documents",
    tags: [
      "checkout",
      "till",
      "cart",
      "transaction",
      "purchase",
      "buy",
      "product",
      "packaging",
      "retail",
      "consumer",
      "qr-code",
      "dashed",
    ],
    aliases: [],
  },
  {
    name: "code-xml",
    label: "Code Xml",
    category: "Technology",
    tags: ["source", "programming", "html", "xml"],
    aliases: ["engineering", "developer", "developers", "code"],
  },
  {
    name: "terminal",
    label: "Terminal",
    category: "Technology",
    tags: ["code", "command line", "prompt", "shell"],
    aliases: [],
  },
  {
    name: "bug",
    label: "Bug",
    category: "Technology",
    tags: [
      "issue",
      "error",
      "defect",
      "testing",
      "troubleshoot",
      "problem",
      "report",
      "debug",
      "code",
      "insect",
      "beetle",
    ],
    aliases: ["reports"],
  },
  {
    name: "cpu",
    label: "Cpu",
    category: "Technology",
    tags: [
      "processor",
      "cores",
      "technology",
      "computer",
      "chip",
      "circuit",
      "memory",
      "ram",
      "specs",
      "gigahertz",
      "ghz",
    ],
    aliases: [],
  },
  {
    name: "circuit-board",
    label: "Circuit Board",
    category: "Technology",
    tags: ["computing", "electricity", "electronics"],
    aliases: [],
  },
  {
    name: "database",
    label: "Database",
    category: "Technology",
    tags: ["storage", "memory", "container", "tin", "pot", "bytes", "servers"],
    aliases: ["server"],
  },
  {
    name: "server",
    label: "Server",
    category: "Technology",
    tags: ["cloud", "storage"],
    aliases: ["servers"],
  },
  {
    name: "cloud",
    label: "Cloud",
    category: "Technology",
    tags: ["weather"],
    aliases: ["hosting", "storage"],
  },
  {
    name: "network",
    label: "Network",
    category: "Technology",
    tags: ["tree"],
    aliases: [],
  },
  {
    name: "wifi",
    label: "Wifi",
    category: "Technology",
    tags: ["connection", "signal", "wireless"],
    aliases: [],
  },
  {
    name: "ethernet-port",
    label: "Ethernet Port",
    category: "Technology",
    tags: [
      "internet",
      "network",
      "connection",
      "cable",
      "lan",
      "port",
      "router",
      "switch",
      "hub",
      "modem",
      "web",
      "online",
      "networking",
      "communication",
      "socket",
      "plug",
      "slot",
      "controller",
      "connector",
      "interface",
      "console",
      "signal",
      "data",
      "input",
      "output",
    ],
    aliases: [],
  },
  {
    name: "bluetooth",
    label: "Bluetooth",
    category: "Technology",
    tags: ["wireless"],
    aliases: [],
  },
  {
    name: "usb",
    label: "Usb",
    category: "Technology",
    tags: [
      "universal",
      "serial",
      "bus",
      "controller",
      "connector",
      "interface",
    ],
    aliases: [],
  },
  {
    name: "plug-zap",
    label: "Plug Zap",
    category: "Technology",
    tags: [
      "electricity",
      "energy",
      "electronics",
      "charge",
      "charging",
      "battery",
      "connect",
    ],
    aliases: [],
  },
  {
    name: "battery-charging",
    label: "Battery Charging",
    category: "Technology",
    tags: ["power", "electricity", "energy", "accumulator", "charge"],
    aliases: [],
  },
  {
    name: "monitor",
    label: "Monitor",
    category: "Technology",
    tags: [
      "tv",
      "computer",
      "desktop",
      "screen",
      "display",
      "external display",
      "screen sharing",
      "virtual machine",
      "vm",
    ],
    aliases: [],
  },
  {
    name: "smartphone",
    label: "Smartphone",
    category: "Technology",
    tags: [
      "phone",
      "cellphone",
      "device",
      "mobile",
      "screen",
      "display",
      "touchscreen",
      "portable",
      "responsive",
    ],
    aliases: ["phones", "devices"],
  },
  {
    name: "tablet",
    label: "Tablet",
    category: "Technology",
    tags: [
      "device",
      "mobile",
      "screen",
      "display",
      "touchscreen",
      "portable",
      "responsive",
    ],
    aliases: ["devices"],
  },
  {
    name: "keyboard",
    label: "Keyboard",
    category: "Technology",
    tags: ["layout", "spell", "settings", "mouse"],
    aliases: ["setting"],
  },
  {
    name: "mouse",
    label: "Mouse",
    category: "Technology",
    tags: ["device", "scroll", "click"],
    aliases: ["devices"],
  },
  {
    name: "layers",
    label: "Layers",
    category: "Organisation",
    tags: ["stack", "pile", "pages", "sheets", "paperwork", "copies", "copy"],
    aliases: [],
  },
  {
    name: "list-todo",
    label: "List Todo",
    category: "Organisation",
    tags: [
      "todo",
      "done",
      "check",
      "tick",
      "complete",
      "tasks",
      "items",
      "pending",
    ],
    aliases: ["task"],
  },
  {
    name: "calendar-days",
    label: "Calendar Days",
    category: "Organisation",
    tags: ["date", "month", "year", "event"],
    aliases: ["schedule", "schedules", "meeting", "meetings", "calendars"],
  },
  {
    name: "clock",
    label: "Clock",
    category: "Organisation",
    tags: ["time", "watch", "alarm"],
    aliases: [],
  },
  {
    name: "timer",
    label: "Timer",
    category: "Organisation",
    tags: ["time", "timer", "stopwatch"],
    aliases: [],
  },
  {
    name: "alarm-clock",
    label: "Alarm Clock",
    category: "Organisation",
    tags: ["morning"],
    aliases: [],
  },
  {
    name: "check",
    label: "Check",
    category: "Organisation",
    tags: ["done", "todo", "tick", "complete", "task"],
    aliases: ["tasks"],
  },
  {
    name: "square-check-big",
    label: "Square Check Big",
    category: "Organisation",
    tags: ["done", "todo", "tick", "complete", "task"],
    aliases: ["done", "complete", "completed", "tasks"],
  },
  {
    name: "flag",
    label: "Flag",
    category: "Organisation",
    tags: [
      "report",
      "marker",
      "notification",
      "warning",
      "milestone",
      "goal",
      "notice",
      "signal",
      "attention",
      "banner",
    ],
    aliases: ["goals", "reports", "flags"],
  },
  {
    name: "tag",
    label: "Tag",
    category: "Organisation",
    tags: ["label", "badge", "ticket", "mark"],
    aliases: ["labels", "tags"],
  },
  {
    name: "kanban",
    label: "Kanban",
    category: "Organisation",
    tags: [
      "projects",
      "manage",
      "overview",
      "board",
      "tickets",
      "issues",
      "roadmap",
      "plan",
      "intentions",
      "productivity",
      "work",
      "agile",
      "code",
      "coding",
    ],
    aliases: ["project"],
  },
  {
    name: "search",
    label: "Search",
    category: "Organisation",
    tags: [
      "find",
      "scan",
      "magnifier",
      "magnifying glass",
      "lens",
      "locate",
      "explore",
      "discover",
      "enlarge",
      "zoom",
    ],
    aliases: ["find", "lookup"],
  },
  {
    name: "funnel",
    label: "Filter",
    category: "Organisation",
    tags: ["filter", "hopper"],
    aliases: ["filter"],
  },
  {
    name: "settings-2",
    label: "Settings 2",
    category: "Organisation",
    tags: ["cog", "edit", "gear", "preferences", "slider"],
    aliases: ["setting", "settings", "preferences", "preference", "settings-2"],
  },
  {
    name: "wrench",
    label: "Wrench",
    category: "Organisation",
    tags: [
      "account",
      "settings",
      "spanner",
      "diy",
      "toolbox",
      "build",
      "construction",
    ],
    aliases: ["accounts", "setting"],
  },
  {
    name: "workflow",
    label: "Workflow",
    category: "Organisation",
    tags: [
      "action",
      "continuous integration",
      "ci",
      "automation",
      "devops",
      "network",
      "node",
      "connection",
    ],
    aliases: [],
  },
  {
    name: "git-branch",
    label: "Git Branch",
    category: "Organisation",
    tags: ["code", "version control", "vcs", "repository"],
    aliases: [],
  },
  {
    name: "puzzle",
    label: "Puzzle",
    category: "Organisation",
    tags: ["component", "module", "part", "piece"],
    aliases: [],
  },
  {
    name: "link",
    label: "Link",
    category: "Organisation",
    tags: ["chain", "url"],
    aliases: [],
  },
  {
    name: "split",
    label: "Split",
    category: "Organisation",
    tags: ["break", "disband", "divide", "separate", "branch", "disunite"],
    aliases: [],
  },
  {
    name: "house",
    label: "House",
    category: "Places",
    tags: ["home", "living", "building", "residence", "architecture"],
    aliases: [],
  },
  {
    name: "building-complex",
    label: "Building 2",
    category: "Places",
    tags: [
      "business",
      "company",
      "enterprise",
      "skyscraper",
      "organisation",
      "organization",
      "city",
    ],
    aliases: ["office", "offices", "building-2"],
  },
  {
    name: "store",
    label: "Store",
    category: "Places",
    tags: ["shop", "supermarket", "stand", "boutique", "building"],
    aliases: ["stores"],
  },
  {
    name: "warehouse",
    label: "Warehouse",
    category: "Places",
    tags: [
      "storage",
      "storehouse",
      "depot",
      "depository",
      "repository",
      "stockroom",
      "logistics",
      "building",
    ],
    aliases: [],
  },
  {
    name: "hospital",
    label: "Hospital",
    category: "Places",
    tags: [
      "infirmary",
      "sanatorium",
      "healthcare",
      "doctor",
      "hospice",
      "clinic",
      "emergency room",
      "ward",
      "building",
      "medical",
      "vet",
    ],
    aliases: [],
  },
  {
    name: "school",
    label: "School",
    category: "Places",
    tags: [
      "building",
      "education",
      "childhood",
      "university",
      "learning",
      "campus",
      "scholar",
      "student",
      "lecture",
      "degree",
      "course",
      "academia",
      "study",
      "knowledge",
      "classroom",
      "research",
      "diploma",
      "graduation",
      "professor",
      "tutorial",
      "homework",
      "assignment",
      "exam",
    ],
    aliases: [],
  },
  {
    name: "university",
    label: "University",
    category: "Places",
    tags: [
      "building",
      "education",
      "childhood",
      "school",
      "college",
      "academy",
      "institute",
    ],
    aliases: [],
  },
  {
    name: "church",
    label: "Church",
    category: "Places",
    tags: ["temple", "building"],
    aliases: [],
  },
  {
    name: "landmark",
    label: "Landmark",
    category: "Places",
    tags: [
      "bank",
      "building",
      "capitol",
      "finance",
      "money",
      "museum",
      "art gallery",
      "hall",
      "institute",
      "pediment",
      "portico",
      "doric",
      "columns",
      "pillars",
      "classical",
      "architecture",
      "government",
      "institution",
      "monument",
      "site",
      "history",
      "historic",
      "library",
      "temple",
      "ancient",
      "structure",
    ],
    aliases: [],
  },
  {
    name: "tent",
    label: "Tent",
    category: "Places",
    tags: [
      "tipi",
      "teepee",
      "wigwam",
      "lodge",
      "camping",
      "campsite",
      "holiday",
      "retreat",
      "nomadic",
      "native american",
      "indian",
      "wilderness",
      "outdoors",
    ],
    aliases: [],
  },
  {
    name: "mountain",
    label: "Mountain",
    category: "Places",
    tags: ["climb", "hike", "rock"],
    aliases: [],
  },
  {
    name: "trees",
    label: "Trees",
    category: "Places",
    tags: ["tree", "forest", "park", "nature"],
    aliases: [],
  },
  {
    name: "globe",
    label: "Globe",
    category: "Places",
    tags: ["world", "browser", "language", "translate"],
    aliases: [],
  },
  {
    name: "compass",
    label: "Compass",
    category: "Places",
    tags: ["direction", "north", "east", "south", "west", "browser"],
    aliases: [],
  },
  {
    name: "navigation",
    label: "Navigation",
    category: "Places",
    tags: ["location", "travel"],
    aliases: [],
  },
  {
    name: "map-pin",
    label: "Map Pin",
    category: "Places",
    tags: ["location", "waypoint", "marker", "drop"],
    aliases: [],
  },
  {
    name: "route",
    label: "Route",
    category: "Places",
    tags: ["path", "journey", "planner", "points", "stops", "stations"],
    aliases: [],
  },
  {
    name: "plane",
    label: "Plane",
    category: "Places",
    tags: ["plane", "trip", "airplane"],
    aliases: [],
  },
  {
    name: "train-front",
    label: "Train Front",
    category: "Places",
    tags: [
      "railway",
      "metro",
      "subway",
      "underground",
      "high-speed",
      "bullet",
      "fast",
      "track",
      "line",
    ],
    aliases: [],
  },
  {
    name: "ship",
    label: "Ship",
    category: "Places",
    tags: [
      "boat",
      "knots",
      "nautical mile",
      "maritime",
      "sailing",
      "yacht",
      "cruise",
      "ocean liner",
      "tanker",
      "vessel",
      "navy",
      "trip",
      "releases",
    ],
    aliases: [],
  },
  {
    name: "lightbulb",
    label: "Lightbulb",
    category: "Objects",
    tags: ["idea", "bright", "lights"],
    aliases: [],
  },
  {
    name: "sparkles",
    label: "Sparkles",
    category: "Objects",
    tags: ["stars", "effect", "filter", "night", "magic"],
    aliases: [],
  },
  {
    name: "star",
    label: "Star",
    category: "Objects",
    tags: ["bookmark", "favorite", "like", "review", "rating"],
    aliases: ["favourite"],
  },
  {
    name: "heart",
    label: "Heart",
    category: "Objects",
    tags: ["like", "love", "emotion", "suit", "playing", "cards"],
    aliases: ["favourite", "favorite", "favourites", "favorites"],
  },
  {
    name: "flame",
    label: "Flame",
    category: "Objects",
    tags: [
      "heat",
      "burn",
      "light",
      "glow",
      "ignite",
      "passion",
      "ember",
      "fire",
      "lit",
      "burning",
      "spark",
      "embers",
      "smoke",
      "firefighter",
      "fireman",
      "department",
      "brigade",
      "station",
      "emergency",
    ],
    aliases: [],
  },
  {
    name: "zap",
    label: "Zap",
    category: "Objects",
    tags: [
      "flash",
      "camera",
      "lightning",
      "electricity",
      "energy",
      "power",
      "quick",
    ],
    aliases: [],
  },
  {
    name: "sun",
    label: "Sun",
    category: "Objects",
    tags: ["brightness", "weather", "light", "summer"],
    aliases: [],
  },
  {
    name: "moon",
    label: "Moon",
    category: "Objects",
    tags: ["dark", "night"],
    aliases: [],
  },
  {
    name: "umbrella",
    label: "Umbrella",
    category: "Objects",
    tags: ["rain", "weather"],
    aliases: [],
  },
  {
    name: "coffee",
    label: "Coffee",
    category: "Objects",
    tags: ["drink", "cup", "mug", "tea", "cafe", "hot", "beverage"],
    aliases: [],
  },
  {
    name: "apple",
    label: "Apple",
    category: "Objects",
    tags: [
      "fruit",
      "food",
      "healthy",
      "snack",
      "nutrition",
      "fresh",
      "produce",
      "grocery",
      "organic",
      "harvest",
      "vitamin",
      "red",
      "green",
      "juicy",
      "sweet",
      "tart",
      "bite",
      "orchard",
      "plant",
      "core",
      "raw",
      "diet",
    ],
    aliases: [],
  },
  {
    name: "leaf",
    label: "Leaf",
    category: "Objects",
    tags: ["sustainability", "nature", "energy", "plant", "autumn"],
    aliases: [],
  },
  {
    name: "flower-2",
    label: "Flower 2",
    category: "Objects",
    tags: ["sustainability", "nature", "plant"],
    aliases: ["flower-2"],
  },
  {
    name: "paw-print",
    label: "Paw Print",
    category: "Objects",
    tags: [
      "pets",
      "vets",
      "veterinarian",
      "domesticated",
      "cat",
      "dog",
      "bear",
    ],
    aliases: [],
  },
  {
    name: "gem",
    label: "Gem",
    category: "Objects",
    tags: [
      "diamond",
      "crystal",
      "ruby",
      "jewellery",
      "price",
      "special",
      "present",
      "gift",
      "ring",
      "wedding",
      "proposal",
      "marriage",
      "rubygems",
    ],
    aliases: [],
  },
  {
    name: "gift",
    label: "Gift",
    category: "Objects",
    tags: ["present", "box", "birthday", "party"],
    aliases: [],
  },
  {
    name: "shopping-cart",
    label: "Shopping Cart",
    category: "Objects",
    tags: [
      "trolley",
      "cart",
      "basket",
      "e-commerce",
      "store",
      "purchase",
      "products",
      "items",
      "ingredients",
    ],
    aliases: ["stores"],
  },
  {
    name: "shopping-bag",
    label: "Shopping Bag",
    category: "Objects",
    tags: ["ecommerce", "cart", "purchase", "store"],
    aliases: ["stores"],
  },
  {
    name: "camera",
    label: "Camera",
    category: "Objects",
    tags: [
      "photography",
      "lens",
      "focus",
      "capture",
      "shot",
      "visual",
      "image",
      "device",
      "equipment",
      "photo",
      "webcam",
      "video",
    ],
    aliases: ["devices"],
  },
  {
    name: "palette",
    label: "Palette",
    category: "Objects",
    tags: [
      "colors",
      "colours",
      "theme",
      "scheme",
      "paint",
      "watercolor",
      "watercolour",
      "artist",
    ],
    aliases: ["colour", "color", "colours", "colors", "design"],
  },
] as const;
/** A stable canonical Lucide identifier in the curated catalogue. */
export type IconName = (typeof ICON_CATALOGUE)[number]["name"];
/** A stored identity glyph, independent of its hue. */
export type IconValue =
  { kind: "icon"; name: IconName } | { kind: "emoji"; char: string };
const names: ReadonlySet<string> = new Set(
  ICON_CATALOGUE.map((entry) => entry.name),
);
/** Whether a string is an available canonical icon name. */
export function isIconName(value: string): value is IconName {
  return names.has(value);
}
