// @vegastack icon-arrow-big-left@0.23.123 sha256-F44K9eeFNFeqclaN85Dwp7z4mWk/paX8dj0d7L/HLRA=

// Mirrored from lucide-animated (https://lucide-animated.com/r/arrow-big-left.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { d: "M18 15h-6v4l-7-7 7-7v4h6v6z", translateX: 0 }, animate: { d: "M18 15h-6v4l-7-7 7-7v4h6v6z", translateX: [0, -3, 0], transition: { duration: 0.4 } } };

export type ArrowBigLeftIconHandle = AnimatedIconHandle;

export const ArrowBigLeftIcon = createAnimatedIcon({ name: "ArrowBigLeftIcon", elements: [{ tag: "motion.path", d: "M18 15h-6v4l-7-7 7-7v4h6v6z", variants: PATH_VARIANTS }] });
