// @vegastack icon-battery-low@0.6.0 sha256-pj+N9y8ObcqYhjUcZK/BtHp9eL8Gu24Gr6YlLyy8YZQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/battery-low.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const LINE_VARIANTS: Variants = {
  initial: { opacity: 1 },
  fadeOut: { opacity: 0, transition: { duration: 0.4, ease: "easeInOut" } },
  fadeIn: (i: number) => ({ opacity: 1, transition: { duration: 0.6, delay: i * 0.4, ease: "easeInOut" } }),
};

export type BatteryLowIconHandle = AnimatedIconHandle;

export const BatteryLowIcon = createAnimatedIcon({
  name: "BatteryLowIcon",
  svg: { tag: "motion.svg", inherit: true },
  elements: [
    { tag: "rect", height: "10", rx: "2", ry: "2", width: "16", x: "2", y: "7" },
    { tag: "line", x1: "22", x2: "22", y1: "11", y2: "13" },
    { tag: "motion.line", x1: "6", x2: "6", y1: "11", y2: "13", variants: LINE_VARIANTS, initial: "initial", custom: 0 },
  ],
  start: async ({ control, run }) => {
    await run(control(), "fadeOut");
    run(control(), "fadeIn");
  },
  stop: ({ control, reset }) => {
    reset(control(), "initial");
  },
});
