// @vegastack icon-bluetooth-off@0.7.0 sha256-6pxrnQOMBmonRvp0/rGdeYj+rpR0PnOn9s/Qb/Ie29s=

// Mirrored from lucide-animated (https://lucide-animated.com/r/bluetooth-off.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1, pathOffset: 0 }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } };

const OFFLINE_VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1 }, animate: { pathLength: [0, 1], opacity: [0, 1] } };

export type BluetoothOffIconHandle = AnimatedIconHandle;

export const BluetoothOffIcon = createAnimatedIcon({
  name: "BluetoothOffIcon",
  elements: [
    { tag: "motion.path", d: "m17 17-5 5V12l-5 5", variants: PATH_VARIANTS, transition: { duration: 0.3 } },
    { tag: "motion.path", d: "m2 2 20 20", variants: OFFLINE_VARIANTS, transition: { duration: 0.2, delay: 0.3 } },
    { tag: "motion.path", d: "M14.5 9.5 17 7l-5-5v4.5", variants: PATH_VARIANTS, transition: { duration: 0.3 } },
  ],
});
