// @vegastack icon-bookmark@0.7.0 sha256-k14I6C0kRNlHXuZ4UZWkIKvSKa+aohEIMHUjJfwJL9I=

// Mirrored from lucide-animated (https://lucide-animated.com/r/bookmark.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const BOOKMARK_VARIANTS: Variants = { normal: { scaleY: 1, scaleX: 1 }, animate: { scaleY: [1, 1.3, 0.9, 1.05, 1], scaleX: [1, 0.9, 1.1, 0.95, 1], transition: { duration: 0.6, ease: "easeOut" } } };

export type BookmarkIconHandle = AnimatedIconHandle;

export const BookmarkIcon = createAnimatedIcon({
  name: "BookmarkIcon",
  elements: [{ tag: "motion.path", d: "m19 21-7-4-7 4V5a2 2 0 0 1 2-2h10a2 2 0 0 1 2 2v16z", variants: BOOKMARK_VARIANTS, style: { originY: 0.5, originX: 0.5 } }],
});
