// @vegastack icon-chevron-down@0.11.0 sha256-NnS085Z6y+hUkEAO6n5ZMWkW6tTi/e3IoiOWpte/W4s=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chevron-down.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type ChevronDownIconHandle = AnimatedIconHandle;

export const ChevronDownIcon = createAnimatedIcon({
  name: "ChevronDownIcon",
  elements: [{ tag: "motion.path", d: "m6 9 6 6 6-6", variants: { normal: { y: 0 }, animate: { y: [0, 2, 0] } }, transition: DEFAULT_TRANSITION }],
});
