// @vegastack icon-chevrons-up-down@0.23.39 sha256-UAXy5m2a26RyNbf+74cD94J0KKHAQo8pgH355bku6Hw=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chevrons-up-down.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 250, damping: 25 };

export type ChevronsUpDownIconHandle = AnimatedIconHandle;

export const ChevronsUpDownIcon = createAnimatedIcon({
  name: "ChevronsUpDownIcon",
  elements: [
    { tag: "motion.path", d: "m7 15 5 5 5-5", variants: { normal: { translateY: "0%" }, animate: { translateY: "2px" } }, initial: "normal", transition: DEFAULT_TRANSITION },
    { tag: "motion.path", d: "m7 9 5-5 5 5", variants: { normal: { translateY: "0%" }, animate: { translateY: "-2px" } }, initial: "normal", transition: DEFAULT_TRANSITION },
  ],
});
