// @vegastack icon-chevron-left@0.6.0 sha256-/IA4qEnrgr+ShSJLO9w+IWUGPGV2OAGCdI8Z1NDErGw=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chevron-left.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type ChevronLeftIconHandle = AnimatedIconHandle;

export const ChevronLeftIcon = createAnimatedIcon({
  name: "ChevronLeftIcon",
  elements: [{ tag: "motion.path", d: "m15 18-6-6 6-6", variants: { normal: { x: 0 }, animate: { x: [0, -2, 0] } }, transition: DEFAULT_TRANSITION }],
});
