// @vegastack icon-chrome@0.6.0 sha256-xjtp8wDyZTOzq/hhj0RqSFDU/qhIE245ZtzFI2WNq4A=

// Mirrored from lucide-animated (https://lucide-animated.com/r/chrome.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const TRANSITION: Transition = { duration: 0.3, opacity: { delay: 0.15 } };

const VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1 }, animate: (custom: number) => ({ pathLength: [0, 1], opacity: [0, 1], transition: { ...TRANSITION, delay: 0.1 * custom } }) };

export type ChromeIconHandle = AnimatedIconHandle;

export const ChromeIcon = createAnimatedIcon({
  name: "ChromeIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    { tag: "motion.circle", cx: "12", cy: "12", r: "4", variants: VARIANTS, custom: 0 },
    { tag: "motion.line", x1: "21.17", x2: "12", y1: "8", y2: "8", variants: VARIANTS, custom: 3 },
    { tag: "motion.line", x1: "3.95", x2: "8.54", y1: "6.06", y2: "14", variants: VARIANTS, custom: 3 },
    { tag: "motion.line", x1: "10.88", x2: "15.46", y1: "21.94", y2: "14", variants: VARIANTS, custom: 3 },
  ],
});
