// @vegastack icon-cigarette-off@0.7.5 sha256-HLzVk5ZLXgbBwdPTtaCHynHt9qf+RuvJVkdrj0a2UVo=

// Mirrored from lucide-animated (https://lucide-animated.com/r/cigarette-off.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CIGARETTE_VARIANTS: Variants = {
  normal: { y: 0, opacity: 1 },
  animate: (custom: number) => ({ y: -3, opacity: [0, 1, 0], transition: { repeat: 1, duration: 1.5, ease: "easeInOut", delay: 0.2 * custom } }),
};

const PATH_VARIANTS: Variants = { normal: { pathLength: 1 }, animate: { pathLength: [0, 1], transition: { duration: 0.4, ease: "linear" } } };

export type CigaretteOffIconHandle = AnimatedIconHandle;

export const CigaretteOffIcon = createAnimatedIcon({
  name: "CigaretteOffIcon",
  svg: { tag: "motion.svg", style: { overflow: "visible" }, inherit: true },
  elements: [
    "M12 12H3a1 1 0 0 0-1 1v2a1 1 0 0 0 1 1h13",
    { tag: "motion.path", d: "M18 8c0-2.5-2-2.5-2-5", variants: CIGARETTE_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "m2 2 20 20", variants: PATH_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M21 12a1 1 0 0 1 1 1v2a1 1 0 0 1-.5.866", inherit: true },
    { tag: "motion.path", d: "M22 8c0-2.5-2-2.5-2-5", variants: CIGARETTE_VARIANTS, initial: "normal" },
    "M7 12v4",
  ],
});
