// @vegastack icon-circle-chevron-down@0.7.0 sha256-d6izXj7v3iIMrPKMLQibU8u1oy2EAC5pDwe0JTa2r78=

// Mirrored from lucide-animated (https://lucide-animated.com/r/circle-chevron-down.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type CircleChevronDownIconHandle = AnimatedIconHandle;

export const CircleChevronDownIcon = createAnimatedIcon({
  name: "CircleChevronDownIcon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    { tag: "motion.path", d: "m16 10-4 4-4-4", variants: { normal: { y: 0 }, animate: { y: [0, 2, 0] } }, transition: DEFAULT_TRANSITION },
  ],
});
