// @vegastack icon-cloud-backup@0.7.3 sha256-BHpjcb4bkjQPYCtdEwhplxCbgS1t/IgiswWKCuIbPk8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/cloud-backup.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const BACKUP_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: -360 } };

const BACKUP_TRANSITION: Transition = { duration: 0.8, ease: "easeInOut" };

export type CloudBackupIconHandle = AnimatedIconHandle;

export const CloudBackupIcon = createAnimatedIcon({
  name: "CloudBackupIcon",
  elements: [
    "M21 15.251A4.5 4.5 0 0 0 17.5 8h-1.79A7 7 0 1 0 3 13.607",
    {
      tag: "motion.g",
      variants: BACKUP_VARIANTS,
      initial: "normal",
      transition: BACKUP_TRANSITION,
      children: ["M7 11v4h4", "M8 19a5 5 0 0 0 9-3 4.5 4.5 0 0 0-4.5-4.5 4.82 4.82 0 0 0-3.41 1.41L7 15"],
    },
  ],
});
