// @vegastack icon-cloud-snow@0.6.0 sha256-WkHtd4w3csE3FicM0//3MJ8Eku9YsYOPDNrEqOrBl5c=

// Mirrored from lucide-animated (https://lucide-animated.com/r/cloud-snow.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SNOWFLAKE_VARIANTS: Variants = { animate: { transition: { staggerChildren: 0.3 } } };

export type CloudSnowIconHandle = AnimatedIconHandle;

export const CloudSnowIcon = createAnimatedIcon({
  name: "CloudSnowIcon",
  elements: [
    "M4 14.899A7 7 0 1 1 15.71 8h1.79a4.5 4.5 0 0 1 2.5 8.242",
    {
      tag: "motion.g",
      variants: SNOWFLAKE_VARIANTS,
      initial: "normal",
      children: [
        { tag: "motion.path", d: "M8 15h.01", variants: { normal: { opacity: 1 }, animate: { opacity: [1, 0.3, 1], transition: { duration: 1.5, repeat: 1, ease: "easeInOut" } } }, inherit: true },
        { tag: "motion.path", d: "M8 19h.01", variants: { normal: { opacity: 1 }, animate: { opacity: [1, 0.3, 1], transition: { duration: 1.5, repeat: 1, ease: "easeInOut" } } }, inherit: true },
        { tag: "motion.path", d: "M12 17h.01", variants: { normal: { opacity: 1 }, animate: { opacity: [1, 0.3, 1], transition: { duration: 1.5, repeat: 1, ease: "easeInOut" } } }, inherit: true },
        { tag: "motion.path", d: "M12 21h.01", variants: { normal: { opacity: 1 }, animate: { opacity: [1, 0.3, 1], transition: { duration: 1.5, repeat: 1, ease: "easeInOut" } } }, inherit: true },
        { tag: "motion.path", d: "M16 15h.01", variants: { normal: { opacity: 1 }, animate: { opacity: [1, 0.3, 1], transition: { duration: 1.5, repeat: 1, ease: "easeInOut" } } }, inherit: true },
        { tag: "motion.path", d: "M16 19h.01", variants: { normal: { opacity: 1 }, animate: { opacity: [1, 0.3, 1], transition: { duration: 1.5, repeat: 1, ease: "easeInOut" } } }, inherit: true },
      ],
    },
  ],
});
