// @vegastack icon-corner-up-right@0.23.25 sha256-948y8xI4Nto36TKEHgWL872UjhQkt9sp6r7z9mO5UkQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/corner-up-right.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const STRETCH_VARIANTS: Variants = { normal: { scaleX: 1, x: 0, opacity: 1 }, animate: { scaleX: [1, 1.15, 1], x: [0, 2, 0], transition: { duration: 0.45, ease: "easeInOut" } } };

export type CornerUpRightIconHandle = AnimatedIconHandle;

export const CornerUpRightIcon = createAnimatedIcon({
  name: "CornerUpRightIcon",
  svg: { tag: "motion.svg", variants: STRETCH_VARIANTS, initial: "normal" },
  elements: ["m15 14 5-5-5-5", "M4 20v-7a4 4 0 0 1 4-4h12"],
});
