// @vegastack icon-corner-left-down@0.8.2 sha256-6PEz/pR0S4973ZCdw7cxLywN2R8kS7+dZhgcCy/YhnU=

// Mirrored from lucide-animated (https://lucide-animated.com/r/corner-left-down.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const STRETCH_VARIANTS: Variants = { normal: { scaleY: 1, y: 0, opacity: 1 }, animate: { scaleY: [1, 1.15, 1], y: [0, 2, 0], transition: { duration: 0.45, ease: "easeInOut" } } };

export type CornerLeftDownIconHandle = AnimatedIconHandle;

export const CornerLeftDownIcon = createAnimatedIcon({
  name: "CornerLeftDownIcon",
  svg: { tag: "motion.svg", variants: STRETCH_VARIANTS, initial: "normal" },
  elements: ["m14 15-5 5-5-5", "M20 4h-7a4 4 0 0 0-4 4v12"],
});
