// @vegastack icon-credit-card@0.7.4 sha256-f7Q9BwjvBgXju4HTmrnqwcRErUzGSp3oq5lSVd0bRj8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/credit-card.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CARD_VARIANTS: Variants = {
  normal: { x: 0, transition: { type: "spring", stiffness: 280, damping: 18 } },
  animate: { x: [0, -4, 1.5, 0], transition: { duration: 0.7, times: [0, 0.4, 0.75, 1], ease: "easeInOut" } },
};

export type CreditCardIconHandle = AnimatedIconHandle;

export const CreditCardIcon = createAnimatedIcon({
  name: "CreditCardIcon",
  svg: { className: "overflow-visible" },
  elements: [
    {
      tag: "motion.g",
      variants: CARD_VARIANTS,
      initial: "normal",
      children: [
        { tag: "rect", height: "14", rx: "2", width: "20", x: "2", y: "5" },
        { tag: "line", x1: "2", x2: "22", y1: "10", y2: "10" },
      ],
    },
  ],
});
