// @vegastack icon-cup-soda@0.6.0 sha256-z74etBdU5Tz9PYWcFIWt3kF6vZTtLzsvmgro2Ymvwb0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/cup-soda.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const STRAW_VARIANTS: Variants = {
  normal: { y: 0, scaleY: 1, transition: { duration: 0.25, ease: "easeOut" } },
  animate: { y: [0, -0.85, 0.15, 0], scaleY: [1, 1.06, 0.99, 1], transition: { duration: 0.5, ease: [0.34, 1.56, 0.64, 1], times: [0, 0.35, 0.65, 1] } },
};

const WAVE_VARIANTS: Variants = { normal: { y: 0, transition: { duration: 0.25, ease: "easeOut" } }, animate: { y: [0, -1, 0], transition: { duration: 1.8, repeat: 1, ease: "easeInOut" } } };

const BUBBLE_VARIANTS: Variants = {
  normal: { opacity: 0, y: 0, scale: 1 },
  animate: (delay: number) => ({
    opacity: [0, 0.9, 0.4, 0],
    y: [0, -3, -10, -14],
    scale: [1, 1, 0.85, 0.6],
    transition: { duration: 1.5, ease: "easeIn", delay, repeat: 1, repeatDelay: 0, times: [0, 0.08, 0.7, 1] },
  }),
};

export type CupSodaIconHandle = AnimatedIconHandle;

export const CupSodaIcon = createAnimatedIcon({
  name: "CupSodaIcon",
  elements: [
    "m6 8 1.75 12.28a2 2 0 0 0 2 1.72h4.54a2 2 0 0 0 2-1.72L18 8",
    "M5 8h14",
    { tag: "motion.path", d: "M7 15a6.47 6.47 0 0 1 5 0 6.47 6.47 0 0 0 5 0", variants: WAVE_VARIANTS },
    { tag: "motion.path", d: "m12 8 1-6h2", variants: STRAW_VARIANTS, style: { transformBox: "fill-box", originX: "50%", originY: "100%" } },
    {
      tag: "motion.circle",
      cx: 8.25,
      cy: 20.5,
      fill: "currentColor",
      r: 0.75,
      stroke: "none",
      variants: BUBBLE_VARIANTS,
      initial: "normal",
      style: { transformBox: "fill-box", originX: "50%", originY: "50%" },
      custom: 0,
    },
    {
      tag: "motion.circle",
      cx: 11.25,
      cy: 19.5,
      fill: "currentColor",
      r: 0.6,
      stroke: "none",
      variants: BUBBLE_VARIANTS,
      initial: "normal",
      style: { transformBox: "fill-box", originX: "50%", originY: "50%" },
      custom: 0.35,
    },
    {
      tag: "motion.circle",
      cx: 14,
      cy: 20.75,
      fill: "currentColor",
      r: 0.6,
      stroke: "none",
      variants: BUBBLE_VARIANTS,
      initial: "normal",
      style: { transformBox: "fill-box", originX: "50%", originY: "50%" },
      custom: 0.7,
    },
    {
      tag: "motion.circle",
      cx: 9.75,
      cy: 19,
      fill: "currentColor",
      r: 0.75,
      stroke: "none",
      variants: BUBBLE_VARIANTS,
      initial: "normal",
      style: { transformBox: "fill-box", originX: "50%", originY: "50%" },
      custom: 1.05,
    },
    {
      tag: "motion.circle",
      cx: 12.5,
      cy: 20,
      fill: "currentColor",
      r: 0.45,
      stroke: "none",
      variants: BUBBLE_VARIANTS,
      initial: "normal",
      style: { transformBox: "fill-box", originX: "50%", originY: "50%" },
      custom: 0.55,
    },
  ],
});
