// @vegastack icon-disc-3@0.7.4 sha256-lkP0GHRXCw20HqEOVeMYCx7fVTBYFVDhdgspBMRLwr0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/disc-3.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type Disc3IconHandle = AnimatedIconHandle;

export const Disc3Icon = createAnimatedIcon({
  name: "Disc3Icon",
  elements: [
    { tag: "circle", cx: "12", cy: "12", r: "10" },
    { tag: "circle", cx: "12", cy: "12", r: "2" },
    {
      tag: "motion.g",
      variants: { normal: { rotate: 0 }, animate: { rotate: 90 } },
      transition: { duration: 0.4, ease: "easeInOut" },
      style: { transformOrigin: "12px 12px" },
      children: ["M6 12c0-1.7.7-3.2 1.8-4.2", "M18 12c0 1.7-.7 3.2-1.8 4.2"],
    },
  ],
});
