// @vegastack icon-earth@0.7.5 sha256-zLyn8FTEPdyVKThjsi6qujikt3jTRuY5qWbVzBR1qt0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/earth.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CIRCLE_TRANSITION: Transition = { duration: 0.3, delay: 0.1, opacity: { delay: 0.15 } };

const CIRCLE_VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1 }, animate: { pathLength: [0, 1], opacity: [0, 1] } };

export type EarthIconHandle = AnimatedIconHandle;

export const EarthIcon = createAnimatedIcon({
  name: "EarthIcon",
  elements: [
    {
      tag: "motion.path",
      d: "M21.54 15H17a2 2 0 0 0-2 2v4.54",
      variants: { normal: { pathLength: 1, opacity: 1, pathOffset: 0 }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } },
      transition: { duration: 0.7, delay: 0.5, opacity: { delay: 0.5 } },
    },
    {
      tag: "motion.path",
      d: "M7 3.34V5a3 3 0 0 0 3 3a2 2 0 0 1 2 2c0 1.1.9 2 2 2a2 2 0 0 0 2-2c0-1.1.9-2 2-2h3.17",
      variants: { normal: { pathLength: 1, opacity: 1, pathOffset: 0 }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } },
      transition: { duration: 0.7, delay: 0.5, opacity: { delay: 0.5 } },
    },
    {
      tag: "motion.path",
      d: "M11 21.95V18a2 2 0 0 0-2-2a2 2 0 0 1-2-2v-1a2 2 0 0 0-2-2H2.05",
      variants: { normal: { pathLength: 1, opacity: 1, pathOffset: 0 }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } },
      transition: { duration: 0.7, delay: 0.5, opacity: { delay: 0.5 } },
    },
    { tag: "motion.circle", cx: "12", cy: "12", r: "10", variants: CIRCLE_VARIANTS, transition: CIRCLE_TRANSITION },
  ],
});
