// @vegastack icon-ev-charger@0.7.1 sha256-CMC37YNqcDpVZ5/FRQS917cdwqXz7Hd0D/gpbTd5JIA=

// Mirrored from lucide-animated (https://lucide-animated.com/r/ev-charger.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const EV_CHARGER_VARIANT: Variants = { normal: { opacity: 1 }, animate: { opacity: [1, 0.4, 1], transition: { duration: 1, repeat: 1, ease: "easeInOut" } } };

export type EvChargerIconHandle = AnimatedIconHandle;

export const EvChargerIcon = createAnimatedIcon({
  name: "EvChargerIcon",
  elements: [
    "M14 13h2a2 2 0 0 1 2 2v2a2 2 0 0 0 4 0v-6.998a2 2 0 0 0-.59-1.42L18 5",
    "M14 21V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v16",
    "M2 21h13",
    "M3 7h11",
    { tag: "motion.path", d: "m9 11-2 3h3l-2 3", variants: EV_CHARGER_VARIANT, initial: "normal" },
  ],
});
