// @vegastack icon-expand@0.8.1 sha256-yXvi5cdZaWwYsADHrJk/2T1UWopS3mSjkXwtKP1AKTA=

// Mirrored from lucide-animated (https://lucide-animated.com/r/expand.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 250, damping: 25 };

export type ExpandIconHandle = AnimatedIconHandle;

export const ExpandIcon = createAnimatedIcon({
  name: "ExpandIcon",
  elements: [
    {
      tag: "motion.path",
      d: "m21 21-6-6m6 6v-4.8m0 4.8h-4.8",
      variants: { normal: { translateX: "0%", translateY: "0%" }, animate: { translateX: "2px", translateY: "2px" } },
      transition: DEFAULT_TRANSITION,
    },
    {
      tag: "motion.path",
      d: "M3 16.2V21m0 0h4.8M3 21l6-6",
      variants: { normal: { translateX: "0%", translateY: "0%" }, animate: { translateX: "-2px", translateY: "2px" } },
      transition: DEFAULT_TRANSITION,
    },
    {
      tag: "motion.path",
      d: "M21 7.8V3m0 0h-4.8M21 3l-6 6",
      variants: { normal: { translateX: "0%", translateY: "0%" }, animate: { translateX: "2px", translateY: "-2px" } },
      transition: DEFAULT_TRANSITION,
    },
    {
      tag: "motion.path",
      d: "M3 7.8V3m0 0h4.8M3 3l6 6",
      variants: { normal: { translateX: "0%", translateY: "0%" }, animate: { translateX: "-2px", translateY: "-2px" } },
      transition: DEFAULT_TRANSITION,
    },
  ],
});
