// @vegastack icon-fish-symbol@0.7.2 sha256-f40mRwLKu5ROw1RcQ+RPu/3NcZJn8en8+5Q/R4vyLQY=

// Mirrored from lucide-animated (https://lucide-animated.com/r/fish-symbol.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1 }, animate: { pathLength: [0, 1], opacity: [0, 1], transition: { delay: 0.15, opacity: { delay: 0.1 } } } };

export type FishSymbolIconHandle = AnimatedIconHandle;

export const FishSymbolIcon = createAnimatedIcon({ name: "FishSymbolIcon", elements: [{ tag: "motion.path", d: "M2 16s9-15 20-4C11 23 2 8 2 8", variants: VARIANTS }] });
