// @vegastack icon-folder-git-2@0.7.5 sha256-HndjSSLftp8FVRVlMI+zojRTjxWBgQ5ex88ZzBqj7yk=

// Mirrored from lucide-animated (https://lucide-animated.com/r/folder-git-2.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DURATION = 0.3;

const CALCULATE_DELAY = (i: number) => {
  if (i === 0) return 0.1;

  return i * DURATION + 0.1;
};

export type FolderGit2IconHandle = AnimatedIconHandle;

export const FolderGit2Icon = createAnimatedIcon({
  name: "FolderGit2Icon",
  elements: [
    "M9 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v5",
    {
      tag: "motion.circle",
      cx: "13",
      cy: "12",
      r: "2",
      variants: { normal: { pathLength: 1, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(0), opacity: { delay: CALCULATE_DELAY(0) } },
    },
    {
      tag: "motion.path",
      d: "M18 19c-2.8 0-5-2.2-5-5v8",
      variants: { normal: { pathLength: 1, pathOffset: 0, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(1), opacity: { delay: CALCULATE_DELAY(1) } },
    },
    {
      tag: "motion.circle",
      cx: "20",
      cy: "19",
      r: "2",
      variants: { normal: { pathLength: 1, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(2), opacity: { delay: CALCULATE_DELAY(2) } },
    },
  ],
});
