// @vegastack icon-folder-output@0.7.0 sha256-BL2Kr6CE+ByuUvd6pXnvqZvMvYtFyoFcCb1Kt05M79I=

// Mirrored from lucide-animated (https://lucide-animated.com/r/folder-output.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const ARROW_VARIANTS: Variants = { normal: { x: 0 }, animate: { x: [0, -2, 0] } };

const ARROW_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type FolderOutputIconHandle = AnimatedIconHandle;

export const FolderOutputIcon = createAnimatedIcon({
  name: "FolderOutputIcon",
  elements: [
    "M2 7.5V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2H4a2 2 0 0 1-2-1.5",
    { tag: "motion.g", variants: ARROW_VARIANTS, initial: "normal", transition: ARROW_TRANSITION, children: ["M2 13h10", "m5 10-3 3 3 3"] },
  ],
});
