// @vegastack icon-frown@0.2.0 sha256-hu0DVqx6q8FMcZZ/CrauaFJuaNr3JOlmeFwA9jp03D0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/frown.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface FrownIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface FrownIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<FrownIconHandle>;
}

const FrownIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: FrownIconProps) => {
  const controls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = () => runAnimation(controls, "animate");
  const stopAnimation = () => resetAnimation(controls, "normal");
  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  const faceVariants: Variants = {
    normal: {
      scale: 1,
      rotate: 0,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      scale: [1, 1.15, 1.05, 1.08],
      rotate: [0, -2, 2, 0],
      transition: {
        duration: 0.8,
        times: [0, 0.3, 0.6, 1],
        ease: "easeInOut",
      },
    },
  };

  const mouthVariants: Variants = {
    normal: {
      d: "M16 16s-1.5-2-4-2-4 2-4 2",
      pathLength: 1,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      d: "M16 17s-1.5-2.5-4-2.5-4 2.5-4 2.5",
      pathLength: [0.3, 1, 1],
      transition: {
        d: { duration: 0.5, ease: "easeOut" },
        pathLength: {
          duration: 0.5,
          times: [0, 0.5, 1],
          ease: "easeInOut",
        },
        delay: 0.1,
      },
    },
  };

  const leftEyeVariants: Variants = {
    normal: {
      scale: 1,
      y: 0,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      scale: [1, 1.3, 0.9, 1.1],
      y: [0, -0.5, 0.3, 0],
      transition: {
        duration: 0.6,
        times: [0, 0.3, 0.6, 1],
        ease: "easeInOut",
      },
    },
  };

  const rightEyeVariants: Variants = {
    normal: {
      scale: 1,
      y: 0,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      scale: [1, 0.9, 1.3, 1.1],
      y: [0, -0.5, 0.3, 0],
      transition: {
        duration: 0.6,
        times: [0, 0.3, 0.6, 1],
        ease: "easeInOut",
      },
    },
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <motion.svg
        animate={controls}
        fill="none"
        height={size}
        initial="normal"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        variants={faceVariants}
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <circle cx="12" cy="12" r="10" />
        <motion.path
          animate={controls}
          d="M16 16s-1.5-2-4-2-4 2-4 2"
          initial="normal"
          variants={mouthVariants}
        />
        <motion.line
          animate={controls}
          initial="normal"
          variants={leftEyeVariants}
          x1="9"
          x2="9.01"
          y1="9"
          y2="9"
        />
        <motion.line
          animate={controls}
          initial="normal"
          variants={rightEyeVariants}
          x1="15"
          x2="15.01"
          y1="9"
          y2="9"
        />
      </motion.svg>
    </div>
  );
};

FrownIcon.displayName = "FrownIcon";

export { FrownIcon };
