// @vegastack icon-git-compare@0.7.5 sha256-avbKGrjTIeXkcWG39MNepD2I0uGCXSrQp4fdTWMpQz8=

// Mirrored from lucide-animated (https://lucide-animated.com/r/git-compare.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DURATION = 0.3;

const CALCULATE_DELAY = (i: number) => {
  if (i === 0) return 0.1;

  return i * DURATION + 0.1;
};

export type GitCompareIconHandle = AnimatedIconHandle;

export const GitCompareIcon = createAnimatedIcon({
  name: "GitCompareIcon",
  elements: [
    {
      tag: "motion.circle",
      cx: "18",
      cy: "18",
      r: "3",
      variants: { normal: { pathLength: 1, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(0), opacity: { delay: CALCULATE_DELAY(0) } },
    },
    {
      tag: "motion.path",
      d: "M13 6h3a2 2 0 0 1 2 2v7",
      variants: { normal: { pathLength: 1, pathOffset: 0, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(1), opacity: { delay: CALCULATE_DELAY(1) } },
    },
    {
      tag: "motion.path",
      d: "M11 18H8a2 2 0 0 1-2-2V9",
      variants: { normal: { pathLength: 1, pathOffset: 0, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1], pathOffset: [1, 0] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(1), opacity: { delay: CALCULATE_DELAY(1) } },
    },
    {
      tag: "motion.circle",
      cx: "6",
      cy: "6",
      r: "3",
      variants: { normal: { pathLength: 1, opacity: 1, transition: { delay: 0 } }, animate: { pathLength: [0, 1], opacity: [0, 1] } },
      transition: { duration: DURATION, delay: CALCULATE_DELAY(2), opacity: { delay: CALCULATE_DELAY(2) } },
    },
  ],
});
