// @vegastack icon-git-commit-horizontal@0.8.2 sha256-5MzyI7lEPkMvKNr9g6cMQAvKyTQ7jdVVmPRkMyqQNG0=

// Mirrored from lucide-animated (https://lucide-animated.com/r/git-commit-horizontal.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1 },
  animate: (custom: number) => ({ pathLength: [0, 1], opacity: [0, 1], transition: { delay: 0.15 * custom, opacity: { delay: 0.1 * custom } } }),
};

export type GitCommitHorizontalIconHandle = AnimatedIconHandle;

export const GitCommitHorizontalIcon = createAnimatedIcon({
  name: "GitCommitHorizontalIcon",
  elements: [
    { tag: "motion.circle", cx: "12", cy: "12", r: "3", variants: VARIANTS, custom: 1 },
    { tag: "motion.line", x1: "3", x2: "9", y1: "12", y2: "12", variants: VARIANTS, custom: 0 },
    { tag: "motion.line", x1: "15", x2: "21", y1: "12", y2: "12", variants: VARIANTS, custom: 2 },
  ],
});
