// @vegastack icon-graduation-cap@0.7.2 sha256-/Tr8EKCmu51Rj5kDS9MDAW5VtqZDMT77PN8CviJMR80=

// Mirrored from lucide-animated (https://lucide-animated.com/r/graduation-cap.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CAP_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { y: [0, -2, 0], rotate: [0, -2, 2, 0], transition: { duration: 0.6, ease: "easeInOut" } } };

const TASSEL_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: [0, 15, -10, 5, 0], transition: { duration: 0.8, ease: "easeInOut", delay: 0.1 } } };

export type GraduationCapIconHandle = AnimatedIconHandle;

export const GraduationCapIcon = createAnimatedIcon({
  name: "GraduationCapIcon",
  elements: [
    {
      tag: "motion.g",
      variants: CAP_VARIANTS,
      style: { transformOrigin: "12px 12px" },
      children: [
        "M2 10l10-5 10 5-10 5z",
        "M6 12v5c3 3 9 3 12 0v-5",
        { tag: "motion.path", d: "M22 10v6", variants: TASSEL_VARIANTS, style: { transformBox: "fill-box", transformOrigin: "top center" }, inherit: true },
      ],
    },
  ],
});
