// @vegastack icon-heart-pulse@0.7.3 sha256-QeBl0TJyLCnfO6QdkXDkph5yOqjMYTnc3pVK2uGp6ts=

// Mirrored from lucide-animated (https://lucide-animated.com/r/heart-pulse.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const HEART_DRAW_VARIANTS: Variants = { normal: { pathLength: 1, opacity: 1 }, hidden: { pathLength: 0, opacity: 0 }, draw: { pathLength: [0, 1], opacity: [0, 1] } };

const HEART_PULSE_VARIANTS: Variants = { normal: { scale: 1 }, pulse: { scale: [1, 1.08, 1] } };

const LINE_VARIANTS: Variants = { normal: { pathLength: 1, pathOffset: 0, opacity: 1 }, animate: { pathLength: [0, 1], pathOffset: [1, 0], opacity: [0, 1] } };

export type HeartPulseIconHandle = AnimatedIconHandle;

export const HeartPulseIcon = createAnimatedIcon({
  name: "HeartPulseIcon",
  elements: [
    {
      tag: "motion.g",
      variants: HEART_PULSE_VARIANTS,
      style: { originX: "12px", originY: "12px" },
      group: "heartPulse",
      children: [
        {
          tag: "motion.path",
          d: "M2 9.5a5.5 5.5 0 0 1 9.591-3.676.56.56 0 0 0 .818 0A5.49 5.49 0 0 1 22 9.5c0 2.29-1.5 4-3 5.5l-5.492 5.313a2 2 0 0 1-3 .019L5 15c-1.5-1.5-3-3.2-3-5.5",
          variants: HEART_DRAW_VARIANTS,
          group: "heartDraw",
        },
      ],
    },
    { tag: "motion.path", d: "M3.22 13H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27", variants: LINE_VARIANTS, group: "line" },
  ],
  groups: ["heartDraw", "heartPulse", "line"],
  start: async ({ control, run }) => {
    run(control("heartDraw"), "hidden", { duration: 0 });
    await run(control("line"), "animate", { duration: 0.6, ease: "linear", opacity: { duration: 0.1 } });
    await run(control("heartDraw"), "draw", { duration: 0.5, ease: "easeOut", opacity: { duration: 0.1 } });
    run(control("heartPulse"), "pulse", { duration: 0.9, repeat: 1, ease: "easeInOut" });
  },
  stop: ({ control, reset }) => {
    reset(control("heartDraw"), "normal", { duration: 0.3 });
    reset(control("heartPulse"), "normal", { duration: 0.3 });
    reset(control("line"), "normal", { duration: 0.3 });
  },
});
