// @vegastack icon-keyboard@0.8.1 sha256-y/nxod+5i4lo/fG2ZMXD0ll3MvXPRMuKkrRRgk9zceM=

// Mirrored from lucide-animated (https://lucide-animated.com/r/keyboard.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type KeyboardIconHandle = AnimatedIconHandle;

export const KeyboardIcon = createAnimatedIcon({
  name: "KeyboardIcon",
  elements: [
    { tag: "rect", height: "16", rx: "2", width: "20", x: "2", y: "4" },
    { tag: "motion.path", d: "M10 8h.01", initial: { opacity: 1 }, custom: 0 },
    { tag: "motion.path", d: "M12 12h.01", initial: { opacity: 1 }, custom: 1 },
    { tag: "motion.path", d: "M14 8h.01", initial: { opacity: 1 }, custom: 2 },
    { tag: "motion.path", d: "M16 12h.01", initial: { opacity: 1 }, custom: 3 },
    { tag: "motion.path", d: "M18 8h.01", initial: { opacity: 1 }, custom: 4 },
    { tag: "motion.path", d: "M6 8h.01", initial: { opacity: 1 }, custom: 5 },
    { tag: "motion.path", d: "M7 16h10", initial: { opacity: 1 }, custom: 6 },
    { tag: "motion.path", d: "M8 12h.01", initial: { opacity: 1 }, custom: 7 },
  ],
  start: ({ run, control }) =>
    run(control(), (i: number) => ({ opacity: [1, 0.2, 1], transition: { duration: 1.5, times: [0, 0.5, 1], delay: i * 0.2 * Math.random(), repeat: 1, repeatType: "reverse" } })),
  stop: ({ set, control }) => set(control(), { opacity: 1 }),
});
