// @vegastack icon-loader-pinwheel@0.7.0 sha256-pK0BSxzqbH6CUNy1MsbFcV5btGcsuVm4Pz9MUOCptxI=

// Mirrored from lucide-animated (https://lucide-animated.com/r/loader-pinwheel.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const G_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: 360, transition: { repeat: 1, duration: 1, ease: "linear" } } };

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 50, damping: 10 };

export type LoaderPinwheelIconHandle = AnimatedIconHandle;

export const LoaderPinwheelIcon = createAnimatedIcon({
  name: "LoaderPinwheelIcon",
  elements: [
    {
      tag: "motion.g",
      variants: G_VARIANTS,
      transition: DEFAULT_TRANSITION,
      children: ["M22 12a1 1 0 0 1-10 0 1 1 0 0 0-10 0", "M7 20.7a1 1 0 1 1 5-8.7 1 1 0 1 0 5-8.6", "M7 3.3a1 1 0 1 1 5 8.6 1 1 0 1 0 5 8.6"],
    },
    { tag: "circle", cx: "12", cy: "12", r: "10" },
  ],
});
