// @vegastack icon-lock-keyhole-open@0.7.5 sha256-RlWr5HNG8wPUoldUxBFGIShfszkahUqSlOuZWIMbykY=

// Mirrored from lucide-animated (https://lucide-animated.com/r/lock-keyhole-open.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type LockKeyholeOpenIconHandle = AnimatedIconHandle;

export const LockKeyholeOpenIcon = createAnimatedIcon({
  name: "LockKeyholeOpenIcon",
  svg: {
    tag: "motion.svg",
    variants: { normal: { rotate: 0, scale: 1 }, animate: { rotate: [2, 4, -2, 0], scale: [1.05, 0.95, 1.02, 1] } },
    initial: "normal",
    transition: { duration: 1, ease: [0.4, 0, 0.2, 1] },
  },
  elements: [
    { tag: "circle", cx: "12", cy: "16", r: "1" },
    { tag: "rect", height: "12", rx: "2", width: "18", x: "3", y: "10" },
    {
      tag: "motion.path",
      d: "M7 10V7a5 5 0 0 1 10 0v3",
      variants: { normal: { pathLength: 0.8 }, animate: { pathLength: 1 } },
      initial: "normal",
      transition: { duration: 0.3, ease: [0.4, 0, 0.2, 1] },
    },
  ],
});
