// @vegastack icon-mic-off@0.4.1 sha256-XsLjMOb0aayDhxWc22YBN7vHpqLGQ1lmR15OvqUBTAI=

// Mirrored from lucide-animated (https://lucide-animated.com/r/mic-off.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface MicOffIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface MicOffIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<MicOffIconHandle>;
}

const LINE_VARIANTS: Variants = {
  normal: {
    pathLength: 1,
    opacity: 1,
    transition: {
      duration: 0.3,
      opacity: { duration: 0.1 },
    },
  },
  animate: {
    pathLength: [0, 1],
    opacity: [0, 1],
    transition: {
      duration: 0.4,
      delay: 0.15,
      opacity: { duration: 0.1 },
    },
  },
};

const MicOffIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: MicOffIconProps) => {
  const controls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = () => runAnimation(controls, "animate");
  const stopAnimation = () => resetAnimation(controls, "normal");
  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <svg
        fill="none"
        height={size}
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <path d="M12 19v3" />
        <path d="M15 9.34V5a3 3 0 0 0-5.68-1.33" />
        <path d="M16.95 16.95A7 7 0 0 1 5 12v-2" />
        <path d="M18.89 13.23A7 7 0 0 0 19 12v-2" />
        <path d="M9 9v3a3 3 0 0 0 5.12 2.12" />
        <motion.path
          animate={controls}
          d="m2 2 20 20"
          initial="normal"
          variants={LINE_VARIANTS}
        />
      </svg>
    </div>
  );
};

MicOffIcon.displayName = "MicOffIcon";

export { MicOffIcon };
