// @vegastack icon-monitor-check@0.25.6 sha256-Z9njuUsl8QaEFLGH9d5YDWP+zGlJT9j7B1Z+qR0845s=

// Mirrored from lucide-animated (https://lucide-animated.com/r/monitor-check.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const CHECK_VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1, transition: { duration: 0.3 } },
  animate: { pathLength: [0, 1], opacity: [0, 1], transition: { pathLength: { duration: 0.4, ease: "easeInOut" }, opacity: { duration: 0.4, ease: "easeInOut" } } },
};

export type MonitorCheckIconHandle = AnimatedIconHandle;

export const MonitorCheckIcon = createAnimatedIcon({
  name: "MonitorCheckIcon",
  elements: [
    { tag: "rect", height: "14", rx: "2", width: "20", x: "2", y: "3" },
    "M12 17v4",
    "M8 21h8",
    { tag: "motion.path", d: "m9 10 2 2 4-4", variants: CHECK_VARIANTS, initial: "normal", style: { transformOrigin: "center" } },
  ],
});
