// @vegastack icon-play@0.7.2 sha256-ikHC1jYXa0xVt7AsNH8gWLBarlcyGRO0Ugbh5Ol/8dw=

// Mirrored from lucide-animated (https://lucide-animated.com/r/play.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { x: 0, rotate: 0 },
  animate: { x: [0, -1, 2, 0], rotate: [0, -10, 0, 0], transition: { duration: 0.5, times: [0, 0.2, 0.5, 1], stiffness: 260, damping: 20 } },
};

export type PlayIconHandle = AnimatedIconHandle;

export const PlayIcon = createAnimatedIcon({
  name: "PlayIcon",
  svg: { tag: "motion.svg", inherit: true },
  elements: [{ tag: "motion.polygon", points: "6 3 20 12 6 21 6 3", variants: PATH_VARIANTS }],
});
