// @vegastack icon-plug-zap@0.8.2 sha256-eAOGtiMwULKegLKWtl+4Wi1CUgHtoIlub6ZMr4tPYh4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/plug-zap.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const ZAP_VARIANT: Variants = { normal: { opacity: 1 }, animate: { opacity: [1, 0.4, 1], transition: { duration: 1, repeat: 1, ease: "easeInOut" } } };

export type PlugZapIconHandle = AnimatedIconHandle;

export const PlugZapIcon = createAnimatedIcon({
  name: "PlugZapIcon",
  elements: [
    "M6.3 20.3a2.4 2.4 0 0 0 3.4 0L12 18l-6-6-2.3 2.3a2.4 2.4 0 0 0 0 3.4Z",
    "m2 22 3-3",
    "M7.5 13.5 10 11",
    "M10.5 16.5 13 14",
    { tag: "motion.path", d: "m18 3-4 4h6l-4 4", variants: ZAP_VARIANT, initial: "normal" },
  ],
});
