// @vegastack icon-refresh-cw@0.8.1 sha256-Ecf43H/09rFVB2i10qk4x72pofG3UDO2R7T7ygs7f2A=

// Mirrored from lucide-animated (https://lucide-animated.com/r/refresh-cw.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type RefreshCWIconHandle = AnimatedIconHandle;

export const RefreshCWIcon = createAnimatedIcon({
  name: "RefreshCWIcon",
  svg: { tag: "motion.svg", variants: { normal: { rotate: "0deg" }, animate: { rotate: "50deg" } }, transition: { type: "spring", stiffness: 250, damping: 25 } },
  elements: ["M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8", "M21 3v5h-5", "M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16", "M8 16H3v5"],
});
