// @vegastack icon-rocking-chair@0.7.1 sha256-14eiRJzgZlRgHL9eXRuVZf/Z0dl0sohDLZkRBnGQjOs=

// Mirrored from lucide-animated (https://lucide-animated.com/r/rocking-chair.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants, Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { type: "spring", stiffness: 100, damping: 12, mass: 0.4 };

const ROCKING_VARIANTS: Variants = { normal: { rotate: 0 }, animate: { rotate: [-5, 5, -5], transition: { repeat: 1, repeatType: "mirror" as const, duration: 1.2, ease: "easeInOut" } } };

export type RockingChairIconHandle = AnimatedIconHandle;

export const RockingChairIcon = createAnimatedIcon({
  name: "RockingChairIcon",
  svg: { tag: "motion.svg", variants: ROCKING_VARIANTS, style: { originX: "10%", originY: "90%" } },
  elements: [
    { tag: "motion.polyline", points: "3.5 2 6.5 12.5 18 12.5", transition: DEFAULT_TRANSITION },
    { tag: "motion.line", x1: "9.5", x2: "5.5", y1: "12.5", y2: "20", transition: DEFAULT_TRANSITION },
    { tag: "motion.line", x1: "15", x2: "18.5", y1: "12.5", y2: "20", transition: DEFAULT_TRANSITION },
    { tag: "motion.path", d: "M2.75 18a13 13 0 0 0 18.5 0", transition: DEFAULT_TRANSITION },
  ],
});
