// @vegastack icon-saudi-riyal@0.7.1 sha256-zJHSdNhapc2vauq4VFhIxkLRylgZ/Nx2v3J9grD/69E=

// Mirrored from lucide-animated (https://lucide-animated.com/r/saudi-riyal.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const SAUDI_RIYAL_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, transition: { duration: 0.4, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], transition: { duration: 0.6, opacity: { duration: 0.1 } } },
};

export type SaudiRiyalIconHandle = AnimatedIconHandle;

export const SaudiRiyalIcon = createAnimatedIcon({
  name: "SaudiRiyalIcon",
  elements: [
    { tag: "motion.path", d: "m20 19.5-5.5 1.2", variants: SAUDI_RIYAL_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M14.5 4v11.22a1 1 0 0 0 1.242.97L20 15.2", variants: SAUDI_RIYAL_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "m2.978 19.351 5.549-1.363A2 2 0 0 0 10 16V2", variants: SAUDI_RIYAL_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M20 10 4 13.5", variants: SAUDI_RIYAL_VARIANTS, initial: "normal" },
  ],
});
