// @vegastack icon-search@0.23.108 sha256-KtcWU0lWKtEfxmczR2Ai026rh6upsY03R7447Rqdf2g=

// Mirrored from lucide-animated (https://lucide-animated.com/r/search.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

export type SearchIconHandle = AnimatedIconHandle;

export const SearchIcon = createAnimatedIcon({
  name: "SearchIcon",
  svg: { tag: "motion.svg", variants: { normal: { x: 0, y: 0 }, animate: { x: [0, 0, -3, 0], y: [0, -4, 0, 0] } }, transition: { duration: 1, bounce: 0.3 } },
  elements: [{ tag: "circle", cx: "11", cy: "11", r: "8" }, "m21 21-4.3-4.3"],
});
