// @vegastack icon-smartphone-nfc@0.7.0 sha256-ddALHbyIIhr/pP79vtgjKT89jfvgEg430C+M8PR5utQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/smartphone-nfc.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, transition: { duration: 0.4 } },
  fadeOut: { opacity: 0, transition: { duration: 0.3 } },
  fadeIn: (i: number) => ({ opacity: 1, transition: { type: "spring", stiffness: 300, damping: 20, delay: i * 0.1 } }),
};

export type SmartphoneNfcIconHandle = AnimatedIconHandle;

export const SmartphoneNfcIcon = createAnimatedIcon({
  name: "SmartphoneNfcIcon",
  elements: [
    { tag: "rect", height: "12", rx: "1", width: "7", x: "2", y: "6" },
    { tag: "motion.path", d: "M13 8.32a7.43 7.43 0 0 1 0 7.36", variants: PATH_VARIANTS, initial: { opacity: 1 }, custom: 0 },
    { tag: "motion.path", d: "M16.46 6.21a11.76 11.76 0 0 1 0 11.58", variants: PATH_VARIANTS, initial: { opacity: 1 }, custom: 1 },
    { tag: "motion.path", d: "M19.91 4.1a15.91 15.91 0 0 1 .01 15.8", variants: PATH_VARIANTS, initial: { opacity: 1 }, custom: 2 },
  ],
  start: async ({ control, run }) => {
    await run(control(), "fadeOut");
    run(control(), "fadeIn");
  },
  stop: ({ control, reset }) => {
    reset(control(), "normal");
  },
});
