// @vegastack icon-smile@0.3.0 sha256-vU6SJ83577foJVBw4amlM98FmK1TVDviJwgM1C+1i0E=

// Mirrored from lucide-animated (https://lucide-animated.com/r/smile.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface SmileIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface SmileIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<SmileIconHandle>;
}

const SmileIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: SmileIconProps) => {
  const controls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = () => runAnimation(controls, "animate");
  const stopAnimation = () => resetAnimation(controls, "normal");
  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  const faceVariants: Variants = {
    normal: {
      scale: 1,
      rotate: 0,
      strokeWidth: 2,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      scale: [1, 1.15, 1.05, 1.1],
      rotate: [0, -3, 3, 0],
      strokeWidth: [2, 2.5, 2.5, 2.5],
      transition: {
        duration: 0.8,
        times: [0, 0.3, 0.6, 1],
        ease: "easeInOut",
      },
    },
  };

  const mouthVariants: Variants = {
    normal: {
      d: "M8 14s1.5 2 4 2 4-2 4-2",
      pathLength: 1,
      pathOffset: 0,
      strokeWidth: 2,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      d: "M7 13.5s2.5 3.5 5 3.5 5-3.5 5-3.5",
      pathLength: [0.3, 1, 1],
      pathOffset: [0, 0, 0],
      strokeWidth: 2.5,
      transition: {
        d: { duration: 0.4, ease: "easeOut" },
        pathLength: {
          duration: 0.5,
          times: [0, 0.5, 1],
          ease: "easeInOut",
        },
        delay: 0.1,
      },
    },
  };

  const eyeVariants: Variants = {
    normal: {
      scale: 1,
      opacity: 1,
      transition: { duration: 0.3, ease: "easeOut" },
    },
    animate: {
      scale: [1, 1.5, 0.8, 1.2],
      opacity: [1, 1, 1, 1],
      transition: {
        duration: 0.5,
        times: [0, 0.3, 0.6, 1],
        ease: "easeInOut",
      },
    },
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <motion.svg
        animate={controls}
        fill="none"
        height={size}
        initial="normal"
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        variants={faceVariants}
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <motion.circle cx="12" cy="12" r="10" />
        <motion.path
          animate={controls}
          d="M8 14s1.5 2 4 2 4-2 4-2"
          initial="normal"
          variants={mouthVariants}
        />
        <motion.line
          animate={controls}
          initial="normal"
          variants={eyeVariants}
          x1="9"
          x2="9.01"
          y1="9"
          y2="9"
        />
        <motion.line
          animate={controls}
          initial="normal"
          variants={eyeVariants}
          x1="15"
          x2="15.01"
          y1="9"
          y2="9"
        />
      </motion.svg>
    </div>
  );
};

SmileIcon.displayName = "SmileIcon";

export { SmileIcon };
