// @vegastack icon-square-chevron-up@0.7.1 sha256-utjtpX4C/XhR4tCHuSdFVyomSinvicXlVDrawicR4H4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/square-chevron-up.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Transition } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const DEFAULT_TRANSITION: Transition = { times: [0, 0.4, 1], duration: 0.5 };

export type SquareChevronUpIconHandle = AnimatedIconHandle;

export const SquareChevronUpIcon = createAnimatedIcon({
  name: "SquareChevronUpIcon",
  elements: [
    { tag: "rect", height: "18", rx: "2", width: "18", x: "3", y: "3" },
    { tag: "motion.path", d: "m8 14 4-4 4 4", variants: { normal: { y: 0 }, animate: { y: [0, -2, 0] } }, transition: DEFAULT_TRANSITION },
  ],
});
