// @vegastack icon-square-activity@0.7.0 sha256-Q/pU5o+DrUoAraeRKkQtLVsEFdSTG9U0mC8BhpAnnJ4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/square-activity.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PATH_VARIANTS: Variants = {
  normal: { opacity: 1, pathLength: 1, pathOffset: 0, transition: { duration: 0.4, opacity: { duration: 0.1 } } },
  animate: { opacity: [0, 1], pathLength: [0, 1], pathOffset: [1, 0], transition: { duration: 0.6, ease: "linear", opacity: { duration: 0.1 } } },
};

const SQUARE_VARIANTS: Variants = { normal: { transition: { duration: 0.4 } }, animate: { transition: { duration: 0.6, ease: "easeInOut" } } };

export type SquareActivityIconHandle = AnimatedIconHandle;

export const SquareActivityIcon = createAnimatedIcon({
  name: "SquareActivityIcon",
  elements: [
    { tag: "motion.rect", height: "18", rx: "2", width: "18", x: "3", y: "3", variants: SQUARE_VARIANTS, initial: "normal" },
    { tag: "motion.path", d: "M17 12h-2l-2 5-2-10-2 5H7", variants: PATH_VARIANTS, initial: "normal" },
  ],
});
