// @vegastack icon-square-pen@0.7.3 sha256-E6DicJzjVdHYKjuK46E17Q8YoyAtPm5aeVKLb4ArXt4=

// Mirrored from lucide-animated (https://lucide-animated.com/r/square-pen.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { createAnimatedIcon, type AnimatedIconHandle } from "@vegastack/design/create-animated-icon";

const PEN_VARIANTS: Variants = { normal: { rotate: 0, x: 0, y: 0 }, animate: { rotate: [-0.5, 0.5, -0.5], x: [0, -1, 1.5, 0], y: [0, 1.5, -1, 0] } };

export type SquarePenIconHandle = AnimatedIconHandle;

export const SquarePenIcon = createAnimatedIcon({
  name: "SquarePenIcon",
  svg: { style: { overflow: "visible" } },
  elements: [
    "M12 3H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7",
    { tag: "motion.path", d: "M18.375 2.625a1 1 0 0 1 3 3l-9.013 9.014a2 2 0 0 1-.853.505l-2.873.84a.5.5 0 0 1-.62-.62l.84-2.873a2 2 0 0 1 .506-.852z", variants: PEN_VARIANTS },
  ],
});
