// @vegastack icon-underline@0.2.0 sha256-efNYpc4RiLJXZB0/HWKhGUFbcvaj4xle4cQOilut1tQ=

// Mirrored from lucide-animated (https://lucide-animated.com/r/underline.json) — MIT.
// Generated by tooling/mirror-animated-icons.mjs — do NOT hand-edit; re-run the mirror to update.

"use client";

import type { Variants } from "motion/react";
import { motion, useAnimation, useReducedMotion } from "motion/react";
import type { HTMLAttributes } from "react";
import { useCallback, useImperativeHandle, useRef, useEffect } from "react";

import { cn } from "@vegastack/design";

export interface UnderlineIconHandle {
  startAnimation: () => void;
  stopAnimation: () => void;
}

interface UnderlineIconProps extends HTMLAttributes<HTMLDivElement> {
  size?: number | string;
  ref?: React.Ref<UnderlineIconHandle>;
}

const VARIANTS: Variants = {
  normal: { pathLength: 1, opacity: 1, pathOffset: 0 },
  animate: {
    pathLength: [0, 1],
    opacity: [0, 1],
    pathOffset: [1, 0],
  },
};

const UnderlineIcon = ({
  onMouseEnter,
  onMouseLeave,
  className,
  size = "var(--icon-default)",
  ref,
  onPointerEnter,
  onPointerLeave,
  onPointerDown,
  onFocus,
  onBlur,
  ...props
}: UnderlineIconProps) => {
  const controls = useAnimation();
  const shouldReduceMotion = useReducedMotion();
  const runAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const resetAnimation = useCallback(
    (
      control: typeof controls,
      definition: Parameters<typeof controls.start>[0],
      transitionOverride?: Parameters<typeof controls.start>[1],
    ) => {
      if (shouldReduceMotion) {
        control.stop();
        control.set(definition);
        return Promise.resolve();
      }
      return control.start(definition, transitionOverride);
    },
    [shouldReduceMotion],
  );
  const isControlledRef = useRef(false);

  const startAnimation = () => runAnimation(controls, "animate");
  const stopAnimation = () => resetAnimation(controls, "normal");
  useImperativeHandle(ref, () => {
    isControlledRef.current = true;
    return { startAnimation, stopAnimation };
  });

  useEffect(() => {
    if (shouldReduceMotion) stopAnimation();
  });

  const handlePointerEnter = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerEnter?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      startAnimation();
  };

  const handlePointerLeave = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerLeave?.(event);
    if (!isControlledRef.current && event.pointerType !== "touch")
      stopAnimation();
  };

  const handlePointerDown = (event: React.PointerEvent<HTMLDivElement>) => {
    onPointerDown?.(event);
    if (!isControlledRef.current && event.pointerType === "touch")
      startAnimation();
  };

  const handleFocus = (event: React.FocusEvent<HTMLDivElement>) => {
    onFocus?.(event);
    if (!isControlledRef.current) startAnimation();
  };

  const handleBlur = (event: React.FocusEvent<HTMLDivElement>) => {
    onBlur?.(event);
    if (!isControlledRef.current) stopAnimation();
  };

  return (
    <div
      className={cn(className)}
      onMouseEnter={onMouseEnter}
      onMouseLeave={onMouseLeave}
      onPointerEnter={handlePointerEnter}
      onPointerLeave={handlePointerLeave}
      onPointerDown={handlePointerDown}
      onFocus={handleFocus}
      onBlur={handleBlur}
      {...props}
    >
      <svg
        fill="none"
        height={size}
        stroke="currentColor"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
        viewBox="0 0 24 24"
        width={size}
        xmlns="http://www.w3.org/2000/svg"
      >
        <motion.path
          animate={controls}
          d="M6 4v6a6 6 0 0 0 12 0V4"
          transition={{ duration: 0.3 }}
          variants={VARIANTS}
        />
        <motion.line
          animate={controls}
          transition={{
            delay: 0.2,
            duration: 0.4,
          }}
          variants={VARIANTS}
          x1="4"
          x2="20"
          y1="20"
          y2="20"
        />
      </svg>
    </div>
  );
};

UnderlineIcon.displayName = "UnderlineIcon";

export { UnderlineIcon };
