// @vegastack region-select@0.3.0 sha256-bFYobi62HB5ECpAsPBaMaLtAFM4RxH7uwv2OYNiTgtI=

import type { Region } from "./region-select";

/**
 * Region datasets keyed by ISO country code — split out of the component so the
 * (large, rarely-edited) data can ship and be reviewed separately from the UI
 * (register P2-08). Consumed by `RegionSelect` via `getRegionsByCountry`.
 */
/**
 * A comprehensive, embedded dataset of states/provinces keyed by ISO-3166-1 alpha-2 country code,
 * covering 45 countries with administrative divisions (US states, Canadian provinces, Australian
 * states/territories, Indian states/UTs, UK regions, plus most high-volume billing/shipping markets
 * across the Americas, Europe, Africa, the Middle East, and Asia-Pacific). Countries absent from this
 * map have no predefined subdivisions and fall back to a free-text input.
 */
export const REGIONS_BY_COUNTRY: Record<string, Region[]> = {
  // United States
  US: [
    { code: "AL", name: "Alabama" },
    { code: "AK", name: "Alaska" },
    { code: "AZ", name: "Arizona" },
    { code: "AR", name: "Arkansas" },
    { code: "CA", name: "California" },
    { code: "CO", name: "Colorado" },
    { code: "CT", name: "Connecticut" },
    { code: "DE", name: "Delaware" },
    { code: "FL", name: "Florida" },
    { code: "GA", name: "Georgia" },
    { code: "HI", name: "Hawaii" },
    { code: "ID", name: "Idaho" },
    { code: "IL", name: "Illinois" },
    { code: "IN", name: "Indiana" },
    { code: "IA", name: "Iowa" },
    { code: "KS", name: "Kansas" },
    { code: "KY", name: "Kentucky" },
    { code: "LA", name: "Louisiana" },
    { code: "ME", name: "Maine" },
    { code: "MD", name: "Maryland" },
    { code: "MA", name: "Massachusetts" },
    { code: "MI", name: "Michigan" },
    { code: "MN", name: "Minnesota" },
    { code: "MS", name: "Mississippi" },
    { code: "MO", name: "Missouri" },
    { code: "MT", name: "Montana" },
    { code: "NE", name: "Nebraska" },
    { code: "NV", name: "Nevada" },
    { code: "NH", name: "New Hampshire" },
    { code: "NJ", name: "New Jersey" },
    { code: "NM", name: "New Mexico" },
    { code: "NY", name: "New York" },
    { code: "NC", name: "North Carolina" },
    { code: "ND", name: "North Dakota" },
    { code: "OH", name: "Ohio" },
    { code: "OK", name: "Oklahoma" },
    { code: "OR", name: "Oregon" },
    { code: "PA", name: "Pennsylvania" },
    { code: "RI", name: "Rhode Island" },
    { code: "SC", name: "South Carolina" },
    { code: "SD", name: "South Dakota" },
    { code: "TN", name: "Tennessee" },
    { code: "TX", name: "Texas" },
    { code: "UT", name: "Utah" },
    { code: "VT", name: "Vermont" },
    { code: "VA", name: "Virginia" },
    { code: "WA", name: "Washington" },
    { code: "WV", name: "West Virginia" },
    { code: "WI", name: "Wisconsin" },
    { code: "WY", name: "Wyoming" },
    { code: "DC", name: "District of Columbia" },
  ],

  // Canada
  CA: [
    { code: "AB", name: "Alberta" },
    { code: "BC", name: "British Columbia" },
    { code: "MB", name: "Manitoba" },
    { code: "NB", name: "New Brunswick" },
    { code: "NL", name: "Newfoundland and Labrador" },
    { code: "NS", name: "Nova Scotia" },
    { code: "NT", name: "Northwest Territories" },
    { code: "NU", name: "Nunavut" },
    { code: "ON", name: "Ontario" },
    { code: "PE", name: "Prince Edward Island" },
    { code: "QC", name: "Quebec" },
    { code: "SK", name: "Saskatchewan" },
    { code: "YT", name: "Yukon" },
  ],

  // Australia
  AU: [
    { code: "ACT", name: "Australian Capital Territory" },
    { code: "NSW", name: "New South Wales" },
    { code: "NT", name: "Northern Territory" },
    { code: "QLD", name: "Queensland" },
    { code: "SA", name: "South Australia" },
    { code: "TAS", name: "Tasmania" },
    { code: "VIC", name: "Victoria" },
    { code: "WA", name: "Western Australia" },
  ],

  // India
  IN: [
    { code: "AN", name: "Andaman and Nicobar Islands" },
    { code: "AP", name: "Andhra Pradesh" },
    { code: "AR", name: "Arunachal Pradesh" },
    { code: "AS", name: "Assam" },
    { code: "BR", name: "Bihar" },
    { code: "CH", name: "Chandigarh" },
    { code: "CT", name: "Chhattisgarh" },
    { code: "DN", name: "Dadra and Nagar Haveli and Daman and Diu" },
    { code: "DL", name: "Delhi" },
    { code: "GA", name: "Goa" },
    { code: "GJ", name: "Gujarat" },
    { code: "HR", name: "Haryana" },
    { code: "HP", name: "Himachal Pradesh" },
    { code: "JK", name: "Jammu and Kashmir" },
    { code: "JH", name: "Jharkhand" },
    { code: "KA", name: "Karnataka" },
    { code: "KL", name: "Kerala" },
    { code: "LA", name: "Ladakh" },
    { code: "LD", name: "Lakshadweep" },
    { code: "MP", name: "Madhya Pradesh" },
    { code: "MH", name: "Maharashtra" },
    { code: "MN", name: "Manipur" },
    { code: "ML", name: "Meghalaya" },
    { code: "MZ", name: "Mizoram" },
    { code: "NL", name: "Nagaland" },
    { code: "OR", name: "Odisha" },
    { code: "PY", name: "Puducherry" },
    { code: "PB", name: "Punjab" },
    { code: "RJ", name: "Rajasthan" },
    { code: "SK", name: "Sikkim" },
    { code: "TN", name: "Tamil Nadu" },
    { code: "TS", name: "Telangana" },
    { code: "TR", name: "Tripura" },
    { code: "UP", name: "Uttar Pradesh" },
    { code: "UK", name: "Uttarakhand" },
    { code: "WB", name: "West Bengal" },
  ],

  // Brazil
  BR: [
    { code: "AC", name: "Acre" },
    { code: "AL", name: "Alagoas" },
    { code: "AP", name: "Amapá" },
    { code: "AM", name: "Amazonas" },
    { code: "BA", name: "Bahia" },
    { code: "CE", name: "Ceará" },
    { code: "DF", name: "Distrito Federal" },
    { code: "ES", name: "Espírito Santo" },
    { code: "GO", name: "Goiás" },
    { code: "MA", name: "Maranhão" },
    { code: "MT", name: "Mato Grosso" },
    { code: "MS", name: "Mato Grosso do Sul" },
    { code: "MG", name: "Minas Gerais" },
    { code: "PA", name: "Pará" },
    { code: "PB", name: "Paraíba" },
    { code: "PR", name: "Paraná" },
    { code: "PE", name: "Pernambuco" },
    { code: "PI", name: "Piauí" },
    { code: "RJ", name: "Rio de Janeiro" },
    { code: "RN", name: "Rio Grande do Norte" },
    { code: "RS", name: "Rio Grande do Sul" },
    { code: "RO", name: "Rondônia" },
    { code: "RR", name: "Roraima" },
    { code: "SC", name: "Santa Catarina" },
    { code: "SP", name: "São Paulo" },
    { code: "SE", name: "Sergipe" },
    { code: "TO", name: "Tocantins" },
  ],

  // Mexico
  MX: [
    { code: "AGU", name: "Aguascalientes" },
    { code: "BCN", name: "Baja California" },
    { code: "BCS", name: "Baja California Sur" },
    { code: "CAM", name: "Campeche" },
    { code: "CHP", name: "Chiapas" },
    { code: "CHH", name: "Chihuahua" },
    { code: "COA", name: "Coahuila" },
    { code: "COL", name: "Colima" },
    { code: "DIF", name: "Ciudad de México" },
    { code: "DUR", name: "Durango" },
    { code: "GUA", name: "Guanajuato" },
    { code: "GRO", name: "Guerrero" },
    { code: "HID", name: "Hidalgo" },
    { code: "JAL", name: "Jalisco" },
    { code: "MEX", name: "Estado de México" },
    { code: "MIC", name: "Michoacán" },
    { code: "MOR", name: "Morelos" },
    { code: "NAY", name: "Nayarit" },
    { code: "NLE", name: "Nuevo León" },
    { code: "OAX", name: "Oaxaca" },
    { code: "PUE", name: "Puebla" },
    { code: "QUE", name: "Querétaro" },
    { code: "ROO", name: "Quintana Roo" },
    { code: "SLP", name: "San Luis Potosí" },
    { code: "SIN", name: "Sinaloa" },
    { code: "SON", name: "Sonora" },
    { code: "TAB", name: "Tabasco" },
    { code: "TAM", name: "Tamaulipas" },
    { code: "TLA", name: "Tlaxcala" },
    { code: "VER", name: "Veracruz" },
    { code: "YUC", name: "Yucatán" },
    { code: "ZAC", name: "Zacatecas" },
  ],

  // United Kingdom
  GB: [
    { code: "ENG", name: "England" },
    { code: "SCT", name: "Scotland" },
    { code: "WLS", name: "Wales" },
    { code: "NIR", name: "Northern Ireland" },
  ],

  // Germany
  DE: [
    { code: "BW", name: "Baden-Württemberg" },
    { code: "BY", name: "Bayern" },
    { code: "BE", name: "Berlin" },
    { code: "BB", name: "Brandenburg" },
    { code: "HB", name: "Bremen" },
    { code: "HH", name: "Hamburg" },
    { code: "HE", name: "Hessen" },
    { code: "MV", name: "Mecklenburg-Vorpommern" },
    { code: "NI", name: "Niedersachsen" },
    { code: "NW", name: "Nordrhein-Westfalen" },
    { code: "RP", name: "Rheinland-Pfalz" },
    { code: "SL", name: "Saarland" },
    { code: "SN", name: "Sachsen" },
    { code: "ST", name: "Sachsen-Anhalt" },
    { code: "SH", name: "Schleswig-Holstein" },
    { code: "TH", name: "Thüringen" },
  ],

  // Italy
  IT: [
    { code: "ABR", name: "Abruzzo" },
    { code: "BAS", name: "Basilicata" },
    { code: "CAL", name: "Calabria" },
    { code: "CAM", name: "Campania" },
    { code: "EMR", name: "Emilia-Romagna" },
    { code: "FVG", name: "Friuli-Venezia Giulia" },
    { code: "LAZ", name: "Lazio" },
    { code: "LIG", name: "Liguria" },
    { code: "LOM", name: "Lombardia" },
    { code: "MAR", name: "Marche" },
    { code: "MOL", name: "Molise" },
    { code: "PIE", name: "Piemonte" },
    { code: "PUG", name: "Puglia" },
    { code: "SAR", name: "Sardegna" },
    { code: "SIC", name: "Sicilia" },
    { code: "TOS", name: "Toscana" },
    { code: "TAA", name: "Trentino-Alto Adige" },
    { code: "UMB", name: "Umbria" },
    { code: "VAL", name: "Valle d'Aosta" },
    { code: "VEN", name: "Veneto" },
  ],

  // Spain
  ES: [
    { code: "AN", name: "Andalucía" },
    { code: "AR", name: "Aragón" },
    { code: "AS", name: "Principado de Asturias" },
    { code: "CN", name: "Canarias" },
    { code: "CB", name: "Cantabria" },
    { code: "CL", name: "Castilla y León" },
    { code: "CM", name: "Castilla-La Mancha" },
    { code: "CT", name: "Cataluña" },
    { code: "EX", name: "Extremadura" },
    { code: "GA", name: "Galicia" },
    { code: "IB", name: "Islas Baleares" },
    { code: "RI", name: "La Rioja" },
    { code: "MD", name: "Comunidad de Madrid" },
    { code: "MC", name: "Región de Murcia" },
    { code: "NC", name: "Comunidad Foral de Navarra" },
    { code: "PV", name: "País Vasco" },
    { code: "VC", name: "Comunidad Valenciana" },
  ],

  // France
  FR: [
    { code: "ARA", name: "Auvergne-Rhône-Alpes" },
    { code: "BFC", name: "Bourgogne-Franche-Comté" },
    { code: "BRE", name: "Bretagne" },
    { code: "CVL", name: "Centre-Val de Loire" },
    { code: "COR", name: "Corse" },
    { code: "GES", name: "Grand Est" },
    { code: "HDF", name: "Hauts-de-France" },
    { code: "IDF", name: "Île-de-France" },
    { code: "NOR", name: "Normandie" },
    { code: "NAQ", name: "Nouvelle-Aquitaine" },
    { code: "OCC", name: "Occitanie" },
    { code: "PDL", name: "Pays de la Loire" },
    { code: "PAC", name: "Provence-Alpes-Côte d'Azur" },
  ],

  // Japan
  JP: [
    { code: "01", name: "Hokkaido" },
    { code: "02", name: "Aomori" },
    { code: "03", name: "Iwate" },
    { code: "04", name: "Miyagi" },
    { code: "05", name: "Akita" },
    { code: "06", name: "Yamagata" },
    { code: "07", name: "Fukushima" },
    { code: "08", name: "Ibaraki" },
    { code: "09", name: "Tochigi" },
    { code: "10", name: "Gunma" },
    { code: "11", name: "Saitama" },
    { code: "12", name: "Chiba" },
    { code: "13", name: "Tokyo" },
    { code: "14", name: "Kanagawa" },
    { code: "15", name: "Niigata" },
    { code: "16", name: "Toyama" },
    { code: "17", name: "Ishikawa" },
    { code: "18", name: "Fukui" },
    { code: "19", name: "Yamanashi" },
    { code: "20", name: "Nagano" },
    { code: "21", name: "Gifu" },
    { code: "22", name: "Shizuoka" },
    { code: "23", name: "Aichi" },
    { code: "24", name: "Mie" },
    { code: "25", name: "Shiga" },
    { code: "26", name: "Kyoto" },
    { code: "27", name: "Osaka" },
    { code: "28", name: "Hyogo" },
    { code: "29", name: "Nara" },
    { code: "30", name: "Wakayama" },
    { code: "31", name: "Tottori" },
    { code: "32", name: "Shimane" },
    { code: "33", name: "Okayama" },
    { code: "34", name: "Hiroshima" },
    { code: "35", name: "Yamaguchi" },
    { code: "36", name: "Tokushima" },
    { code: "37", name: "Kagawa" },
    { code: "38", name: "Ehime" },
    { code: "39", name: "Kochi" },
    { code: "40", name: "Fukuoka" },
    { code: "41", name: "Saga" },
    { code: "42", name: "Nagasaki" },
    { code: "43", name: "Kumamoto" },
    { code: "44", name: "Oita" },
    { code: "45", name: "Miyazaki" },
    { code: "46", name: "Kagoshima" },
    { code: "47", name: "Okinawa" },
  ],

  // Argentina
  AR: [
    { code: "A", name: "Salta" },
    { code: "B", name: "Buenos Aires" },
    { code: "C", name: "Ciudad Autónoma de Buenos Aires" },
    { code: "D", name: "San Luis" },
    { code: "E", name: "Entre Ríos" },
    { code: "F", name: "La Rioja" },
    { code: "G", name: "Santiago del Estero" },
    { code: "H", name: "Chaco" },
    { code: "J", name: "San Juan" },
    { code: "K", name: "Catamarca" },
    { code: "L", name: "La Pampa" },
    { code: "M", name: "Mendoza" },
    { code: "N", name: "Misiones" },
    { code: "P", name: "Formosa" },
    { code: "Q", name: "Neuquén" },
    { code: "R", name: "Río Negro" },
    { code: "S", name: "Santa Fe" },
    { code: "T", name: "Tucumán" },
    { code: "U", name: "Chubut" },
    { code: "V", name: "Tierra del Fuego" },
    { code: "W", name: "Corrientes" },
    { code: "X", name: "Córdoba" },
    { code: "Y", name: "Jujuy" },
    { code: "Z", name: "Santa Cruz" },
  ],

  // China (mainland provinces, municipalities, autonomous regions)
  CN: [
    { code: "AH", name: "Anhui" },
    { code: "BJ", name: "Beijing" },
    { code: "CQ", name: "Chongqing" },
    { code: "FJ", name: "Fujian" },
    { code: "GS", name: "Gansu" },
    { code: "GD", name: "Guangdong" },
    { code: "GX", name: "Guangxi" },
    { code: "GZ", name: "Guizhou" },
    { code: "HI", name: "Hainan" },
    { code: "HE", name: "Hebei" },
    { code: "HL", name: "Heilongjiang" },
    { code: "HA", name: "Henan" },
    { code: "HK", name: "Hong Kong" },
    { code: "HB", name: "Hubei" },
    { code: "HN", name: "Hunan" },
    { code: "JS", name: "Jiangsu" },
    { code: "JX", name: "Jiangxi" },
    { code: "JL", name: "Jilin" },
    { code: "LN", name: "Liaoning" },
    { code: "MO", name: "Macau" },
    { code: "NM", name: "Inner Mongolia" },
    { code: "NX", name: "Ningxia" },
    { code: "QH", name: "Qinghai" },
    { code: "SN", name: "Shaanxi" },
    { code: "SD", name: "Shandong" },
    { code: "SH", name: "Shanghai" },
    { code: "SX", name: "Shanxi" },
    { code: "SC", name: "Sichuan" },
    { code: "TW", name: "Taiwan" },
    { code: "TJ", name: "Tianjin" },
    { code: "XJ", name: "Xinjiang" },
    { code: "XZ", name: "Tibet" },
    { code: "YN", name: "Yunnan" },
    { code: "ZJ", name: "Zhejiang" },
  ],

  // Indonesia
  ID: [
    { code: "AC", name: "Aceh" },
    { code: "BA", name: "Bali" },
    { code: "BT", name: "Banten" },
    { code: "BE", name: "Bengkulu" },
    { code: "GO", name: "Gorontalo" },
    { code: "JK", name: "Jakarta" },
    { code: "JA", name: "Jambi" },
    { code: "JB", name: "West Java" },
    { code: "JT", name: "Central Java" },
    { code: "JI", name: "East Java" },
    { code: "KB", name: "West Kalimantan" },
    { code: "KS", name: "South Kalimantan" },
    { code: "KT", name: "Central Kalimantan" },
    { code: "KI", name: "East Kalimantan" },
    { code: "KU", name: "North Kalimantan" },
    { code: "BB", name: "Bangka Belitung" },
    { code: "KR", name: "Riau Islands" },
    { code: "LA", name: "Lampung" },
    { code: "MA", name: "Maluku" },
    { code: "MU", name: "North Maluku" },
    { code: "NB", name: "West Nusa Tenggara" },
    { code: "NT", name: "East Nusa Tenggara" },
    { code: "PA", name: "Papua" },
    { code: "PB", name: "West Papua" },
    { code: "RI", name: "Riau" },
    { code: "SR", name: "West Sulawesi" },
    { code: "SN", name: "South Sulawesi" },
    { code: "ST", name: "Central Sulawesi" },
    { code: "SG", name: "Southeast Sulawesi" },
    { code: "SA", name: "North Sulawesi" },
    { code: "SB", name: "West Sumatra" },
    { code: "SS", name: "South Sumatra" },
    { code: "SU", name: "North Sumatra" },
    { code: "YO", name: "Yogyakarta" },
  ],

  // Malaysia
  MY: [
    { code: "01", name: "Johor" },
    { code: "02", name: "Kedah" },
    { code: "03", name: "Kelantan" },
    { code: "04", name: "Melaka" },
    { code: "05", name: "Negeri Sembilan" },
    { code: "06", name: "Pahang" },
    { code: "07", name: "Pulau Pinang" },
    { code: "08", name: "Perak" },
    { code: "09", name: "Perlis" },
    { code: "10", name: "Selangor" },
    { code: "11", name: "Terengganu" },
    { code: "12", name: "Sabah" },
    { code: "13", name: "Sarawak" },
    { code: "14", name: "Kuala Lumpur" },
    { code: "15", name: "Labuan" },
    { code: "16", name: "Putrajaya" },
  ],

  // Philippines (Regions)
  PH: [
    { code: "NCR", name: "National Capital Region" },
    { code: "01", name: "Ilocos Region" },
    { code: "02", name: "Cagayan Valley" },
    { code: "03", name: "Central Luzon" },
    { code: "05", name: "Bicol Region" },
    { code: "06", name: "Western Visayas" },
    { code: "07", name: "Central Visayas" },
    { code: "08", name: "Eastern Visayas" },
    { code: "09", name: "Zamboanga Peninsula" },
    { code: "10", name: "Northern Mindanao" },
    { code: "11", name: "Davao Region" },
    { code: "12", name: "Soccsksargen" },
    { code: "13", name: "Caraga" },
    { code: "14", name: "Bangsamoro" },
    { code: "15", name: "Cordillera Administrative Region" },
    { code: "40", name: "Calabarzon" },
    { code: "41", name: "Mimaropa" },
  ],

  // South Korea
  KR: [
    { code: "11", name: "Seoul" },
    { code: "26", name: "Busan" },
    { code: "27", name: "Daegu" },
    { code: "28", name: "Incheon" },
    { code: "29", name: "Gwangju" },
    { code: "30", name: "Daejeon" },
    { code: "31", name: "Ulsan" },
    { code: "41", name: "Gyeonggi" },
    { code: "42", name: "Gangwon" },
    { code: "43", name: "North Chungcheong" },
    { code: "44", name: "South Chungcheong" },
    { code: "45", name: "North Jeolla" },
    { code: "46", name: "South Jeolla" },
    { code: "47", name: "North Gyeongsang" },
    { code: "48", name: "South Gyeongsang" },
    { code: "49", name: "Jeju" },
    { code: "50", name: "Sejong" },
  ],

  // Thailand
  TH: [
    { code: "10", name: "Bangkok" },
    { code: "11", name: "Samut Prakan" },
    { code: "12", name: "Nonthaburi" },
    { code: "13", name: "Pathum Thani" },
    { code: "14", name: "Phra Nakhon Si Ayutthaya" },
    { code: "15", name: "Ang Thong" },
    { code: "16", name: "Lop Buri" },
    { code: "17", name: "Sing Buri" },
    { code: "18", name: "Chai Nat" },
    { code: "19", name: "Saraburi" },
    { code: "20", name: "Chon Buri" },
    { code: "21", name: "Rayong" },
    { code: "22", name: "Chanthaburi" },
    { code: "23", name: "Trat" },
    { code: "24", name: "Chachoengsao" },
    { code: "25", name: "Prachin Buri" },
    { code: "26", name: "Nakhon Nayok" },
    { code: "27", name: "Sa Kaeo" },
    { code: "30", name: "Nakhon Ratchasima" },
    { code: "31", name: "Buri Ram" },
    { code: "32", name: "Surin" },
    { code: "33", name: "Si Sa Ket" },
    { code: "34", name: "Ubon Ratchathani" },
    { code: "35", name: "Yasothon" },
    { code: "36", name: "Chaiyaphum" },
    { code: "37", name: "Amnat Charoen" },
    { code: "38", name: "Bueng Kan" },
    { code: "39", name: "Nong Bua Lam Phu" },
    { code: "40", name: "Khon Kaen" },
    { code: "41", name: "Udon Thani" },
    { code: "42", name: "Loei" },
    { code: "46", name: "Kalasin" },
    { code: "50", name: "Chiang Mai" },
    { code: "51", name: "Lamphun" },
    { code: "52", name: "Lampang" },
    { code: "54", name: "Phrae" },
    { code: "56", name: "Phayao" },
    { code: "57", name: "Chiang Rai" },
    { code: "58", name: "Mae Hong Son" },
    { code: "62", name: "Kamphaeng Phet" },
    { code: "63", name: "Tak" },
    { code: "64", name: "Sukhothai" },
    { code: "65", name: "Phitsanulok" },
    { code: "66", name: "Phichit" },
    { code: "67", name: "Phetchabun" },
    { code: "70", name: "Ratchaburi" },
    { code: "71", name: "Kanchanaburi" },
    { code: "72", name: "Suphan Buri" },
    { code: "74", name: "Samut Sakhon" },
    { code: "75", name: "Samut Songkhram" },
    { code: "76", name: "Phetchaburi" },
    { code: "80", name: "Nakhon Si Thammarat" },
    { code: "81", name: "Krabi" },
    { code: "82", name: "Phangnga" },
    { code: "83", name: "Phuket" },
    { code: "84", name: "Surat Thani" },
    { code: "85", name: "Ranong" },
    { code: "86", name: "Chumphon" },
    { code: "90", name: "Songkhla" },
    { code: "91", name: "Satun" },
    { code: "92", name: "Trang" },
    { code: "93", name: "Phatthalung" },
    { code: "94", name: "Pattani" },
    { code: "95", name: "Yala" },
    { code: "96", name: "Narathiwat" },
    { code: "S", name: "Pattaya" },
  ],

  // Vietnam (Provinces and Cities)
  // NOTE: faithful port of the upstream billing source, which labels code '20' as
  // 'Lào Cai' — a duplicate of code '02'. Codes are unique so selection/keys are correct;
  // only the two visible labels read identically. Left as-ported (correcting code '20'
  // would mean inventing an authoritative province name we can't derive from the source);
  // flagged for an upstream data fix.
  VN: [
    { code: "01", name: "Lai Châu" },
    { code: "02", name: "Lào Cai" },
    { code: "04", name: "Cao Bằng" },
    { code: "06", name: "Yên Bái" },
    { code: "08", name: "Tuyên Quang" },
    { code: "10", name: "Lạng Sơn" },
    { code: "11", name: "Điện Biên" },
    { code: "12", name: "Sơn La" },
    { code: "14", name: "Hòa Bình" },
    { code: "15", name: "Hà Giang" },
    { code: "17", name: "Bắc Kạn" },
    { code: "19", name: "Thái Nguyên" },
    { code: "20", name: "Lào Cai" },
    { code: "22", name: "Quảng Ninh" },
    { code: "24", name: "Bắc Giang" },
    { code: "25", name: "Phú Thọ" },
    { code: "26", name: "Vĩnh Phúc" },
    { code: "27", name: "Bắc Ninh" },
    { code: "30", name: "Hải Dương" },
    { code: "31", name: "Hải Phòng" },
    { code: "33", name: "Hưng Yên" },
    { code: "34", name: "Thái Bình" },
    { code: "35", name: "Hà Nam" },
    { code: "36", name: "Nam Định" },
    { code: "37", name: "Ninh Bình" },
    { code: "HN", name: "Hà Nội" },
    { code: "38", name: "Thanh Hóa" },
    { code: "40", name: "Nghệ An" },
    { code: "42", name: "Hà Tĩnh" },
    { code: "44", name: "Quảng Bình" },
    { code: "45", name: "Quảng Trị" },
    { code: "46", name: "Thừa Thiên Huế" },
    { code: "48", name: "Đà Nẵng" },
    { code: "49", name: "Quảng Nam" },
    { code: "51", name: "Quảng Ngãi" },
    { code: "52", name: "Bình Định" },
    { code: "54", name: "Phú Yên" },
    { code: "56", name: "Khánh Hòa" },
    { code: "58", name: "Ninh Thuận" },
    { code: "60", name: "Bình Thuận" },
    { code: "62", name: "Kon Tum" },
    { code: "64", name: "Gia Lai" },
    { code: "66", name: "Đắk Lắk" },
    { code: "67", name: "Đắk Nông" },
    { code: "68", name: "Lâm Đồng" },
    { code: "70", name: "Bình Phước" },
    { code: "72", name: "Tây Ninh" },
    { code: "74", name: "Bình Dương" },
    { code: "75", name: "Đồng Nai" },
    { code: "77", name: "Bà Rịa - Vũng Tàu" },
    { code: "SG", name: "Hồ Chí Minh" },
    { code: "79", name: "Long An" },
    { code: "80", name: "Tiền Giang" },
    { code: "82", name: "Bến Tre" },
    { code: "83", name: "Trà Vinh" },
    { code: "84", name: "Vĩnh Long" },
    { code: "86", name: "Đồng Tháp" },
    { code: "87", name: "An Giang" },
    { code: "89", name: "Kiên Giang" },
    { code: "91", name: "Cà Mau" },
    { code: "92", name: "Bạc Liêu" },
    { code: "CT", name: "Cần Thơ" },
  ],

  // Pakistan
  PK: [
    { code: "BA", name: "Balochistan" },
    { code: "KP", name: "Khyber Pakhtunkhwa" },
    { code: "PB", name: "Punjab" },
    { code: "SD", name: "Sindh" },
    { code: "IS", name: "Islamabad" },
    { code: "JK", name: "Azad Jammu and Kashmir" },
    { code: "GB", name: "Gilgit-Baltistan" },
  ],

  // Bangladesh
  BD: [
    { code: "A", name: "Barishal" },
    { code: "B", name: "Chattogram" },
    { code: "C", name: "Dhaka" },
    { code: "D", name: "Khulna" },
    { code: "E", name: "Rajshahi" },
    { code: "F", name: "Rangpur" },
    { code: "G", name: "Sylhet" },
    { code: "H", name: "Mymensingh" },
  ],

  // Colombia
  CO: [
    { code: "AMA", name: "Amazonas" },
    { code: "ANT", name: "Antioquia" },
    { code: "ARA", name: "Arauca" },
    { code: "ATL", name: "Atlántico" },
    { code: "BOL", name: "Bolívar" },
    { code: "BOY", name: "Boyacá" },
    { code: "CAL", name: "Caldas" },
    { code: "CAQ", name: "Caquetá" },
    { code: "CAS", name: "Casanare" },
    { code: "CAU", name: "Cauca" },
    { code: "CES", name: "Cesar" },
    { code: "CHO", name: "Chocó" },
    { code: "COR", name: "Córdoba" },
    { code: "CUN", name: "Cundinamarca" },
    { code: "DC", name: "Bogotá D.C." },
    { code: "GUA", name: "Guainía" },
    { code: "GUV", name: "Guaviare" },
    { code: "HUI", name: "Huila" },
    { code: "LAG", name: "La Guajira" },
    { code: "MAG", name: "Magdalena" },
    { code: "MET", name: "Meta" },
    { code: "NAR", name: "Nariño" },
    { code: "NSA", name: "Norte de Santander" },
    { code: "PUT", name: "Putumayo" },
    { code: "QUI", name: "Quindío" },
    { code: "RIS", name: "Risaralda" },
    { code: "SAN", name: "Santander" },
    { code: "SAP", name: "San Andrés y Providencia" },
    { code: "SUC", name: "Sucre" },
    { code: "TOL", name: "Tolima" },
    { code: "VAC", name: "Valle del Cauca" },
    { code: "VAU", name: "Vaupés" },
    { code: "VID", name: "Vichada" },
  ],

  // Chile
  CL: [
    { code: "AI", name: "Aisén" },
    { code: "AN", name: "Antofagasta" },
    { code: "AP", name: "Arica y Parinacota" },
    { code: "AR", name: "Araucanía" },
    { code: "AT", name: "Atacama" },
    { code: "BI", name: "Biobío" },
    { code: "CO", name: "Coquimbo" },
    { code: "LI", name: "Libertador General Bernardo O'Higgins" },
    { code: "LL", name: "Los Lagos" },
    { code: "LR", name: "Los Ríos" },
    { code: "MA", name: "Magallanes" },
    { code: "ML", name: "Maule" },
    { code: "NB", name: "Ñuble" },
    { code: "RM", name: "Región Metropolitana de Santiago" },
    { code: "TA", name: "Tarapacá" },
    { code: "VS", name: "Valparaíso" },
  ],

  // Peru
  PE: [
    { code: "AMA", name: "Amazonas" },
    { code: "ANC", name: "Ancash" },
    { code: "APU", name: "Apurímac" },
    { code: "ARE", name: "Arequipa" },
    { code: "AYA", name: "Ayacucho" },
    { code: "CAJ", name: "Cajamarca" },
    { code: "CAL", name: "Callao" },
    { code: "CUS", name: "Cusco" },
    { code: "HUV", name: "Huancavelica" },
    { code: "HUC", name: "Huánuco" },
    { code: "ICA", name: "Ica" },
    { code: "JUN", name: "Junín" },
    { code: "LAL", name: "La Libertad" },
    { code: "LAM", name: "Lambayeque" },
    { code: "LIM", name: "Lima" },
    { code: "LOR", name: "Loreto" },
    { code: "MDD", name: "Madre de Dios" },
    { code: "MOQ", name: "Moquegua" },
    { code: "PAS", name: "Pasco" },
    { code: "PIU", name: "Piura" },
    { code: "PUN", name: "Puno" },
    { code: "SAM", name: "San Martín" },
    { code: "TAC", name: "Tacna" },
    { code: "TUM", name: "Tumbes" },
    { code: "UCA", name: "Ucayali" },
  ],

  // South Africa
  ZA: [
    { code: "EC", name: "Eastern Cape" },
    { code: "FS", name: "Free State" },
    { code: "GP", name: "Gauteng" },
    { code: "KZN", name: "KwaZulu-Natal" },
    { code: "LP", name: "Limpopo" },
    { code: "MP", name: "Mpumalanga" },
    { code: "NC", name: "Northern Cape" },
    { code: "NW", name: "North West" },
    { code: "WC", name: "Western Cape" },
  ],

  // Nigeria
  NG: [
    { code: "AB", name: "Abia" },
    { code: "AD", name: "Adamawa" },
    { code: "AK", name: "Akwa Ibom" },
    { code: "AN", name: "Anambra" },
    { code: "BA", name: "Bauchi" },
    { code: "BY", name: "Bayelsa" },
    { code: "BE", name: "Benue" },
    { code: "BO", name: "Borno" },
    { code: "CR", name: "Cross River" },
    { code: "DE", name: "Delta" },
    { code: "EB", name: "Ebonyi" },
    { code: "ED", name: "Edo" },
    { code: "EK", name: "Ekiti" },
    { code: "EN", name: "Enugu" },
    { code: "FC", name: "Federal Capital Territory" },
    { code: "GO", name: "Gombe" },
    { code: "IM", name: "Imo" },
    { code: "JI", name: "Jigawa" },
    { code: "KD", name: "Kaduna" },
    { code: "KN", name: "Kano" },
    { code: "KT", name: "Katsina" },
    { code: "KE", name: "Kebbi" },
    { code: "KO", name: "Kogi" },
    { code: "KW", name: "Kwara" },
    { code: "LA", name: "Lagos" },
    { code: "NA", name: "Nasarawa" },
    { code: "NI", name: "Niger" },
    { code: "OG", name: "Ogun" },
    { code: "ON", name: "Ondo" },
    { code: "OS", name: "Osun" },
    { code: "OY", name: "Oyo" },
    { code: "PL", name: "Plateau" },
    { code: "RI", name: "Rivers" },
    { code: "SO", name: "Sokoto" },
    { code: "TA", name: "Taraba" },
    { code: "YO", name: "Yobe" },
    { code: "ZA", name: "Zamfara" },
  ],

  // New Zealand
  NZ: [
    { code: "AUK", name: "Auckland" },
    { code: "BOP", name: "Bay of Plenty" },
    { code: "CAN", name: "Canterbury" },
    { code: "GIS", name: "Gisborne" },
    { code: "HKB", name: "Hawke's Bay" },
    { code: "MBH", name: "Marlborough" },
    { code: "MWT", name: "Manawatu-Wanganui" },
    { code: "NSN", name: "Nelson" },
    { code: "NTL", name: "Northland" },
    { code: "OTA", name: "Otago" },
    { code: "STL", name: "Southland" },
    { code: "TAS", name: "Tasman" },
    { code: "TKI", name: "Taranaki" },
    { code: "WGN", name: "Wellington" },
    { code: "WKO", name: "Waikato" },
    { code: "WTC", name: "West Coast" },
  ],

  // Afghanistan
  AF: [
    { code: "BDS", name: "Badakhshan" },
    { code: "BDG", name: "Badghis" },
    { code: "BGL", name: "Baghlan" },
    { code: "BAL", name: "Balkh" },
    { code: "BAM", name: "Bamyan" },
    { code: "DAY", name: "Daykundi" },
    { code: "FRA", name: "Farah" },
    { code: "FYB", name: "Faryab" },
    { code: "GHA", name: "Ghazni" },
    { code: "GHO", name: "Ghor" },
    { code: "HEL", name: "Helmand" },
    { code: "HER", name: "Herat" },
    { code: "JOW", name: "Jowzjan" },
    { code: "KAB", name: "Kabul" },
    { code: "KAN", name: "Kandahar" },
    { code: "KAP", name: "Kapisa" },
    { code: "KHO", name: "Khost" },
    { code: "KNR", name: "Kunar" },
    { code: "KDZ", name: "Kunduz" },
    { code: "LAG", name: "Laghman" },
    { code: "LOG", name: "Logar" },
    { code: "NAN", name: "Nangarhar" },
    { code: "NIM", name: "Nimruz" },
    { code: "NUR", name: "Nuristan" },
    { code: "PIA", name: "Paktia" },
    { code: "PKA", name: "Paktika" },
    { code: "PAN", name: "Panjshir" },
    { code: "PAR", name: "Parwan" },
    { code: "SAM", name: "Samangan" },
    { code: "SAR", name: "Sar-e Pol" },
    { code: "TAK", name: "Takhar" },
    { code: "URU", name: "Uruzgan" },
    { code: "WAR", name: "Wardak" },
    { code: "ZAB", name: "Zabul" },
  ],

  // Bolivia
  BO: [
    { code: "B", name: "Beni" },
    { code: "H", name: "Chuquisaca" },
    { code: "C", name: "Cochabamba" },
    { code: "L", name: "La Paz" },
    { code: "O", name: "Oruro" },
    { code: "N", name: "Pando" },
    { code: "P", name: "Potosí" },
    { code: "S", name: "Santa Cruz" },
    { code: "T", name: "Tarija" },
  ],

  // Ecuador
  EC: [
    { code: "A", name: "Azuay" },
    { code: "B", name: "Bolívar" },
    { code: "F", name: "Cañar" },
    { code: "C", name: "Carchi" },
    { code: "H", name: "Chimborazo" },
    { code: "X", name: "Cotopaxi" },
    { code: "O", name: "El Oro" },
    { code: "E", name: "Esmeraldas" },
    { code: "W", name: "Galápagos" },
    { code: "G", name: "Guayas" },
    { code: "I", name: "Imbabura" },
    { code: "L", name: "Loja" },
    { code: "R", name: "Los Ríos" },
    { code: "M", name: "Manabí" },
    { code: "S", name: "Morona-Santiago" },
    { code: "N", name: "Napo" },
    { code: "D", name: "Orellana" },
    { code: "Y", name: "Pastaza" },
    { code: "P", name: "Pichincha" },
    { code: "SE", name: "Santa Elena" },
    { code: "SD", name: "Santo Domingo de los Tsáchilas" },
    { code: "U", name: "Sucumbíos" },
    { code: "T", name: "Tungurahua" },
    { code: "Z", name: "Zamora-Chinchipe" },
  ],

  // Egypt
  EG: [
    { code: "C", name: "Cairo" },
    { code: "ALX", name: "Alexandria" },
    { code: "DK", name: "Dakahlia" },
    { code: "BA", name: "Red Sea" },
    { code: "BH", name: "Beheira" },
    { code: "FYM", name: "Faiyum" },
    { code: "GH", name: "Gharbia" },
    { code: "GZ", name: "Giza" },
    { code: "IS", name: "Ismailia" },
    { code: "LX", name: "Luxor" },
    { code: "WAD", name: "New Valley" },
    { code: "SHR", name: "Al Sharqia" },
    { code: "ASN", name: "Aswan" },
    { code: "AST", name: "Asyut" },
    { code: "BNS", name: "Beni Suef" },
    { code: "PTS", name: "Port Said" },
    { code: "DT", name: "Damietta" },
    { code: "JS", name: "South Sinai" },
    { code: "KFS", name: "Kafr el-Sheikh" },
    { code: "KB", name: "Qalyubia" },
    { code: "KN", name: "Qena" },
    { code: "SIN", name: "North Sinai" },
    { code: "SUZ", name: "Suez" },
    { code: "SHG", name: "Sohag" },
    { code: "MN", name: "Minya" },
    { code: "MNF", name: "Monufia" },
    { code: "MT", name: "Matruh" },
  ],

  // Ethiopia
  ET: [
    { code: "AA", name: "Addis Ababa" },
    { code: "AF", name: "Afar" },
    { code: "AM", name: "Amhara" },
    { code: "BE", name: "Benshangul-Gumuz" },
    { code: "DD", name: "Dire Dawa" },
    { code: "GA", name: "Gambela Peoples" },
    { code: "HA", name: "Harari People" },
    { code: "OR", name: "Oromia" },
    { code: "SI", name: "Sidama" },
    { code: "SO", name: "Somali" },
    { code: "SN", name: "Southern Nations, Nationalities, and Peoples" },
    { code: "SW", name: "Southwest Ethiopia Peoples" },
    { code: "TI", name: "Tigray" },
  ],

  // Iran
  IR: [
    { code: "32", name: "Alborz" },
    { code: "03", name: "Ardabil" },
    { code: "02", name: "West Azerbaijan" },
    { code: "01", name: "East Azerbaijan" },
    { code: "06", name: "Bushehr" },
    { code: "08", name: "Chaharmahal and Bakhtiari" },
    { code: "04", name: "Isfahan" },
    { code: "14", name: "Fars" },
    { code: "19", name: "Gilan" },
    { code: "27", name: "Golestan" },
    { code: "24", name: "Hamadan" },
    { code: "23", name: "Hormozgan" },
    { code: "05", name: "Ilam" },
    { code: "15", name: "Kerman" },
    { code: "17", name: "Kermanshah" },
    { code: "29", name: "South Khorasan" },
    { code: "30", name: "Razavi Khorasan" },
    { code: "31", name: "North Khorasan" },
    { code: "10", name: "Khuzestan" },
    { code: "18", name: "Kohgiluyeh and Boyer-Ahmad" },
    { code: "16", name: "Kurdistan" },
    { code: "20", name: "Lorestan" },
    { code: "22", name: "Markazi" },
    { code: "21", name: "Mazandaran" },
    { code: "28", name: "Qazvin" },
    { code: "26", name: "Qom" },
    { code: "12", name: "Semnan" },
    { code: "13", name: "Sistan and Baluchestan" },
    { code: "07", name: "Tehran" },
    { code: "25", name: "Yazd" },
    { code: "11", name: "Zanjan" },
  ],

  // Kazakhstan
  KZ: [
    { code: "75", name: "Almaty" },
    { code: "71", name: "Astana" },
    { code: "79", name: "Shymkent" },
    { code: "10", name: "Abai" },
    { code: "11", name: "Aqmola" },
    { code: "15", name: "Aqtöbe" },
    { code: "19", name: "Almaty Region" },
    { code: "23", name: "Atyrau" },
    { code: "27", name: "West Kazakhstan" },
    { code: "31", name: "Zhambyl" },
    { code: "33", name: "Zhetisu" },
    { code: "35", name: "Karagandy" },
    { code: "39", name: "Kostanay" },
    { code: "43", name: "Qyzylorda" },
    { code: "47", name: "Mangystau" },
    { code: "55", name: "Pavlodar" },
    { code: "59", name: "North Kazakhstan" },
    { code: "61", name: "Turkistan" },
    { code: "62", name: "Ulytau" },
    { code: "63", name: "East Kazakhstan" },
  ],

  // Kenya
  KE: [
    { code: "01", name: "Baringo" },
    { code: "02", name: "Bomet" },
    { code: "03", name: "Bungoma" },
    { code: "04", name: "Busia" },
    { code: "05", name: "Elgeyo/Marakwet" },
    { code: "06", name: "Embu" },
    { code: "07", name: "Garissa" },
    { code: "08", name: "Homa Bay" },
    { code: "09", name: "Isiolo" },
    { code: "10", name: "Kajiado" },
    { code: "11", name: "Kakamega" },
    { code: "12", name: "Kericho" },
    { code: "13", name: "Kiambu" },
    { code: "14", name: "Kilifi" },
    { code: "15", name: "Kirinyaga" },
    { code: "16", name: "Kisii" },
    { code: "17", name: "Kisumu" },
    { code: "18", name: "Kitui" },
    { code: "19", name: "Kwale" },
    { code: "20", name: "Laikipia" },
    { code: "21", name: "Lamu" },
    { code: "22", name: "Machakos" },
    { code: "23", name: "Makueni" },
    { code: "24", name: "Mandera" },
    { code: "25", name: "Marsabit" },
    { code: "26", name: "Meru" },
    { code: "27", name: "Migori" },
    { code: "28", name: "Mombasa" },
    { code: "29", name: "Murang'a" },
    { code: "30", name: "Nairobi City" },
    { code: "31", name: "Nakuru" },
    { code: "32", name: "Nandi" },
    { code: "33", name: "Narok" },
    { code: "34", name: "Nyamira" },
    { code: "35", name: "Nyandarua" },
    { code: "36", name: "Nyeri" },
    { code: "37", name: "Samburu" },
    { code: "38", name: "Siaya" },
    { code: "39", name: "Taita-Taveta" },
    { code: "40", name: "Tana River" },
    { code: "41", name: "Tharaka-Nithi" },
    { code: "42", name: "Trans-Nzoia" },
    { code: "43", name: "Turkana" },
    { code: "44", name: "Uasin Gishu" },
    { code: "45", name: "Vihiga" },
    { code: "46", name: "Wajir" },
    { code: "47", name: "West Pokot" },
  ],

  // Morocco
  MA: [
    { code: "01", name: "Tanger-Tétouan-Al Hoceïma" },
    { code: "02", name: "L'Oriental" },
    { code: "03", name: "Fès-Meknès" },
    { code: "04", name: "Rabat-Salé-Kénitra" },
    { code: "05", name: "Béni Mellal-Khénifra" },
    { code: "06", name: "Casablanca-Settat" },
    { code: "07", name: "Marrakech-Safi" },
    { code: "08", name: "Drâa-Tafilalet" },
    { code: "09", name: "Souss-Massa" },
    { code: "10", name: "Guelmim-Oued Noun" },
    { code: "11", name: "Laâyoune-Sakia El Hamra" },
    { code: "12", name: "Dakhla-Oued Ed-Dahab" },
  ],

  // Myanmar
  MM: [
    { code: "01", name: "Ayeyarwady Region" },
    { code: "02", name: "Bago Region" },
    { code: "03", name: "Magway Region" },
    { code: "04", name: "Mandalay Region" },
    { code: "05", name: "Tanintharyi Region" },
    { code: "06", name: "Yangon Region" },
    { code: "07", name: "Sagaing Region" },
    { code: "11", name: "Kachin State" },
    { code: "12", name: "Kayah State" },
    { code: "13", name: "Kayin State" },
    { code: "14", name: "Chin State" },
    { code: "15", name: "Mon State" },
    { code: "16", name: "Rakhine State" },
    { code: "17", name: "Shan State" },
    { code: "18", name: "Nay Pyi Taw Union Territory" },
  ],

  // Nepal
  NP: [
    { code: "P1", name: "Koshi" },
    { code: "P2", name: "Madhesh" },
    { code: "P3", name: "Bagmati" },
    { code: "P4", name: "Gandaki" },
    { code: "P5", name: "Lumbini" },
    { code: "P6", name: "Karnali" },
    { code: "P7", name: "Sudurpashchim" },
  ],

  // Russia (major federal subjects)
  RU: [
    { code: "AD", name: "Republic of Adygea" },
    { code: "AL", name: "Altai Republic" },
    { code: "BA", name: "Republic of Bashkortostan" },
    { code: "BU", name: "Republic of Buryatia" },
    { code: "CE", name: "Chechen Republic" },
    { code: "CU", name: "Chuvash Republic" },
    { code: "DA", name: "Republic of Dagestan" },
    { code: "IN", name: "Republic of Ingushetia" },
    { code: "KB", name: "Republic of Kabardino-Balkaria" },
    { code: "KL", name: "Republic of Kalmykia" },
    { code: "KC", name: "Karachay-Cherkessia" },
    { code: "KR", name: "Republic of Karelia" },
    { code: "KK", name: "Republic of Khakassia" },
    { code: "ME", name: "Mari El" },
    { code: "MO", name: "Republic of Mordovia" },
    { code: "SA", name: "Sakha Republic" },
    { code: "SE", name: "North Ossetia-Alania" },
    { code: "TA", name: "Republic of Tatarstan" },
    { code: "TY", name: "Republic of Tuva" },
    { code: "UD", name: "Udmurt Republic" },
    { code: "ALT", name: "Altai Krai" },
    { code: "KAM", name: "Kamchatka Krai" },
    { code: "KHA", name: "Khabarovsk Krai" },
    { code: "KDA", name: "Krasnodar Krai" },
    { code: "KYA", name: "Krasnoyarsk Krai" },
    { code: "PER", name: "Perm Krai" },
    { code: "PRI", name: "Primorsky Krai" },
    { code: "STA", name: "Stavropol Krai" },
    { code: "ZAB", name: "Zabaykalsky Krai" },
    { code: "AMU", name: "Amur Oblast" },
    { code: "ARK", name: "Arkhangelsk Oblast" },
    { code: "AST", name: "Astrakhan Oblast" },
    { code: "BEL", name: "Belgorod Oblast" },
    { code: "BRY", name: "Bryansk Oblast" },
    { code: "CHE", name: "Chelyabinsk Oblast" },
    { code: "IRK", name: "Irkutsk Oblast" },
    { code: "IVA", name: "Ivanovo Oblast" },
    { code: "KGD", name: "Kaliningrad Oblast" },
    { code: "KLU", name: "Kaluga Oblast" },
    { code: "KEM", name: "Kemerovo Oblast" },
    { code: "KIR", name: "Kirov Oblast" },
    { code: "KOS", name: "Kostroma Oblast" },
    { code: "KGN", name: "Kurgan Oblast" },
    { code: "KRS", name: "Kursk Oblast" },
    { code: "LEN", name: "Leningrad Oblast" },
    { code: "LIP", name: "Lipetsk Oblast" },
    { code: "MAG", name: "Magadan Oblast" },
    { code: "MOS", name: "Moscow Oblast" },
    { code: "MUR", name: "Murmansk Oblast" },
    { code: "NIZ", name: "Nizhny Novgorod Oblast" },
    { code: "NGR", name: "Novgorod Oblast" },
    { code: "NVS", name: "Novosibirsk Oblast" },
    { code: "OMS", name: "Omsk Oblast" },
    { code: "ORE", name: "Orenburg Oblast" },
    { code: "ORL", name: "Oryol Oblast" },
    { code: "PNZ", name: "Penza Oblast" },
    { code: "PSK", name: "Pskov Oblast" },
    { code: "ROS", name: "Rostov Oblast" },
    { code: "RYA", name: "Ryazan Oblast" },
    { code: "SAK", name: "Sakhalin Oblast" },
    { code: "SAM", name: "Samara Oblast" },
    { code: "SAR", name: "Saratov Oblast" },
    { code: "SMO", name: "Smolensk Oblast" },
    { code: "SVE", name: "Sverdlovsk Oblast" },
    { code: "TAM", name: "Tambov Oblast" },
    { code: "TOM", name: "Tomsk Oblast" },
    { code: "TUL", name: "Tula Oblast" },
    { code: "TVE", name: "Tver Oblast" },
    { code: "TYU", name: "Tyumen Oblast" },
    { code: "ULY", name: "Ulyanovsk Oblast" },
    { code: "VLA", name: "Vladimir Oblast" },
    { code: "VGG", name: "Volgograd Oblast" },
    { code: "VLG", name: "Vologda Oblast" },
    { code: "VOR", name: "Voronezh Oblast" },
    { code: "YAR", name: "Yaroslavl Oblast" },
    { code: "MOW", name: "Moscow" },
    { code: "SPE", name: "Saint Petersburg" },
    { code: "YEV", name: "Jewish Autonomous Oblast" },
  ],

  // Saudi Arabia
  SA: [
    { code: "01", name: "Ar Riyāḍ" },
    { code: "02", name: "Makkah al Mukarramah" },
    { code: "03", name: "Al Madīnah al Munawwarah" },
    { code: "04", name: "Ash Sharqīyah" },
    { code: "05", name: "Al Qaṣīm" },
    { code: "06", name: "Ḥā'il" },
    { code: "07", name: "Tabūk" },
    { code: "08", name: "Al Ḩudūd ash Shamālīyah" },
    { code: "09", name: "Jāzān" },
    { code: "10", name: "Najrān" },
    { code: "11", name: "Al Bāḥah" },
    { code: "12", name: "Al Jawf" },
    { code: "14", name: "ʿAsīr" },
  ],

  // Ukraine
  UA: [
    { code: "05", name: "Vinnytsia Oblast" },
    { code: "07", name: "Volyn Oblast" },
    { code: "09", name: "Luhansk Oblast" },
    { code: "12", name: "Dnipropetrovsk Oblast" },
    { code: "14", name: "Donetsk Oblast" },
    { code: "18", name: "Zhytomyr Oblast" },
    { code: "21", name: "Zakarpattia Oblast" },
    { code: "23", name: "Zaporizhzhia Oblast" },
    { code: "26", name: "Ivano-Frankivsk Oblast" },
    { code: "30", name: "Kyiv" },
    { code: "32", name: "Kyiv Oblast" },
    { code: "35", name: "Kirovohrad Oblast" },
    { code: "40", name: "Sevastopol" },
    { code: "43", name: "Autonomous Republic of Crimea" },
    { code: "46", name: "Lviv Oblast" },
    { code: "48", name: "Mykolaiv Oblast" },
    { code: "51", name: "Odesa Oblast" },
    { code: "53", name: "Poltava Oblast" },
    { code: "56", name: "Rivne Oblast" },
    { code: "59", name: "Sumy Oblast" },
    { code: "61", name: "Ternopil Oblast" },
    { code: "63", name: "Kharkiv Oblast" },
    { code: "65", name: "Kherson Oblast" },
    { code: "68", name: "Khmelnytskyi Oblast" },
    { code: "71", name: "Cherkasy Oblast" },
    { code: "74", name: "Chernihiv Oblast" },
    { code: "77", name: "Chernivtsi Oblast" },
  ],

  // Uruguay
  UY: [
    { code: "AR", name: "Artigas" },
    { code: "CA", name: "Canelones" },
    { code: "CL", name: "Cerro Largo" },
    { code: "CO", name: "Colonia" },
    { code: "DU", name: "Durazno" },
    { code: "FS", name: "Flores" },
    { code: "FD", name: "Florida" },
    { code: "LA", name: "Lavalleja" },
    { code: "MA", name: "Maldonado" },
    { code: "MO", name: "Montevideo" },
    { code: "PA", name: "Paysandú" },
    { code: "RN", name: "Río Negro" },
    { code: "RV", name: "Rivera" },
    { code: "RO", name: "Rocha" },
    { code: "SA", name: "Salto" },
    { code: "SJ", name: "San José" },
    { code: "SO", name: "Soriano" },
    { code: "TA", name: "Tacuarembó" },
    { code: "TT", name: "Treinta y Tres" },
  ],

  // Venezuela
  VE: [
    { code: "A", name: "Distrito Capital" },
    { code: "B", name: "Anzoátegui" },
    { code: "C", name: "Apure" },
    { code: "D", name: "Aragua" },
    { code: "E", name: "Barinas" },
    { code: "F", name: "Bolívar" },
    { code: "G", name: "Carabobo" },
    { code: "H", name: "Cojedes" },
    { code: "I", name: "Falcón" },
    { code: "J", name: "Guárico" },
    { code: "K", name: "Lara" },
    { code: "L", name: "Mérida" },
    { code: "M", name: "Miranda" },
    { code: "N", name: "Monagas" },
    { code: "O", name: "Nueva Esparta" },
    { code: "P", name: "Portuguesa" },
    { code: "R", name: "Sucre" },
    { code: "S", name: "Táchira" },
    { code: "T", name: "Trujillo" },
    { code: "U", name: "Yaracuy" },
    { code: "V", name: "Zulia" },
    { code: "W", name: "Dependencias Federales" },
    { code: "X", name: "Vargas" },
    { code: "Y", name: "Delta Amacuro" },
    { code: "Z", name: "Amazonas" },
  ],

  // Turkey
  TR: [
    { code: "01", name: "Adana" },
    { code: "02", name: "Adıyaman" },
    { code: "03", name: "Afyonkarahisar" },
    { code: "04", name: "Ağrı" },
    { code: "05", name: "Amasya" },
    { code: "06", name: "Ankara" },
    { code: "07", name: "Antalya" },
    { code: "08", name: "Artvin" },
    { code: "09", name: "Aydın" },
    { code: "10", name: "Balıkesir" },
    { code: "11", name: "Bilecik" },
    { code: "12", name: "Bingöl" },
    { code: "13", name: "Bitlis" },
    { code: "14", name: "Bolu" },
    { code: "15", name: "Burdur" },
    { code: "16", name: "Bursa" },
    { code: "17", name: "Çanakkale" },
    { code: "18", name: "Çankırı" },
    { code: "19", name: "Çorum" },
    { code: "20", name: "Denizli" },
    { code: "21", name: "Diyarbakır" },
    { code: "22", name: "Edirne" },
    { code: "23", name: "Elazığ" },
    { code: "24", name: "Erzincan" },
    { code: "25", name: "Erzurum" },
    { code: "26", name: "Eskişehir" },
    { code: "27", name: "Gaziantep" },
    { code: "28", name: "Giresun" },
    { code: "29", name: "Gümüşhane" },
    { code: "30", name: "Hakkâri" },
    { code: "31", name: "Hatay" },
    { code: "32", name: "Isparta" },
    { code: "33", name: "Mersin" },
    { code: "34", name: "İstanbul" },
    { code: "35", name: "İzmir" },
    { code: "36", name: "Kars" },
    { code: "37", name: "Kastamonu" },
    { code: "38", name: "Kayseri" },
    { code: "39", name: "Kırklareli" },
    { code: "40", name: "Kırşehir" },
    { code: "41", name: "Kocaeli" },
    { code: "42", name: "Konya" },
    { code: "43", name: "Kütahya" },
    { code: "44", name: "Malatya" },
    { code: "45", name: "Manisa" },
    { code: "46", name: "Kahramanmaraş" },
    { code: "47", name: "Mardin" },
    { code: "48", name: "Muğla" },
    { code: "49", name: "Muş" },
    { code: "50", name: "Nevşehir" },
    { code: "51", name: "Niğde" },
    { code: "52", name: "Ordu" },
    { code: "53", name: "Rize" },
    { code: "54", name: "Sakarya" },
    { code: "55", name: "Samsun" },
    { code: "56", name: "Siirt" },
    { code: "57", name: "Sinop" },
    { code: "58", name: "Sivas" },
    { code: "59", name: "Tekirdağ" },
    { code: "60", name: "Tokat" },
    { code: "61", name: "Trabzon" },
    { code: "62", name: "Tunceli" },
    { code: "63", name: "Şanlıurfa" },
    { code: "64", name: "Uşak" },
    { code: "65", name: "Van" },
    { code: "66", name: "Yozgat" },
    { code: "67", name: "Zonguldak" },
    { code: "68", name: "Aksaray" },
    { code: "69", name: "Bayburt" },
    { code: "70", name: "Karaman" },
    { code: "71", name: "Kırıkkale" },
    { code: "72", name: "Batman" },
    { code: "73", name: "Şırnak" },
    { code: "74", name: "Bartın" },
    { code: "75", name: "Ardahan" },
    { code: "76", name: "Iğdır" },
    { code: "77", name: "Yalova" },
    { code: "78", name: "Karabük" },
    { code: "79", name: "Kilis" },
    { code: "80", name: "Osmaniye" },
    { code: "81", name: "Düzce" },
  ],
};
