export const designMdConfig = {
  schemaVersion: 1,
  version: "2.1",
  name: "VegaStack",
  description:
    "Canonical VegaStack design contract. Light and dark are co-primary themes; token values are resolved from the current DTCG sources.",
  tokenSources: {
    primitives: "packages/design-tokens/tokens/primitives.tokens.json",
    light: "packages/design-tokens/tokens/semantic.tokens.json",
    dark: "packages/design-tokens/tokens/semantic.dark.tokens.json",
  },
  sourceManifest: "docs/research/design-md-audit/source-manifest.json",
  outputs: {
    canonical: "design.md",
    public: "apps/docs/public/design.md",
  },
  foundationTables: {
    radius: {
      path: "apps/docs/content/docs/foundations/radius.mdx",
      tokens: [
        "radius-xs",
        "radius-sharp",
        "radius-sm",
        "radius-md",
        "radius-lg",
        "radius",
      ],
    },
    elevation: {
      path: "apps/docs/content/docs/foundations/elevation.mdx",
      tokens: ["shadow-overlay", "shadow-lit"],
    },
    charts: {
      path: "apps/docs/content/docs/foundations/colors.mdx",
      tokens: [
        "chart-1",
        "chart-2",
        "chart-3",
        "chart-4",
        "chart-5",
        "chart-6",
        "chart-7",
        "chart-8",
      ],
    },
    typography: {
      path: "apps/docs/content/docs/foundations/typography.mdx",
      tokens: [
        "type-product-base",
        "type-doc-base",
        "text-label",
        "text-strong",
        "text-label-sm",
        "text-code",
        "text-code-sm",
      ],
    },
  },
  recipes: {
    "button-primary": {
      background: "{primary}",
      foreground: "{primary-foreground}",
      hover: "{primary-hover}",
      active: "{primary-active}",
      radius: "{radius-md}",
      height: "{size-md}",
      paddingInline: "0.75rem",
      typography: "{text-label}",
      shadow: "{shadow-lit}",
      interactionColorTransition: "immediate",
    },
    "button-secondary": {
      background: "{card}",
      foreground: "{foreground}",
      border: "{border}",
      hover: "{accent}",
      radius: "{radius-md}",
      height: "{size-md}",
      paddingInline: "0.75rem",
      typography: "{text-label}",
      interactionColorTransition: "immediate",
    },
    "button-destructive": {
      background: "{destructive-subtle}",
      foreground: "{destructive-text}",
      hover: "{destructive-subtle-hover}",
      radius: "{radius-md}",
      height: "{size-md}",
      paddingInline: "0.75rem",
      typography: "{text-label}",
      interactionColorTransition: "immediate",
    },
    input: {
      background: "{secondary}",
      foreground: "{foreground}",
      border: "{input}",
      focusBorder: "{ring}",
      radius: "{radius-md}",
      height: "{size-md}",
      paddingInline: "0.75rem",
      typography: "{type-product-base}",
    },
    card: {
      background: "{card}",
      foreground: "{card-foreground}",
      border: "{border}",
      radius: "{radius-lg}",
      shadow: "none",
    },
    overlay: {
      background: "{popover}",
      foreground: "{popover-foreground}",
      border: "{border}",
      radius: "{radius-lg}",
      shadow: "{shadow-overlay}",
    },
    "menu-item": {
      foreground: "{foreground}",
      hover: "{accent}",
      radius: "{radius-sm}",
      height: "{size-md}",
      paddingInline: "0.5rem",
      typography: "{type-product-base}",
      interactionColorTransition: "immediate",
    },
  },
};
