#!/usr/bin/env node
// Before/after visual review — the capture half of the `/ship` visual step.
//
// WHAT IT DOES
//   Captures the affected showcase routes twice on THIS machine: once at the merge-base of the
//   current branch, once at the working tree. It then writes a structured report plus
//   before/after/diff images for a human — reading them with their agent — to judge.
//
// WHY IT IS NOT A GATE
//   A pixel difference is not a defect; only a person knows whether forty changed photographs were
//   the intent. Clearing a committed-baseline gate meant overwriting the very evidence under review,
//   which is why that gate never actually failed closed. This tool measures and reports; the
//   developer decides. Exit codes say so: 0 for ANY pixel outcome, 2 only when the tool could not
//   produce a report at all (a failed build, a dead server). A silent empty report would be the
//   fail-open behaviour this replaces.
//
// WHY THERE ARE NO COMMITTED BASELINES
//   Screenshots only compare when taken on the same platform AND the same CPU architecture. This
//   team is on mixed macOS and Windows and CI is a third machine, so no committed set can be
//   regenerated by everyone. Capturing both sides here, minutes apart, makes platform irrelevant.
//
// DIVISION OF LABOUR — do not collapse these:
//   measurement     Playwright's comparator. A 2px shift is a fact; a vision model can miss it.
//   interpretation  the developer's agent, reading before/after/diff.
//   decision        the developer. Never self-clear a diff.
//
// OUTPUT
//   .vrt-review/report.json
//   .vrt-review/<route-slug>[--full-page]--<project>/{before,after,diff}.png
//
// ZERO NEW DEPENDENCIES. Playwright already compares images, writes -expected/-actual/-diff PNGs,
// and reports machine-readable JSON. PNG dimensions are read straight from the IHDR header.

import { spawnSync } from "node:child_process";
import {
  copyFileSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Change → route mapping is shared with the contract lane. This lane's configuration is
// PIXEL_SCOPE; the contract lane's differs, and in one case in the opposite direction — see
// tooling/lib/route-scope.mjs.
import {
  createRouteScopeModel,
  escapeRegExp,
  selectRoutes,
} from "./lib/route-scope.mjs";
import {
  workingTreeChangeInventory,
  workingTreeContentHash,
} from "./lib/change-set.mjs";
import { planAffectedImpact } from "./lib/gate-impact.mjs";
import { atomicWriteJson } from "./lib/measurement-report.mjs";
import { CONTRACT_PROJECTS } from "./lib/gate-profile.mjs";
import {
  assertVrtSelectionAvailableOnEitherTree,
  expectedVrtLeaves,
  filterVrtSelectionForAuthority,
  readVrtAuthority,
  reconcileVrtLeaves,
  reconcileVrtSelection,
} from "./lib/vrt-selection.mjs";
import { assertVrtPageRoutesCurrent } from "./sync-vrt-page-routes.mjs";

const USAGE = `Usage: node tooling/vrt-review.mjs [options]

  --base <ref>     compare against this ref (default: origin/main, falling back to main)
  --all            capture every route, skipping change detection
  --full-pages     also capture the full-page lane (includes docs prose — noisy by default)
  --routes a,b     capture exactly these routes
  --keep-worktree  leave the base worktree in place for inspection
  --port <n>       base port for the two capture servers (default 3210)
  --dry-run        print the computed scope and exit without capturing

Output: .vrt-review/report.json plus per-entry before/after/diff images when captured.
Exit codes: 0 for any pixel outcome, 2 when no report could be produced.`;

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_DIR = join(ROOT, ".vrt-review");

// ── options ──────────────────────────────────────────────────────────────────────────────────────

function fail(message) {
  console.error(`vrt-review: ${message}`);
  process.exit(2);
}

function parseOptions(argv) {
  const options = {
    base: null,
    all: false,
    fullPages: false,
    routes: null,
    keepWorktree: false,
    port: 3210,
    dryRun: false,
  };
  for (let index = 0; index < argv.length; index++) {
    const flag = argv[index];
    const value = () => {
      const next = argv[++index];
      if (next === undefined) fail(`${flag} requires a value`);
      return next;
    };
    if (flag === "--base") options.base = value();
    else if (flag === "--all") options.all = true;
    else if (flag === "--full-pages") options.fullPages = true;
    else if (flag === "--routes")
      options.routes = value()
        .split(",")
        .map((route) => route.trim())
        .filter(Boolean);
    else if (flag === "--keep-worktree") options.keepWorktree = true;
    else if (flag === "--dry-run") options.dryRun = true;
    else if (flag === "--port") options.port = Number(value());
    else if (flag === "--help" || flag === "-h") {
      console.log(USAGE);
      process.exit(0);
    } else fail(`unknown option ${flag}\n\n${USAGE}`);
  }
  if (!Number.isInteger(options.port) || options.port < 1024)
    fail("--port must be an integer >= 1024");
  return options;
}

// ── shell ────────────────────────────────────────────────────────────────────────────────────────

function git(args, cwd = ROOT) {
  const result = spawnSync("git", args, { cwd, encoding: "utf8" });
  if (result.status !== 0)
    fail(`git ${args.join(" ")} failed:\n${result.stderr?.trim()}`);
  return result.stdout.trim();
}

function gitQuiet(args, cwd = ROOT) {
  const result = spawnSync("git", args, { cwd, encoding: "utf8" });
  return result.status === 0 ? result.stdout.trim() : null;
}

function run(command, args, options) {
  return spawnSync(command, args, { stdio: "inherit", ...options }).status ?? 1;
}

// ── Playwright invocation ────────────────────────────────────────────────────────────────────────

/** The `--grep` regex selecting exactly the chosen tests, or null to run all of them. */
function buildGrep(selection, options) {
  if (selection.routes === null) return null;
  const alternatives = [];
  if (selection.routes.size > 0)
    alternatives.push(
      `VRT state (${[...selection.routes].map(escapeRegExp).join("|")})$`,
    );
  const fullPage = options.fullPages
    ? new Set([...selection.routes, ...selection.fullPageRoutes])
    : selection.fullPageRoutes;
  if (fullPage.size > 0)
    alternatives.push(`VRT (${[...fullPage].map(escapeRegExp).join("|")})$`);
  if (selection.icons) alternatives.push("VRT icon chunk ");
  return alternatives.length > 0 ? alternatives.join("|") : null;
}

function capture({ cwd, snapshotDir, port, grep, update, jsonOutput }) {
  const args = ["exec", "playwright", "test", "components.spec.ts"];
  if (grep) args.push("--grep", grep);
  if (update) args.push("--update-snapshots");
  args.push("--reporter", jsonOutput ? "list,json" : "list");
  return run("pnpm", args, {
    cwd: join(cwd, "apps/docs"),
    env: {
      ...process.env,
      VRT_SNAPSHOT_DIR: snapshotDir,
      VRT_PORT: String(port),
      ...(jsonOutput ? { PLAYWRIGHT_JSON_OUTPUT_NAME: jsonOutput } : {}),
      // A capture is evidence for a human, never a pass/fail signal — retries would hide genuine
      // instability behind a green run, and `forbidOnly` belongs to gates.
      CI: "",
    },
  });
}

function listCapture({ cwd, snapshotDir, port, grep }) {
  const args = [
    "exec",
    "playwright",
    "test",
    "components.spec.ts",
    "--list",
    "--reporter=json",
  ];
  if (grep) args.push("--grep", grep);
  const result = spawnSync("pnpm", args, {
    cwd: join(cwd, "apps/docs"),
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
    env: {
      ...process.env,
      VRT_SNAPSHOT_DIR: snapshotDir,
      VRT_PORT: String(port),
      CI: "",
    },
  });
  if (result.status !== 0)
    throw new Error(
      `Playwright VRT --list failed: ${(result.stderr || result.stdout).trim()}`,
    );
  try {
    return flattenReport(JSON.parse(result.stdout));
  } catch (error) {
    throw new Error(`Playwright VRT --list JSON is corrupt: ${error.message}`);
  }
}

// ── report assembly ──────────────────────────────────────────────────────────────────────────────

/** PNG dimensions straight from the IHDR header — no image library needed. */
function pngSize(file) {
  if (!file || !existsSync(file)) return null;
  const bytes = readFileSync(file);
  if (bytes.length < 24) return null;
  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

const PIXEL_DIFF =
  /(\d+) pixels(?: \(ratio ([\d.]+) of all image pixels\))? are different/;
const SIZE_MISMATCH =
  /Expected an image (\d+)px by (\d+)px, received (\d+)px by (\d+)px/;
const MISSING_SNAPSHOT = /A snapshot doesn't exist at/;

/** Flatten the Playwright JSON report without erasing skipped/interrupted runtime outcomes. */
function flattenReport(report) {
  const out = [];
  const visit = (suite) => {
    for (const spec of suite.specs ?? [])
      for (const test of spec.tests ?? []) {
        const result = test.results?.at(-1);
        out.push({
          title: spec.title,
          project: test.projectName ?? "unknown",
          outcome: result?.status ?? "not-run",
          ok: result?.status === "passed",
          error: [
            result?.error?.message,
            ...(result?.errors ?? []).map((entry) => entry.message),
          ]
            .filter(Boolean)
            .join("\n"),
          attachments: (result?.attachments ?? []).filter(
            (attachment) => attachment.path && attachment.name,
          ),
        });
      }
    for (const child of suite.suites ?? []) visit(child);
  };
  for (const suite of report.suites ?? []) visit(suite);
  return out;
}

const slug = (route) => route.replace(/^\//, "").replace(/\//g, "-") || "home";

/**
 * Playwright normalises every snapshot path segment before writing it, collapsing runs of
 * punctuation to a single `-`. The spec names its captures `_docs_components_button-state.png`, so
 * what actually lands on disk is `-docs-components-button-state-<project>.png`. Reconstructing the
 * name without this produced a phantom `removed` entry for EVERY captured route — the names simply
 * never matched. Mirrors `sanitizeForFilePath` in playwright-core.
 */
const sanitizeForFilePath = (name) =>
  name.replace(/[\x00-\x2C\x2E-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F]+/g, "-");
const snapshotArg = (route, lane) =>
  sanitizeForFilePath(
    `${route.replaceAll("/", "_")}${lane === "fixture" ? "-state" : ""}`,
  );

/** Snapshot stems are mapped forward from the exact per-tree generated route authority. */

function routeByStemFor(authorities) {
  const stems = new Map();
  for (const authority of authorities) {
    for (const route of authority.fullPageRoutes) {
      stems.set(snapshotArg(route, "full-page"), { route, lane: "full-page" });
      if (authority.fixtureRoutes.includes(route))
        stems.set(snapshotArg(route, "fixture"), { route, lane: "fixture" });
    }
    for (let index = 1; index <= authority.iconChunkCount; index++)
      stems.set(
        sanitizeForFilePath(
          `${authority.iconsRoute.replaceAll("/", "_")}-icon-chunk-${index}`,
        ),
        { route: authority.iconsRoute, lane: "full-page", chunk: index },
      );
  }
  return stems;
}

/** The base-capture filenames a given test is responsible for, so "removed" can be detected. */
function snapshotNamesFor(test, authority) {
  const iconChunk = /^VRT icon chunk (\d+)$/.exec(test.title)?.[1];
  if (iconChunk)
    return [
      `${sanitizeForFilePath(`${authority.iconsRoute.replaceAll("/", "_")}-icon-chunk-${iconChunk}`)}-${test.project}.png`,
    ];
  const route = /VRT (?:state )?(\/\S*)/.exec(test.title)?.[1];
  if (!route) return [];
  const lane = test.title.startsWith("VRT state ") ? "fixture" : "full-page";
  return [`${snapshotArg(route, lane)}-${test.project}.png`];
}

function buildEntries(tests, baseSnapshots, head, routeByStem) {
  const entries = [];
  const covered = new Set();

  for (const test of tests) {
    for (const name of snapshotNamesFor(test, head)) covered.add(name);

    const route =
      /VRT (?:state )?(\/\S*)/.exec(test.title)?.[1] ??
      (test.title.startsWith("VRT icon chunk ") ? head.iconsRoute : test.title);
    const lane = test.title.startsWith("VRT state ") ? "fixture" : "full-page";
    const chunk =
      Number(/^VRT icon chunk (\d+)$/.exec(test.title)?.[1] ?? 0) || null;

    if (test.ok) {
      const expectedNames = snapshotNamesFor(test, head);
      if (expectedNames.length !== 1)
        throw new Error(
          `unchanged VRT leaf ${test.title}[${test.project}] has no canonical snapshot name`,
        );
      const expected = join(snapshotDir, expectedNames[0]);
      if (!existsSync(expected))
        throw new Error(
          `unchanged VRT leaf ${test.title}[${test.project}] has no readable baseline snapshot`,
        );
      entries.push({
        route,
        lane,
        project: test.project,
        status: "unchanged",
        changedPixels: 0,
        totalPixels: null,
        percentChanged: 0,
        images: {},
        ...(chunk ? { chunk } : {}),
      });
      continue;
    }

    const byName = new Map(
      test.attachments.map((attachment) => [attachment.name, attachment.path]),
    );
    const pick = (suffix) =>
      [...byName.entries()].find(([name]) => name.endsWith(suffix))?.[1] ??
      null;
    const expected = pick("-expected.png");
    const actual = pick("-actual.png");
    const diff = pick("-diff.png");

    const pixels = PIXEL_DIFF.exec(test.error);
    const sizes = SIZE_MISMATCH.exec(test.error);
    const isNew = MISSING_SNAPSHOT.test(test.error);
    const size = pngSize(actual) ?? pngSize(expected);
    const totalPixels = size ? size.width * size.height : null;
    const changedPixels = isNew
      ? totalPixels
      : pixels
        ? Number(pixels[1])
        : null;

    entries.push({
      route,
      lane,
      project: test.project,
      // A failure with no pixel evidence is a BROKEN capture (navigation error, timeout,
      // interrupted run), not a visual change. Reporting it as `changed` would invite a verdict on
      // an image that was never taken.
      status: isNew ? "new" : pixels || sizes ? "changed" : "broken",
      changedPixels,
      totalPixels,
      percentChanged:
        totalPixels && changedPixels != null
          ? Number(((changedPixels / totalPixels) * 100).toFixed(4))
          : null,
      ...(sizes
        ? {
            dimensions: {
              before: `${sizes[1]}×${sizes[2]}`,
              after: `${sizes[3]}×${sizes[4]}`,
            },
          }
        : {}),
      ...(pixels || sizes || isNew
        ? {}
        : {
            note:
              test.error.split("\n")[0] ||
              "the test produced no result — the capture is broken, not the component",
          }),
      images: { expected, actual, diff },
      ...(chunk ? { chunk } : {}),
    });
  }

  // A base-capture image with no test responsible for it at HEAD is a removed route.
  for (const file of baseSnapshots) {
    if (covered.has(file)) continue;
    const match = /^(.+?)-((?:mobile-)?chromium(?:-dark)?)\.png$/.exec(file);
    if (!match) continue;
    const known = routeByStem.get(match[1]);
    entries.push({
      route: known?.route ?? match[1],
      lane:
        known?.lane ?? (match[1].endsWith("-state") ? "fixture" : "full-page"),
      project: match[2],
      status: "removed",
      changedPixels: null,
      totalPixels: null,
      percentChanged: null,
      images: {
        expected: join(snapshotDir, file),
        actual: null,
        diff: null,
      },
      ...(known?.chunk ? { chunk: known.chunk } : {}),
    });
  }

  return entries;
}

/** Copy each entry's images into .vrt-review/ and rewrite the paths to be repo-relative. */
function materialise(entries) {
  for (const entry of entries) {
    const sources = entry.images;
    const directory = join(
      OUTPUT_DIR,
      `${slug(entry.route)}${entry.lane === "full-page" ? "--full-page" : ""}--${entry.project}`,
      ...(entry.chunk ? [`chunk-${entry.chunk}`] : []),
    );
    const images = {};
    for (const [role, source] of [
      ["before", sources.expected],
      ["after", sources.actual],
      ["diff", sources.diff],
    ]) {
      if (!source || !existsSync(source)) continue;
      mkdirSync(directory, { recursive: true });
      const destination = join(directory, `${role}.png`);
      copyFileSync(source, destination);
      images[role] = relative(ROOT, destination);
    }
    entry.images = images;
  }
}

function writeReport(payload) {
  mkdirSync(OUTPUT_DIR, { recursive: true });
  atomicWriteJson(join(OUTPUT_DIR, "report.json"), payload);
}

// ── main ─────────────────────────────────────────────────────────────────────────────────────────

const options = parseOptions(process.argv.slice(2));

const baseRef =
  options.base ??
  (gitQuiet(["rev-parse", "--verify", "--quiet", "origin/main"])
    ? "origin/main"
    : "main");
if (!gitQuiet(["rev-parse", "--verify", "--quiet", `${baseRef}^{commit}`]))
  fail(`base ref ${baseRef} does not resolve to a commit`);
const mergeBase = git(["merge-base", baseRef, "HEAD"]);
const startTree = workingTreeContentHash().hash;
const routeModel = createRouteScopeModel();
routeModel.assertCurrent();

// Diff the merge-base against the WORKING TREE, not against HEAD: the question is "what does my
// change do to the UI", and during /ship that change is often still uncommitted.
const inventory = workingTreeChangeInventory(mergeBase);
const changedFiles = inventory.changedFiles;
const impactPlan = planAffectedImpact(changedFiles, {
  metadataChanged: inventory.metadataChanged,
  binaryChanged: inventory.binaryChanged,
});
assertVrtPageRoutesCurrent({ root: ROOT });
const headAuthority = readVrtAuthority({ root: ROOT });
headAuthority.assertCurrent();

// The shared module throws on an unknown `--routes` value; this tool's contract is exit 2 with a
// `vrt-review:` prefix, so translate rather than letting a stack trace escape.
const routeSelection = (() => {
  try {
    return selectRoutes(changedFiles, options, routeModel.pixelScope);
  } catch (error) {
    return fail(error.message);
  }
})();
const selection = reconcileVrtSelection({
  routeSelection,
  impactLane: impactPlan.lanes.vrt,
  impactDigest: impactPlan.selectorDigest,
  explicitOverride: options.all || options.routes !== null,
  includeSelectedFullPages: options.fullPages,
});
if (workingTreeContentHash().hash !== startTree)
  fail("working-tree content changed during VRT authority/selector planning");
routeModel.assertCurrent();
const grep = buildGrep(selection, options);
const headSelection = filterVrtSelectionForAuthority(selection, headAuthority, {
  allowUnavailable: true,
});
const headExpectedLeaves = expectedVrtLeaves({
  selection: headSelection,
  allFullPageRoutes: headAuthority.fullPageRoutes,
  allFixtureRoutes: headAuthority.fixtureRoutes,
  projects: CONTRACT_PROJECTS,
  iconChunkCount: headAuthority.iconChunkCount,
});

console.log(
  `vrt-review: base ${baseRef} (${mergeBase.slice(0, 8)}) → working tree`,
);
console.log(
  `vrt-review: ${changedFiles.length} changed file(s); scope: ${selection.reason}`,
);

if (selection.routes !== null && grep === null) {
  console.log(
    "vrt-review: no visual surface changed — nothing captured.\n" +
      "            Report this as SKIPPED. It is not evidence of a clean diff.",
  );
  rmSync(OUTPUT_DIR, { recursive: true, force: true });
  writeReport({
    schema: 1,
    generation: "dynamic-vrt-review-v1",
    state: "safely-skipped",
    evidenceWritten: false,
    receiptWritten: false,
    evidenceEligibility: "human-review-only",
    base: { ref: baseRef, sha: mergeBase },
    tree: { started: startTree, completed: startTree, unchanged: true },
    scope: {
      mode: selection.mode,
      reason: selection.reason,
      reasonCode: selection.reasonCode,
      selectorDigest: selection.selectorDigest,
      commonPlanDigest: impactPlan.selectorDigest,
      disagreement: selection.disagreement,
      captured: false,
      routes: [],
      fullPageRoutes: [],
      icons: false,
    },
    summary: { changed: 0, unchanged: 0, new: 0, removed: 0, broken: 0 },
    reviewState: "not-required",
    entries: [],
  });
  process.exit(0);
}

console.log(
  selection.routes === null
    ? "vrt-review: capturing every route × 4 projects"
    : `vrt-review: capturing ${selection.routes.size} fixture(s)${
        selection.fullPageRoutes.size > 0 || options.fullPages
          ? ` + full pages`
          : ""
      }${selection.icons ? " + icon chunks" : ""} × 4 projects`,
);

if (options.dryRun) {
  if (selection.routes !== null) {
    for (const route of [...selection.routes].sort())
      console.log(`  fixture   ${route}`);
    for (const route of [...selection.fullPageRoutes].sort())
      console.log(`  full-page ${route}`);
  }
  console.log(`  grep: ${grep ?? "(none — every test)"}`);
  process.exit(0);
}

rmSync(OUTPUT_DIR, { recursive: true, force: true });
mkdirSync(OUTPUT_DIR, { recursive: true });
const scratch = mkdtempSync(join(tmpdir(), "vrt-review-"));
const snapshotDir = join(scratch, "snapshots");
mkdirSync(snapshotDir, { recursive: true });
const worktree = join(scratch, "base");
let worktreeAdded = false;

try {
  console.log(`\nvrt-review: [1/2] capturing base ${mergeBase.slice(0, 8)}…`);
  git(["worktree", "add", "--detach", "--quiet", worktree, mergeBase]);
  worktreeAdded = true;
  // The MEASUREMENT INSTRUMENT must be identical on both sides. If the base captured with its own
  // playwright config and capture spec, a change to either — a viewport, a wait, a mask — would show
  // up in every image as though the components had moved. Copy HEAD's harness over the base's so the
  // only variable is the component source. (It also makes the tool work against a base ref that
  // predates the harness entirely.)
  for (const harness of [
    "apps/docs/playwright.config.ts",
    "apps/docs/vrt/components.spec.ts",
    "apps/docs/vrt/page-routes.ts",
  ])
    copyFileSync(join(ROOT, harness), join(worktree, harness));
  copyFileSync(
    join(ROOT, "tooling/sync-vrt-page-routes.mjs"),
    join(worktree, "tooling/sync-vrt-page-routes.mjs"),
  );
  if (
    run("node", ["tooling/sync-vrt-page-routes.mjs"], { cwd: worktree }) !== 0
  )
    throw new Error("base VRT page-route generation failed");
  assertVrtPageRoutesCurrent({ root: worktree });
  const baseAuthority = readVrtAuthority({ root: worktree });
  baseAuthority.assertCurrent();
  const baseSelection = filterVrtSelectionForAuthority(
    selection,
    baseAuthority,
    {
      allowUnavailable: true,
    },
  );
  assertVrtSelectionAvailableOnEitherTree(
    selection,
    baseSelection,
    headSelection,
  );
  const baseExpectedLeaves = expectedVrtLeaves({
    selection: baseSelection,
    allFullPageRoutes: baseAuthority.fullPageRoutes,
    allFixtureRoutes: baseAuthority.fixtureRoutes,
    projects: CONTRACT_PROJECTS,
    iconChunkCount: baseAuthority.iconChunkCount,
  });
  const routeByStem = routeByStemFor([baseAuthority, headAuthority]);
  if (run("pnpm", ["install", "--frozen-lockfile"], { cwd: worktree }) !== 0)
    throw new Error("pnpm install failed in the base worktree");
  // Build only the docs' workspace dependencies; the docs build itself is Playwright's webServer.
  if (
    run(
      "pnpm",
      ["exec", "turbo", "run", "build", "--filter=@vegastack/docs^..."],
      { cwd: worktree },
    ) !== 0
  )
    throw new Error("workspace dependency build failed in the base worktree");
  const baseJsonReport = join(scratch, "base-report.json");
  let baseTests = [];
  let baseExecution =
    baseExpectedLeaves.length === 0 ? reconcileVrtLeaves([], []) : null;
  if (baseExpectedLeaves.length > 0) {
    const baseListed = listCapture({
      cwd: worktree,
      snapshotDir,
      port: options.port,
      grep,
    });
    reconcileVrtLeaves(baseExpectedLeaves, baseListed);
    const baseStatus = capture({
      cwd: worktree,
      snapshotDir,
      port: options.port,
      grep,
      update: true,
      jsonOutput: baseJsonReport,
    });
    if (baseStatus !== 0)
      throw new Error(`the base capture exited ${baseStatus}; expected 0`);
    if (!existsSync(baseJsonReport))
      throw new Error("the base capture produced no structured report");
    baseTests = flattenReport(JSON.parse(readFileSync(baseJsonReport, "utf8")));
    baseExecution = reconcileVrtLeaves(baseExpectedLeaves, baseTests, {
      execution: true,
      requirePassed: true,
    });
  }

  const baseSnapshots = readdirSync(snapshotDir).filter((file) =>
    file.endsWith(".png"),
  );
  const expectedSnapshotNames = baseExpectedLeaves
    .flatMap((leaf) => snapshotNamesFor(leaf, baseAuthority))
    .sort();
  const actualSnapshotNames = [...baseSnapshots].sort();
  if (
    JSON.stringify(expectedSnapshotNames) !==
    JSON.stringify(actualSnapshotNames)
  )
    throw new Error(
      `base snapshot universe mismatch: expected ${expectedSnapshotNames.length}, got ${actualSnapshotNames.length}`,
    );
  console.log(
    `vrt-review: base capture complete (${baseSnapshots.length} images)`,
  );

  console.log("\nvrt-review: [2/2] capturing the working tree…");
  const jsonReport = join(scratch, "head-report.json");
  let headTests = [];
  let headExecution =
    headExpectedLeaves.length === 0 ? reconcileVrtLeaves([], []) : null;
  if (headExpectedLeaves.length > 0) {
    const headListed = listCapture({
      cwd: ROOT,
      snapshotDir,
      port: options.port + 1,
      grep,
    });
    reconcileVrtLeaves(headExpectedLeaves, headListed);
    const headStatus = capture({
      cwd: ROOT,
      snapshotDir,
      port: options.port + 1,
      grep,
      update: false,
      jsonOutput: jsonReport,
    });
    if (![0, 1].includes(headStatus))
      throw new Error(
        `the working-tree capture exited ${headStatus}; expected 0 or visual-difference exit 1`,
      );
    if (!existsSync(jsonReport))
      throw new Error(
        "the working-tree capture produced no report — the build or server failed above",
      );
    headTests = flattenReport(JSON.parse(readFileSync(jsonReport, "utf8")));
    headExecution = reconcileVrtLeaves(headExpectedLeaves, headTests, {
      execution: true,
      requirePassed: false,
    });
  }
  const completedTree = workingTreeContentHash().hash;
  if (completedTree !== startTree)
    throw new Error("working-tree content changed during VRT capture");
  const entries = buildEntries(
    headTests,
    baseSnapshots,
    headAuthority,
    routeByStem,
  );
  materialise(entries);
  // Everything needing a decision first, largest change first inside that — so a reviewer triages by
  // magnitude instead of opening everything. `removed` and broken captures carry no pixel count but
  // still need a verdict, so they sort above `unchanged` rather than with it.
  entries.sort((a, b) => {
    const needsVerdict = (entry) => (entry.status === "unchanged" ? 1 : 0);
    return (
      needsVerdict(a) - needsVerdict(b) ||
      (b.changedPixels ?? Number.MAX_SAFE_INTEGER) -
        (a.changedPixels ?? Number.MAX_SAFE_INTEGER)
    );
  });

  const count = (status) =>
    entries.filter((entry) => entry.status === status).length;
  const summary = {
    changed: count("changed"),
    unchanged: count("unchanged"),
    new: count("new"),
    removed: count("removed"),
    broken: count("broken"),
  };
  writeReport({
    schema: 1,
    generation: "dynamic-vrt-review-v1",
    state: summary.broken > 0 ? "executed/fail" : "executed/pass",
    evidenceWritten: true,
    receiptWritten: false,
    evidenceEligibility: "human-review-only",
    base: { ref: baseRef, sha: mergeBase },
    tree: { started: startTree, completed: completedTree, unchanged: true },
    scope: {
      mode: selection.mode,
      reason: selection.reason,
      reasonCode: selection.reasonCode,
      selectorDigest: selection.selectorDigest,
      commonPlanDigest: impactPlan.selectorDigest,
      disagreement: selection.disagreement,
      captured: true,
      routes: selection.routes === null ? null : [...selection.routes].sort(),
      fullPageRoutes:
        selection.fullPageRoutes === null
          ? null
          : [...selection.fullPageRoutes].sort(),
      icons: selection.icons,
      grep,
      execution: {
        expectedLeaves: {
          base: baseExpectedLeaves.length,
          workingTree: headExpectedLeaves.length,
        },
        base: baseExecution,
        workingTree: headExecution,
      },
    },
    summary,
    reviewState:
      summary.changed + summary.new + summary.removed + summary.broken > 0
        ? "required"
        : "not-required",
    entries,
  });

  const notable = entries.filter((entry) => entry.status !== "unchanged");
  console.log(
    `\nvrt-review: ${summary.changed} changed · ${summary.new} new · ${summary.removed} removed · ${summary.broken} broken · ${summary.unchanged} unchanged`,
  );
  for (const entry of notable.slice(0, 25))
    console.log(
      `  ${entry.status.padEnd(9)} ${String(entry.changedPixels ?? "—").padStart(9)} px  ${entry.route} [${entry.project}${entry.lane === "full-page" ? " full-page" : ""}]`,
    );
  if (notable.length > 25)
    console.log(`  …and ${notable.length - 25} more in report.json`);
  console.log(
    `\nvrt-review: report written to ${relative(ROOT, OUTPUT_DIR)}/report.json`,
  );
  if (notable.length > 0)
    console.log(
      "vrt-review: READ every status-appropriate artifact: changed=Before/After/Difference,\n" +
        "            new=After, removed=Before, broken=error + available artifacts then rerun.\n" +
        "            Explain visible changes plainly, link absolute paths, and STOP. Never self-clear.",
    );
} catch (error) {
  console.error(`vrt-review: ${error.message}`);
  const failedTree = workingTreeContentHash().hash;
  writeReport({
    schema: 1,
    generation: "dynamic-vrt-review-v1",
    state: "unknown",
    evidenceWritten: false,
    receiptWritten: false,
    evidenceEligibility: "human-review-only",
    base: { ref: baseRef, sha: mergeBase },
    tree: {
      started: startTree,
      completed: failedTree,
      unchanged: failedTree === startTree,
    },
    scope: {
      mode: selection.mode,
      reason: selection.reason,
      reasonCode: selection.reasonCode,
      selectorDigest: selection.selectorDigest,
      captured: false,
    },
    error: error.message,
    summary: { changed: 0, unchanged: 0, new: 0, removed: 0, broken: 0 },
    reviewState: "unknown",
    entries: [],
  });
  process.exitCode = 2;
} finally {
  if (worktreeAdded && !options.keepWorktree)
    spawnSync("git", ["worktree", "remove", "--force", worktree], {
      cwd: ROOT,
    });
  if (options.keepWorktree)
    console.log(`vrt-review: base worktree kept at ${worktree}`);
  else rmSync(scratch, { recursive: true, force: true });
}
